### ISSUE TITLE
[Feature]: How to format x-axis?

### ISSUE THREAD

**Issue by sujjeee** [tremorlabs/tremor-npm#1008]
### What problem does this feature solve?

This is view of my chart
![image](https://github.com/tremorlabs/tremor/assets/101963203/f7ac349b-ec36-4aa9-a1d1-d76a0b657d7b)

how i can format the x-axis dates ??

like i want Mar 12 .... Mar18 ... 

we can format y axis but format x axis ? why??

**Comment by severinlandolt** [comment]
Hi! You would have to create your own formatting function that is applied to the data set before you pass it to the AreaChart. Let me if you need help with that, thanks!

**Comment by sujjeee** [comment]
@severinlandolt thanks for reply :)

yeah manage to make it work
![image](https://github.com/tremorlabs/tremor/assets/101963203/c3b6193c-5a9e-4963-8e05-cb9297ec2cb5)
