### ISSUE TITLE
[Bug]: Badge icons from documentation are not working with NextJS 14.2.2

### ISSUE THREAD

**Issue by shwarcu** [tremorlabs/tremor-npm#1019]
### Tremor Version

 @tremor/react: ^3.16.1

### Link to minimal reproduction

[https://codesandbox.io/p/devbox/brave-easley-nht8x6](https://codesandbox.io/p/devbox/brave-easley-nht8x6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv8d2ke400063j6lzw1evjlr%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv8d2ke300023j6lp4uzn5f2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv8d2ke300043j6lq55c1dna%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv8d2ke400053j6ld7qzjfzm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B42.68467855324941%252C57.31532144675059%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv8d2ke300023j6lp4uzn5f2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv8d2ke300013j6llp0bpyva%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clv8d2ke300023j6lp4uzn5f2%2522%252C%2522activeTabId%2522%253A%2522clv8d2ke300013j6llp0bpyva%2522%257D%252C%2522clv8d2ke400053j6ld7qzjfzm%2522%253A%257B%2522id%2522%253A%2522clv8d2ke400053j6ld7qzjfzm%2522%252C%2522activeTabId%2522%253A%2522clv8d4an800av3j6ltzzswzln%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clv8d4an800av3j6ltzzswzln%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clv8d2ke300043j6lq55c1dna%2522%253A%257B%2522id%2522%253A%2522clv8d2ke300043j6lq55c1dna%2522%252C%2522activeTabId%2522%253A%2522clv8d664j002r3j6llrb377dv%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv8d2ke300033j6lw809h9tb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clv8d664j002r3j6llrb377dv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clv8d65wz000yd8gedcnbg7x7%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A25.143979057591622%257D)

### Steps to reproduce

I went steb by step through https://www.tremor.so/docs/getting-started/installation
and then added a badge from this example
https://www.tremor.so/docs/ui/table#usage-example

in my page.tsx
```tsx
import { RiFlag2Line } from '@remixicon/react';
import { Badge } from '@tremor/react';

 <Badge color="emerald" icon={RiFlag2Line}>Active</Badge>
```

### What is expected?

Badge with an icon is rendered same as in the documentation

### What is actually happening?

![image](https://github.com/tremorlabs/tremor/assets/58426925/990d00d5-c734-4906-ae5e-bab2419644b4)

### What browsers are you seeing the problem on?

Microsoft Edge

### Any additional comments?

This seems to be the same problem as in https://github.com/tremorlabs/tremor/issues/879

**Comment by severinlandolt** [comment]
Hi! You would have to add "use client" to your page.tsx file.
