### ISSUE TITLE
[Feature]: TimeField to format the time in hh:mm:ss

### ISSUE THREAD

**Issue by chiragmak10** [tremorlabs/tremor-npm#1026]
### What problem does this feature solve?

time value gets auto formatted hh:mm:ss
https://mui.com/x/react-date-pickers/time-field/

**Comment by severinlandolt** [comment]
Hi! Thank you for your feature request, unfortunately, this won't make it into the package. However, we recently added a date picker with time functionality. You can get the time picker component here: https://github.com/tremorlabs/tremor-raw/blob/6974b7680880234d80e367e672137c98e42ecc27/src/components/DatePicker/DatePicker.tsx#L34
