### ISSUE TITLE
[Bug]:  How can we make the tooltip clickable? I'm unable to change the pointer-events attribute to all.

### ISSUE THREAD

**Issue by nextjs-tsadei** [tremorlabs/tremor-npm#1030]
### Tremor Version

v18.2.0+

### Link to minimal reproduction

....

### Steps to reproduce

-  Use the Bar chart 
- Create the custom-tooltip
-  try to click on any lable.

### What is expected?

want to make tooltip clickable.

### What is actually happening?

Not able to make tooltip clickable because of point-event is none

**Comment by severinlandolt** [comment]
Hi! It's not possible to make the tooltip it self clickable. If you wish to add such feature, you have to dive into [Recharts](https://recharts.org/en-US/) directly (it's what we use under the hood).
