### ISSUE TITLE
A special class property for the text input icon [Feature]: 

### ISSUE THREAD

**Issue by nodirbekrajaboff** [tremorlabs/tremor-npm#1033]
### What problem does this feature solve?

I can't change icon color when typing using ClassName

**Comment by severinlandolt** [comment]
Hi @nodirbekrajaboff! Unfortunately, we do not have any slots for targeting specific elements in the text input component. However, you could use arbitrary variants for this:
`<TextInput icon={SearchIcon} placeholder="Search..." className="[&>svg]:text-red-500" />`

![CleanShot 2024-05-13 at 17 22 30@2x](https://github.com/tremorlabs/tremor/assets/41927988/dce4414e-458c-4995-be96-20721c1f608d)

Another alternative: Try our new [Raw Input](https://raw.tremor.so/docs/inputs/input) component.

Hope this helps!
