### ISSUE TITLE
[Feature]: Allow tablecells to hold datepicker/select dropdown items without hiding

### ISSUE THREAD

**Issue by Yuheng7** [tremorlabs/tremor-npm#1034]
### What problem does this feature solve?

Right now, when any dropdown item is placed inside of a tablecell, it hides the dropdown unless you scroll down on the inner table itself. This only happens for the bottom few rows as they have dropdowns which naturally overflow past the bottom of the table.

(Please let me know if this is fixable with other workarounds right now!)

**Comment by severinlandolt** [comment]
Hi! I tried to replicate what you described and it seems to work for me.
![CleanShot 2024-05-13 at 17 07 36@2x](https://github.com/tremorlabs/tremor/assets/41927988/170a68c3-8f53-461c-9e5f-13d2d8463bde)

Could you share a replication of your issue? Thanks!

**Comment by severinlandolt** [comment]
Hi @Yuheng7! We add "overflow-auto" to the `<Table>` component. If you want to make it visible, add `<Table className="overflow-visible" />` Let me know if that helped :)

![CleanShot 2024-05-13 at 17 10 24@2x](https://github.com/tremorlabs/tremor/assets/41927988/c5a587c9-db3a-4823-aec9-da8fbea7a20a)

**Comment by Yuheng7** [comment]
className="overflow-visible" worked perfectly. Thank you so much!
