### ISSUE TITLE
[Feature]: Calendar / Agenda Component

### ISSUE THREAD

**Issue by lnstuder** [tremorlabs/tremor-npm#1047]
### What problem does this feature solve?

When visualizing events or generic date ranges, I have to rely on a text based solution. It would be very nice to have an agenda component, to visualize these things. You could also use it as an input component, with a user experience similar to outlook.

### What does the proposed API look like?

I image it being like the outlook calendar view. Possibly just the monthly view. An existing solution would be the [Kendo UI for React Scheduler](https://www.telerik.com/kendo-react-ui/components/scheduler/).

**Comment by severinlandolt** [comment]
Hi! Thanks for your feature request. We don't see a lot of added value when wrapping an Scheduler. Better to directly use existing solutions and style them with the tremor design tokens.
