### ISSUE TITLE
Tailwind installation instructions in documentation

### ISSUE THREAD

**Issue by asheikho99** [tremorlabs/tremor-npm#105]
Hi,

I was having a look at optional Tailwind installation step 2 paths added in `content: []` does not match Tailwind React installation guide.

I understand that the path could point to where needed, but it would be nicer to be matching with Tailwind documentation which will eliminate any confusions caused by this for new developers looking into the project.

**Tremor**
![image](https://user-images.githubusercontent.com/105573050/195440804-5781401c-aafa-415e-ae28-1d8bae3dc678.png)

**Tailwind**
![image](https://user-images.githubusercontent.com/105573050/195440748-e4330e71-75e4-4854-b3df-d274e3e3df85.png)

**Comment by ColaIan** [comment]
I believe Trevor currently primarily focuses on Next.js projects as suggested in their installation page, here attached the Tailwind CSS official installation guide for Next.js, please have a look, and if you would like to use the project with pure React, I guess you can just follow official tailwind installation guides as well :)
https://tailwindcss.com/docs/guides/nextjs
![image](https://user-images.githubusercontent.com/43201383/195524644-c9ff2bbe-9adb-4db7-a056-a954f040a7ea.png)

**Comment by asheikho99** [comment]
Thanks for the clarification @ColaIan
