### ISSUE TITLE
[Feature]: Allow toggling axisLine for XAxis and YAxis

### ISSUE THREAD

**Issue by alexbalonperin** [tremorlabs/tremor-npm#1058]
### What problem does this feature solve?

axisLine is hardcoded to false for all chart types. 
I would like to have a prop to modify that value in my project.

### What does the proposed API look like?

Pass a new prop called `showAxisLine: boolean` to configure showing XAxis and YAxis on all charts.

**Comment by severinlandolt** [comment]
Hey there! Thanks for the PR and bringing this up. We aim to keep our API lean and focused. Since we always use charts with these lines, we'll have to pass on this change. We appreciate your input though!
