### ISSUE TITLE
[Feature]: Progree bar color and background color

### ISSUE THREAD

**Issue by ParmPanwar** [tremorlabs/tremor-npm#1069]
### What problem does this feature solve?

For now only 1 color can implement on progress bar, and use opacity for background , But I want to show different color for background and bar color

**Comment by severinlandolt** [comment]
Hi @ParmPanwar ! This is not possible with the package. In your particular case, I recommend switching to our copy & paste version of the progress bar. There you can control this super easily! → https://raw.tremor.so/docs/visualizations/progress-bar
