### ISSUE TITLE
[Bug]: Select does not apply error styling in dark mode

### ISSUE THREAD

**Issue by jhoffmann-se** [tremorlabs/tremor-npm#1070]
### Tremor Version

3.17.2

### Link to minimal reproduction

https://github.com/jmhoffmann9612/tremor-select-darkmode-error-bug

### Steps to reproduce

1. Run `npm run dev` / `npx next dev`.
2. Open `localhost:3000` in browser.
3. Enable dark mode in system settings.

### What is expected?

Select component should apply error styling (red border and text) in dark mode.

### What is actually happening?

- Select component does not have error styling in dark mode.
- Light mode has the expected styling.

-----

![image](https://github.com/tremorlabs/tremor/assets/46888078/b83424d4-3e31-4ec4-aea4-c89a3c0a2650)
-----
![image](https://github.com/tremorlabs/tremor/assets/46888078/f2a37638-024e-4ff7-8fad-c61820cb295a)

### What browsers are you seeing the problem on?

Chrome, Firefox

### Any additional comments?

Not super familiar with the inner workings of the library, but it seems like `<Select />` elements get their error styling from `getSelectButtonColors` in `selectUtils.ts`.

https://github.com/tremorlabs/tremor/blob/3dc49f9adbb1886e3d06c3397f7dbab25f3eaf3b/src/components/input-elements/selectUtils.ts#L47-L48

It seems this bug happens because the expressions for when `hasError` is true do not include `dark:` modifiers, so `tailwind-merge` does not overwrite any previously set `dark:text-...` and `dark:border-...` like here:

https://github.com/tremorlabs/tremor/blob/3dc49f9adbb1886e3d06c3397f7dbab25f3eaf3b/src/components/input-elements/Select/Select.tsx#L125

-----

Patching the lines in `selectUtils.ts` from
```
hasError && "text-red-500 placeholder:text-red-500",
hasError ? "border-red-500" : "border-tremor-border dark:border-dark-tremor-border",
```
to
```
hasError && "text-red-500 placeholder:text-red-500 dark:text-red-500 dark:placeholder:text-red-500",
hasError ? "border-red-500 dark:border-red-500" : "border-tremor-border dark:border-dark-tremor-border",
```
with [patch-package](https://www.npmjs.com/package/patch-package) has worked in my project, but I so far cannot tell if this causes any unintended side effects.

**Comment by severinlandolt** [comment]
Thanks for noticing and thank for the patch suggestions 🫶

**Comment by severinlandolt** [comment]
Note: Will add this to the next fix version!
