### ISSUE TITLE
[Bug]: TabGroup doesn't follow the colours defined in tailwind.config.ts

### ISSUE THREAD

**Issue by ArifAA14** [tremorlabs/tremor-npm#1071]
### Tremor Version

3.17.2

### Link to minimal reproduction

https://github.com/ArifAA14/dashboards

### Steps to reproduce

- Install tremor.
- Install all dependencies
- Copy paste the tailwind.config.ts from tremor.so installation guide.
- Change branding colours from blue to any required colour
- Copy and paste the <TabsGroup> component as shown on tremor.so docs.

### What is expected?

The colour change should apply to the tabs such as the border for the active tab, the text-colour for the active tab but it doesn't. 

The colour changes seem to apply to other components such as Button but doesn't work for the TabsGroup.

### What is actually happening?

The default blue branding remains.

### What browsers are you seeing the problem on?

Chrome, Safari, Brave

**Comment by ArifAA14** [comment]
Just an update, I did find a temporary solution for this incase anyone is wondering. Feels redundant but this is the only thing that worked

`<Tab className="ui-selected:text-tremor-brand ui-selected:border-tremor-brand ">`

**Comment by jzfrank** [comment]
I would like to be assigned for this!

**Comment by merryfelloww** [comment]
Also would like to note that on top of that `color` prop is not applying color when hex color (i.e. `#ff0000` is passed), it replaces default color but doesn't apply any color instead of it. Even though correct class is applying.
Might be related bug

**Comment by severinlandolt** [comment]
Hi @ArifAA14, just released a beta for this, could you give it a try and report back? 

`npm i @tremor/react@3.17.4-beta-tab-color-fix.1`

**Comment by severinlandolt** [comment]
Hi @egorkavin, this is actually intended. The color prop accepts all colors we defined in our `Color` type. Custom hex does not work: 
![CleanShot 2024-06-22 at 00 29 15@2x](https://github.com/tremorlabs/tremor/assets/41927988/27d261ec-a38a-4219-8975-8c39b75ace80)

You find all accepted color names here: https://www.tremor.so/docs/layout/color-palette

**Comment by merryfelloww** [comment]
@severinlandolt Ah, got it, thanks!

**Comment by severinlandolt** [comment]
@egorkavin If you want to have full control over this, check out https://raw.tremor.so/docs/ui/tabs
