### ISSUE TITLE
[Feature]: Stacked Funnel Chart

### ISSUE THREAD

**Issue by jasperdegens** [tremorlabs/tremor-npm#1074]
### What problem does this feature solve?

The new funnel chart types have been amazing to show conversion funnels. Adding support for stacked bar charts would allow for visualizations to add an additional data feature. This would be especially meaningful for the `evolutionGradient` funnel type. 
<img width="280" alt="Frame 1948757732" src="https://github.com/tremorlabs/tremor/assets/1487543/f348490e-4dd8-460d-b9d3-91d4adaebe44">

### What does the proposed API look like?

API would add the following properties to the `FunnelChart` client component (added from `BarChart` component):

`stack: boolean`
`categories: string[]`
`index: string`

**Comment by severinlandolt** [comment]
Hi @jasperdegens,  can you provide a real-world example for this? Wouldn't you rather use a custom Sankey chart for this?

**Comment by jasperdegens** [comment]
Hey @severinlandolt, an example of how we would plan to use this would be showing a breakdown of conversion steps (i.e. Add credit card -> Copy invite code -> Send invite code) by UTM parameters, such as the referral source (i.e. Facebook, Twitter, Newsletter). This way, you could see your overall funnel, but also some additional details of what led to each conversion.

Sankey chart would also work, but have found the design of the tremor funnel really clean and straightforward!

**Comment by severinlandolt** [comment]
Hi there! Thanks a lot for your suggestion and for providing an example!

After looking into it, we’ve decided not to implement stacked bar charts in funnel charts. Handling small stack values could make the user experience less smooth, and we haven't seen this pattern work well in funnels. We want to keep our design clean and simple for everyone.

Thanks again for your request!
