### ISSUE TITLE
[Feature]: Progress Circle with different color by sector

### ISSUE THREAD

**Issue by biapar** [tremorlabs/tremor-npm#1081]
### What problem does this feature solve?

Is't possible to configure a Progress Circle with different color by value and different color on a sector like a gauge?
Thanks...

### What does the proposed API look like?

Is't possible to configure a Progress Circle with different color by value and different color on a sector like a gauge?
Thanks...

**Comment by severinlandolt** [comment]
Hi @biapar, this quite a custom solution. With the Tremor NPM, this is not possible. However, we offer most components as a copy & paste version. You can check it out here: https://raw.tremor.so/docs/visualizations/progress-circle

There you could build that requirement directly into the component.
