### ISSUE TITLE
Barchart with Rounded Corners

### ISSUE THREAD

**Issue by kamigerami** [tremorlabs/tremor-npm#1084]
### Discussed in https://github.com/tremorlabs/tremor/discussions/875

I would like to achieve the effect shown in the attached image, where the bars in the barchart have rounded corners. The default barchart currently does not support this feature. Could we add an option or modify the barchart component to support rounded corners? (I think recharts might support this)

![barchart_rounded](https://github.com/tremorlabs/tremor/assets/9321510/10141341-7ba4-4780-8405-5e3c67832f0a)

**Comment by mbauchet** [comment]
Not available in the NPM package, but check Tremor Raw you'll have full control over the charts

**Comment by kamigerami** [comment]
> Not available in the NPM package, but check Tremor Raw you'll have full control over the charts

great idea! will check it out!

Should I close this ticket?

**Comment by severinlandolt** [comment]
Yes, won't add this to the package. Happy coding!
