### ISSUE TITLE
[Question]: How can I increase the thickness of the donuts pie charts ?

### ISSUE THREAD

**Issue by lewis-ab** [tremorlabs/tremor-npm#1089]
I've tried adding the stroke-width of the svgs  inside the component using custom css but it's not working.

Any suggestion please

**Comment by severinlandolt** [comment]
Hi! This is not possible with the Tremor Package. This won't change until the next major release.

However, I created a donut chart in our copy and paste library. You can find it here: https://github.com/tremorlabs/tremor-raw/blob/feat/donut-chart/src/components/DonutChart/DonutChart.tsx

There you have full control over the donut shape.

More about Tremor Raw here: https://raw.tremor.so/docs/getting-started/installation
