### ISSUE TITLE
[Feature]: HPO Graphs

### ISSUE THREAD

**Issue by anaclumos** [tremorlabs/tremor-npm#1096]
### What problem does this feature solve?

We specifically need this type of graph. Can Tremor support this type of graph at the moment?

![image](https://github.com/tremorlabs/tremor/assets/31657298/ff74f01c-0dc3-4de3-acc5-8efec3d84de0)

**Comment by severinlandolt** [comment]
Hi @anaclumos! General answer: This is not possible with the Tremor NPM Package. 

However, with Tremor Raw (copy + paste), you could go and [refactor the line chart](https://raw.tremor.so/docs/visualizations/line-chart) to get closer to this. The problem I see is that you need 5 axes with different domains. This won't work.

Did a quick research. If I was in your shoes, I'd probably start from here: https://www.react-graph-gallery.com/parallel-plot

Happy coding!
