### ISSUE TITLE
[Bug]: Website UI broken

### ISSUE THREAD

**Issue by harshqback** [tremorlabs/tremor-npm#1097]
### Tremor Version

latest

### Link to minimal reproduction

NA

### Steps to reproduce

Drag the main page downward

### What is expected?

Component in the sidebar should not be shown over the announcement banner.

### What is actually happening?

![image](https://github.com/tremorlabs/tremor/assets/155417349/c2036308-7a5f-4a13-bd5d-132933c8f934)

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by severinlandolt** [comment]
Fixed!
