### ISSUE TITLE
[Bug]: Unable to update bar colors using `tremor-brand-default` from tailwindConfig.js

### ISSUE THREAD

**Issue by aakarsh-kumar-pst** [tremorlabs/tremor-npm#1100]
### Tremor Version

15

### Steps to reproduce

* Create a bar chart 
* Try updating the default color from tailwindconfig.js the BarChart is not getting updated. 

### What is expected?

Default color for BarChart should get updated

### What is actually happening?

Default color for BarChart remains blue 

### What browsers are you seeing the problem on?

* All

**Comment by severinlandolt** [comment]
Will take a look later this week!

**Comment by severinlandolt** [comment]
Hi! Had a closer look at your issue. 

The BarChart doesn't employ the tailwindconfig.js colors for the Bar Colors. Changing the DEFAULT token won't change the color in the bar chart. As you can [see here](https://www.tremor.so/docs/visualizations/bar-chart#theming), no token targets the default color.

If you wan't to use a custom color, check out our documentation section here: https://www.tremor.so/docs/visualizations/bar-chart#usage-example-with-a-custom-colors

If you need even more control, I'd suggest to have a look at our copy/paste components: https://raw.tremor.so/docs/visualizations/bar-chart
