### ISSUE TITLE
[Bug]: I want to show the 'Select All' option all the time, even when searching in the multi-select

### ISSUE THREAD

**Issue by dhiraj-avasthi-pst** [tremorlabs/tremor-npm#1101]
### Tremor Version

15

### Steps to reproduce

```
<MultiSelect>
        <MultiSelectItem value="all">Select All</MultiSelectItem>
        <MultiSelectItem value="1">Option 1</MultiSelectItem>
        <MultiSelectItem value="2">Option 2</MultiSelectItem>
        <MultiSelectItem value="3">Option 3</MultiSelectItem>
 </MultiSelect>
```

### What is expected?

whenever we are searching for a field, suppose I search for option 1, it should show me Select All and option 1.
<img width="336" alt="Screenshot 2024-07-09 at 10 36 06 PM" src="https://github.com/tremorlabs/tremor/assets/97656517/38135944-6a32-449d-8b2a-7b43e6e76fc2">

### What is actually happening?

I don't have an option to manipulate the filter fields, as I want to show the 'Select All' option while filtering the options

### Any additional comments?

https://github.dev/tremorlabs/tremor/blob/main/src/components/input-elements/MultiSelect/MultiSelect.tsx#L58

<img width="763" alt="image" src="https://github.com/tremorlabs/tremor/assets/97656517/e0555830-7281-46ec-ac15-3f2deac5e408">

**Comment by severinlandolt** [comment]
Hi @dhiraj-avasthi-pst! Unfortunately, this is not possible with the current implementation of this MultiSelect component. We do not have plans to change this in the future, so you would have to build this yourself :)
