### ISSUE TITLE
[Bug]: in IOS all the inputs has a zoom in automatically

### ISSUE THREAD

**Issue by carloswiboo** [tremorlabs/tremor-npm#1104]
### Tremor Version

3.17.4

### Link to minimal reproduction

https://operadorv2.operadores.com/

### Steps to reproduce

Enter with an iOS mobile phone to produce the error when the inputs are hover

### What is expected?

Don't do that zoom in, because it moves all my UI

### What is actually happening?

Zoom in automatically in my UI

**Comment by severinlandolt** [comment]
This is actually a feature of iOS. If you want to remove this, you have to generally increase the font size in your inputs. I suggest increasing this in your config:

```diff
-  "tremor-default": ["0.875rem", { lineHeight: "1.25rem" }],
+  "tremor-default": ["1rem", { lineHeight: "1.5rem" }],
```
