### ISSUE TITLE
[Feature]: Enabling area gradient for a subset of all categories

### ISSUE THREAD

**Issue by lpatino10** [tremorlabs/tremor-npm#1105]
### What problem does this feature solve?

This feature would be purely visual, but while using the `AreaChart`, I'd love to be able to specify which categories get the area under their line highlighted. It could serve as a visual anchor for a "key" category. An example is for comparing a property's revenue against projected revenue and the revenue of comparable properties in the same market:

<img width="903" alt="Screenshot 2024-07-18 at 2 08 18 PM" src="https://github.com/user-attachments/assets/d8ea6a32-248b-4247-888a-a10577a8a667">

### What does the proposed API look like?

API-wise, I picture this as a new prop on the `AreaChart` to specify category names matching the ones supplied to the `categories` prop:

```jsx
<AreaChart
  data={chartData}
  index="date"
  categories={['Income', 'Projected income', 'Market comparables']}
  // New prop example
  categoriesWithGradient={['Income']}
/>
```

**Comment by severinlandolt** [comment]
Hi @lpatino10 ! This prop is super use-case specific, so we won't be adding this. However, we have *fully* customizable variant of our AreaChart here: https://raw.tremor.so/docs/visualizations/area-chart

There, you could add your custom logic if a gradient should be displayed or not!
