### ISSUE TITLE
[Feature]: Upgrade @headless/ui to v2

### ISSUE THREAD

**Issue by andreibarabas** [tremorlabs/tremor-npm#1113]
### What problem does this feature solve?

v1.7 has not had a patch since April 2024, and v2 has a lot of new bug fixes, especially around ARIA.

**Comment by severinlandolt** [comment]
Will do a big tailwind update once v4 is released!

**Comment by Kiryous** [comment]
hey @severinlandolt! I just updated to NextJS 15 and build is broken due to 
```
./node_modules/@tremor/react/node_modules/@headlessui/react/dist/utils/stable-collection.js
Attempted import error: '__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED' is not exported from 'react' (imported as 'r').
```
Could we have @headless/ui@2.2.0, please?

**Comment by fabioriva** [comment]
Same issue, I switched back to nextjs 14

**Comment by atilladeniz** [comment]
is there any solution? have the same issue

**Comment by severinlandolt** [comment]
Hi all! I tested it internally, and looked good to me. Would be great to have you test it too!

**Comment by atilladeniz** [comment]
> Hi all! I tested it internally, and looked good to me. Would be great to have you test it too!

It works for me! thanks a lot!
