### ISSUE TITLE
[Feature]: Programmatically hover over a chart. 

### ISSUE THREAD

**Issue by simlarsen** [tremorlabs/tremor-npm#1115]
### What problem does this feature solve?

Please creare a prop to programmatically hover over a chart and show tooltips. Users dont have to use mouse to hover when they see other data outside the chart component and hover over those, we need them to see the chart tooltip on the chart. 

### What does the proposed API look like?

xAxisMarker={valueOfXAxis}

**Comment by severinlandolt** [comment]
Hi! We don't see this as a useful scope to incorporate it in the npm package. I'd suggest switching to our raw components here, and add the specific feature directly: https://raw.tremor.so/docs/visualizations/area-chart
