### ISSUE TITLE
[Feature]: Improvement in Date Picker.

### ISSUE THREAD

**Issue by ptk-dev** [tremorlabs/tremor-npm#1118]
### What problem does this feature solve?

It is too much hard to pick a date which of another year. Beacuse the current picker dows not allows to pick months or years directly. For example; Try to pick 12 dec 2010, or your dob. it's of course DIY.

**Comment by severinlandolt** [comment]
Hi! We won't add this to the npm package date picker. However, you could it add to our new date picker yourself: https://tremor.so/docs/inputs/date-range-picker by switching the caption layout to "Dropdown" https://daypicker.dev/v8/api/type-aliases/CaptionLayout
