### ISSUE TITLE
[Feature]: Funnel report

### ISSUE THREAD

**Issue by tmskpf** [tremorlabs/tremor-npm#1120]
### What problem does this feature solve?

What problem does this feature solve?
I would really love to have a tremor based funnel charts

Funnel charts are particularly useful for visualizing and solving problems related to processes or workflows that have sequential steps, where there is a progressive reduction in data at each stage.

### What does the proposed API look like?

What does the proposed API look like?

- Define the stages of the funnel (e.g., Visitors, Signups, etc.) and their corresponding values.
- Customize the chart’s appearance if needed, such as setting specific colors, adjusting label formats, or enabling animations.
- Render the chart to display it on the web page.

**Comment by mbauchet** [comment]
Funnel chart is already available. Check it: https://tremor.so/docs/visualizations/funnel-chart
