### ISSUE TITLE
[Feature]: Support different color for bars in bar chart 

### ISSUE THREAD

**Issue by sourabh-singla** [tremorlabs/tremor-npm#1129]
### What problem does this feature solve?

Currently tremor bar chart doesn't support different color to different bar. I have a use case to provide different color.
Could we have this asap? 

### What does the proposed API look like?

![Screenshot 2024-09-04 095122](https://github.com/user-attachments/assets/aa106511-02f6-4a71-98c9-17d4948e98df)

**Comment by severinlandolt** [comment]
Hi! If you need this asap, I'd suggest you use our copy-and-paste chart: https://tremor.so/docs/visualizations/bar-chart

There you can get rid of the color mapping or provide a new prop to color charts individually. 

The ability to color each bar individually neccessitates a change to the package and mapping logic we don't want to have.
