### ISSUE TITLE
[Bug]: Card component does not respect border-none

### ISSUE THREAD

**Issue by lidermanrony** [tremorlabs/tremor-npm#1133]
### Tremor Version

3.18.2

### Link to minimal reproduction

https://github.com/lidermanrony/tremor-issue-repro

### Steps to reproduce

1. `npm i`
2. `npm run dev`

or use your favorite package manger (pnpm / yarn)

see the card on screen - it has a shadow even though shadow is none.

### What is expected?

no shadow to be shown since `shadow-none` was specified as a className.

### What is actually happening?

![image](https://github.com/user-attachments/assets/23dd6d25-1511-4bca-8f41-8e2597d9dd42)

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by severinlandolt** [comment]
Hi @lidermanrony ! I suppose this connects to how `tailwind-merge` resolves the shadow styles. I cloned your reproduction and was able to get rid of the shadow by adding **!** to the tailwind utility → `!shadow-none`. Let me know if that helps :)

**Comment by severinlandolt** [comment]
Hi @lidermanrony again, I released a beta `npm i @tremor/react@3.18.3-beta-tailwind-merge-update.1` where I updated tailwind-merge. Worked in my local tests. Can you give it a try and report back?

**Comment by lidermanrony** [comment]
> Hi @lidermanrony again, I released a beta `npm i @tremor/react@3.18.3-beta-tailwind-merge-update.1` where I updated tailwind-merge. Worked in my local tests. Can you give it a try and report back?

Tested and this indeed resolves the issue. Thank you!

**Comment by severinlandolt** [comment]
Great, will release this soon!
