### ISSUE TITLE
Legend colors not matching labels correctly in tooltip

### ISSUE THREAD

**Issue by angelhodar** [tremorlabs/tremor-npm#115]
Hey! First of all thank you for creating this amazing library. I am giving it a try for some charts and I am going really fast! Just noticed a bug when rendering the dot colors in legend because it does not match properly with the data sometimes. I have prepared a codesanbox with the real data that is giving the error but hiding users personal info:

![image](https://user-images.githubusercontent.com/26228709/196449463-0d681523-a993-486d-a48e-3978cd78e9f3.png)

https://codesandbox.io/s/adoring-thunder-owrnsj?file=/src/App.js

As you can see the colors in the tooltip are rendered exactly as the categories order but the data doesnt always have that order because statistics may change between users even in terms of being undefined or not (which are correctly rendered as value 0).

**Comment by mitrotasios** [comment]
hey @angelhodar, glad that you like the library! Good catch, that shouldn't be the case. Thanks for submitting this! Will try to fix as soon as possible!

**Comment by mitrotasios** [comment]
hey @angelhodar, the issue should now be fixed with release `v1.0.10`. Thanks for submitting the this!
