### ISSUE TITLE
Add year selector for DatePicker

### ISSUE THREAD

**Issue by angelhodar** [tremorlabs/tremor-npm#116]
The DatePicker component is really clean and awesome but its tedious to use as a birth input for example because it only supports navigating by months. Adding some sort of year selector would make it perfect

**Comment by christopherkindl** [comment]
Thanks for your feedback and testing our product, @angelhodar! Valid point, we will take this into consideration!

If you have any further feedback or feature wishes, feel free to share! :)

**Comment by christopherkindl** [comment]
@angelhodar I saw on your profile that you code in python as well - Would a "Python to HTML/CSS/JS approach" be appealing to you as well (e.g. streamlit) or do you like to tackle web development tasks in a classic front-end manner?

**Comment by angelhodar** [comment]
@christopherkindl In the past I used Python a lot to build backends (FastAPI) and cron scripts for web scraping and so on, but at the moment I only use it in notebooks to manipulate data as I am more productive than using JS for that tasks. I am full stack JS developer (NextJS front and Node back) so I use to tackle tasks in the classic manner. I didnt know about streamlit but it seems quite interesting, tbh I am not an expert in frontend (thats why I love libraries that make my life easier like tremor haha). Im a backend boy

**Comment by christopherkindl** [comment]
@angelhodar very interesting and thanks. This definitely helps to better understand our community :)
