### ISSUE TITLE
Allow charts adjustable y-axis range

### ISSUE THREAD

**Issue by StefBrands** [tremorlabs/tremor-npm#118]
I noticed that the y-axis will always start at 0.  So for example if all your values are somewhere between 80 and 100 you get very little detail in the line charts. Is there currently a way to (dynamically) adjust the y-axis so you preserve more detail? Or would this need to be a new feature?

**Comment by christopherkindl** [comment]
Hi @StefBrands, thanks for pointing this out and testing our library. We will take this into consideration and make it more dynamically adjustable! :)

If you have further feedback or feature wishes, feel free to share :)

**Comment by souravmondal93** [comment]
@christopherkindl Please assign this issue to me. I have already raised a PR for the changes. If there are any review comments, I will take them up.

**Comment by christopherkindl** [comment]
Hi @souravmondal93, many thanks for the PR and being that fast - Really appreciate it :) We are working hard on releasing v1.1.0 soon. After that, we will pick up the open PRs!
