### ISSUE TITLE
Horizontal and vertical lines in Charts

### ISSUE THREAD

**Issue by 1nfinite9** [tremorlabs/tremor-npm#121]
I'm finding it very easy to create and customize dashboards even with little to no prior React experience. It would be great if there's capability to add horizontal or vertical lines to mark significant points in a chart in the future.

**Comment by severinlandolt** [comment]
Hey @1nfinite9, thank you for your feedback. If I understood correctly, you are talking about adding a `ReferenceLine` property like this: [https://recharts.org/en-US/api/ReferenceLine](https://recharts.org/en-US/api/ReferenceLine)?

We will definitely take such a feature into consideration in a future release.

**Comment by 1nfinite9** [comment]
Yes, exactly this! Thank you putting this into consideration!

**Comment by souravmondal93** [comment]
Hi @severinlandolt, can you please assign this issue to me? Most of the changes are done for `AreaChart`, I will extend the same for other chart types and raise a PR.

**Comment by severinlandolt** [comment]
Cf. #164

**Comment by BarakChamo** [comment]
@severinlandolt following up here as all PRs and issues seem to be closed, would be great to have support for passing references to charts, or otherwise leveraging recharts' reference elements (dots, lines and areas)

**Comment by zhiqingchen** [comment]
Is there any way to import [ReferenceLine](https://recharts.org/en-US/api/ReferenceLine)? This is a commonly used feature.
