### ISSUE TITLE
How to use SelectBox and MultiSelectBox in forms?

### ISSUE THREAD

**Issue by Mrahmani71** [tremorlabs/tremor-npm#122]
Hello, I can't use SelectBox and MultiSelectBox in forms and the page refreshes itself. Is this a bug or is there a problem in my code?

![2022-10-19-11-09-34](https://user-images.githubusercontent.com/13013819/196652026-b1263672-a3e2-4bca-9caf-7a20fdad7b59.gif)

**Comment by angelhodar** [comment]
@Mrahmani71 Probably the button is making a submit.  I dont know if there is a way to wrap the component and make a preventDefault to avoid the submit. It should be fixed by simply adding a ```type="button"``` property in the select components wherever there is a button

**Comment by mitrotasios** [comment]
hey @Mrahmani71, thanks for submitting this. This behaviour is not expected, will fix this as soon as possible!

**Comment by Mrahmani71** [comment]
thank you, if it is possible to correct this error also,
in this page **[link](https://www.tremor.so/docs/components/select)**
![123456](https://user-images.githubusercontent.com/13013819/196665793-2b2a2eb8-a3ef-4798-86e9-b862fc474d14.jpg)

❌ `placehoder="Select..."`
✅ `placeholder="Select..."`

**Comment by mitrotasios** [comment]
Oh yeah thanks, will do!

**Comment by severinlandolt** [comment]
@mitrotasios I fixed the typo in the docs.

**Comment by Mrahmani71** [comment]
Excuse me, is it possible for you to add **scroll-snap** for **Tablist**? 
thanks


![1234](https://user-images.githubusercontent.com/13013819/197075408-b5142b4e-774b-4db6-b206-d764e6a7e8b1.png)

**Comment by mitrotasios** [comment]
We had that discussion for some time and we concluded that from a UX perspective a very long tab list is not ideal. This is why we opted for not having a scroll function. In such cases a dropdown is probably more suitable.

**Comment by mitrotasios** [comment]
The issue should now be fixed in `v1.0.9`. Please let us know if you encounter further bugs :)
