### ISSUE TITLE
Does it support TypeScript ?

### ISSUE THREAD

**Issue by code-matter** [tremorlabs/tremor-npm#123]
Current implementation doesn't seem to support TS. Will there be a release for TS?

**Comment by severinlandolt** [comment]
Hey @code-matter, thank you for reaching out. The library supports TypeScript. Can you provide an example where you think TypeScript is not supported/working? That would be great.

**Comment by code-matter** [comment]
> Hey @code-matter, thank you for reaching out. The library supports TypeScript. Can you provide an example where you think TypeScript is not supported/working? That would be great. 

Literally fixed my problems the second I posted this. Sorry for that!

**Comment by severinlandolt** [comment]
Super, have fun coding!
