### ISSUE TITLE
Usage in Deno Deploy via esm.sh?

### ISSUE THREAD

**Issue by miguelrk** [tremorlabs/tremor-npm#127]
Hello! Can this library be used on Deno Deploy? I have tried importing it with https://esm.sh/ to no success. Any pointers are greatly appreciated!

**Comment by severinlandolt** [comment]
Heya @miguelrk, thank you for reaching out and testing our library. I did not know esm.sh before but I would be super interested in hearing more about our use case, i.e. why do you want to use the library with Deno deploy?

**Comment by miguelrk** [comment]
@severinlandolt hadn't seen this! Thanks for the response. The use case us using Deno Deploy to server-side render tremor-built UIs. I tried using esm.sh to import tremor and got halfway since SSR is not the usual way of using tremor (e.g. had trouble importing and injecting the stylesheet). Anyways I'll try to post a more detalied comment in a minute, I believe this use case and more info on this might serve someone else also in the future

**Comment by rklf** [comment]
@miguelrk Did you succeed somehow?

**Comment by miguelrk** [comment]
@rklf nope, I couldn't get it to work and moved on, sorry.
