### ISSUE TITLE
Label rotation for x axis

### ISSUE THREAD

**Issue by angelhodar** [tremorlabs/tremor-npm#128]
When there are enough data bars, some names are hidden even though its shown in the legend. A solution could be to allow to rotate the x labels by some degree to allow more names to be shown or even make it automatically given the amount of bars and space available

**Comment by severinlandolt** [comment]
Hey @angelhodar, thank you for using our library. This sounds reasonable, thank you for reaching out. We will consider this feature for one of our next releases.

**Comment by severinlandolt** [comment]
Recharts reference: [https://recharts.org/en-US/api/XAxis#angle](https://recharts.org/en-US/api/XAxis#angle)

**Comment by severinlandolt** [comment]
Hello all, after considering this for a long time, we decided to not implement this feature. In general, we would have never used this ourselves, and rather opted to create shorter labels or even better, use the `layout = "vertical"` option. Thank you all for sticking around and being part of this community!
