### ISSUE TITLE
issue with date picker / dropdown changing height when values assigned

### ISSUE THREAD

**Issue by thornec** [tremorlabs/tremor-npm#134]
When the value of the date picker and dropdown is empty the height is normal and as shown in the documentation.
<img width="1334" alt="normal" src="https://user-images.githubusercontent.com/46328659/197190778-e2407fa4-cff4-4ac4-979c-3f55e1e60473.png">

 When a value is selected the height of them seems to change and look a bit more blocky, anything I can do to fix the sizing?

<img width="1337" alt="enlargd" src="https://user-images.githubusercontent.com/46328659/197190862-ab0098ec-cb26-474d-a0ca-c76182c30735.png">

**Comment by mitrotasios** [comment]
Hi @thornec, thanks for spotting this! Would you mind sharing some kind of code snippet so that I can have a look at it in a bit more detail?

**Comment by Junaid300** [comment]
I am not sure about this issue  May be he has added additional library for styling that is causing conflict. Is it cause conflict with tailwind ?  
I am using Vite and Tailwind 
here is the screenshot
![image](https://user-images.githubusercontent.com/66414908/199989257-2c7d1e83-14c8-45c0-bc5e-e9a8d7fc1f60.png)

Here is my code: 
https://stackblitz.com/edit/vitejs-vite-nvxrbb?file=tailwind.config.cjs,src%2Findex.css,src%2FApp.jsx,src%2Fmain.jsx,package.json&terminal=dev

**Comment by mitrotasios** [comment]
hi @Junaid300, this is a specificity issue introduced by tailwinds pre-flight config. Specifically, this part:
```
/*
1. Correct the inability to style clickable types in iOS and Safari.
2. Remove default button styles.
*/

button,
[type='button'],
[type='reset'],
[type='submit'] {
  -webkit-appearance: button; /* 1 */
  background-color: transparent; /* 2 */
  background-image: none; /* 2 */
}
```
We are evaluating how we can best increase specificity for our button elements to avoid this kind of behaviour. For now, I would suggest that you first import the `index.css` file in your project and then the `tremor.css` file in your `main.jsx`. This should work for now.

Please refer to this issue for more details: https://github.com/tailwindlabs/tailwindcss/issues/6602
