### ISSUE TITLE
Allow classname as prop on table components

### ISSUE THREAD

**Issue by frankudoags** [tremorlabs/tremor-npm#135]
Realised that i could not add classnames to some table Components like tableHead, I think adding an optional classname prop to the components for extra styling would be lovely. Would love that. Open to even working with the team to accomplish that. Thank you.

**Comment by frankudoags** [comment]
This would enable the addition of more personal styling to table components. Noticed almost all the table components do not accept classnames as optional props

**Comment by severinlandolt** [comment]
Relates to: #75
