### ISSUE TITLE
component request: heatmap

### ISSUE THREAD

**Issue by nektro** [tremorlabs/tremor-npm#137]
curious if your guidance would be to implement it with a table or if a custom Tremor component makes sense

**Comment by severinlandolt** [comment]
Hey, @nektro thank you for your feedback. We will discuss this internally. I am very curious about which use cases you want to cover with this chart, can you tell us a little bit more about that? :)

**Comment by nektro** [comment]
similar to the line chart its a way to show the feed from a single stream over time

![image](https://user-images.githubusercontent.com/5464072/197470418-f3fabf4d-b595-455d-a686-89807cc1d552.png)

however it uses color rather than height and can show longer spans of time since its more dense

![image](https://user-images.githubusercontent.com/5464072/197470755-3ff5fe6d-8b32-41ef-aa74-186ab80a4a30.png)

![image](https://user-images.githubusercontent.com/5464072/197471304-3b989a6d-7234-43ab-8f8f-89326dcc3026.png)

**Comment by AbdelrhmanHamouda** [comment]
I wold like to also add a use case: 
- tracking a specific activity over time. As an examples, track users login overtime in a specific day where the "hotter" a cell is, the more occurrences of that activity happened and in this example, it means more logins

**Comment by christopherkindl** [comment]
Hi @AbdelrhmanHamouda, many thanks for describing your use case! This definitely helps us when designing the components :)

**Comment by vinhloc30796** [comment]
Another set of use cases:

- correlation analysis
- cohort analysis (with metrics like retention rate, total revenue)

I'd love to help build this out - but I'll probably need some guidance on where/how to start.

The closest thing that Tremor has right now is the [Tracker](https://www.tremor.so/docs/components/tracker) component. Perhaps a good way to start is build on top of it: (a) enabling rows (b) enabling auto calculation of color gradient

**Comment by nektro** [comment]
Oh good eye, you can probably make a Heapmap by stacking a few Trackers on top of each other

**Comment by mbauchet** [comment]
@severinlandolt @christopherkindl Any interest on this chart? 
I think we can dig with multiple combined Scatter charts like this: 
<img width="789" alt="Capture d’écran 2023-07-23 à 19 45 54" src="https://github.com/tremorlabs/tremor/assets/90607026/af8a73c7-12d5-471b-b958-70c267636567">

I may try to make a PR for this if there is any interest for you. (We'll have to discuss about data formatting)

**Comment by alroniks** [comment]
It would be nice to have such kind of component that be tuned for some specific cases. One of them is to build a chart for tracking user retention using cohort analysis.

Example:
<img width="1194" alt="Screenshot 2023-11-08 at 16 58 08" src="https://github.com/tremorlabs/tremor/assets/303498/9a516484-674f-4611-9016-695b97de892c">

**Comment by severinlandolt** [comment]
Hi all! This component is super specific to your personal use case. We don't see much added value by giving you an generalised heat map. Rolling out a one-size-fits-all component and remaining a simple API won't be a good fit for this. Thanks for the discussion!
