### ISSUE TITLE
Feature request - multiple calendars in datepicker

### ISSUE THREAD

**Issue by Newbie012** [tremorlabs/tremor-npm#138]
It would have been great if there was a way to display x numbers of calendars in the datepicker (preferably two). This is useful when you went to let your users pick a range that can be longer that a month without the extra clicks

**Comment by severinlandolt** [comment]
Hey, @Newbie012 thank you for reaching out. Do you have a particularly well-executed example in mind? Would be great to hear.

**Comment by Newbie012** [comment]
Sure - https://reactdatepicker.com/#example-multiple-months

**Comment by severinlandolt** [comment]
Hi! @Newbie012 we are not going to add this feature in our current date picker. However: We recently launched Tremor Raw, a copy & paste library for React components. There we have a [new version of the [DatePicker](https://raw.tremor.so/docs/input/date-range-picker), where you have full control over this. Happy coding ⌨️
![CleanShot 2024-04-12 at 20 58 55@2x](https://github.com/tremorlabs/tremor/assets/41927988/d3228ee7-9a6d-4fb5-a7bf-54e3c753d907)
