### ISSUE TITLE
Is it possible to have multiple data points per day, use month as the dataKey?

### ISSUE THREAD

**Issue by j2is** [tremorlabs/tremor-npm#143]
I was looking to do something like this where the x axis shows the month, and the tooltip shows the hour as well as the population growth rate, is it possible?
```
const chartdata = [
  {
    month: "Oct",
    hour: "8th 01:00"
    "Population growth rate": 1.74,
  },
  {
    month: "Oct",
    hour: "8th 02:00"
    "Population growth rate": 1.93,
  },
  {
    month: "Oct",
    hour: "8th 03:00"
    "Population growth rate": 1.9,
  },
  {
    month: "Oct",
    hour: "8th 04:00"
    "Population growth rate": 1.98,
  },
  {
    month: "Oct",
    hour: "8th 05:00"
    "Population growth rate": 2,
  },
];
```

**Comment by severinlandolt** [comment]
Hey @j2is, the [datakey property](https://www.tremor.so/docs/components/line-chart) can only take one input. The tooltip depends on the dataKey property as well. Everything that should be displayed in the Chart (i.e. Line and Tooltip) has to be passed as a single reference into the dataKey propery.

One way to get both the date and the time into the chart is to create a timestamp like this:

```js
const chartdata = [
    {
        name: 'Oct 23rd 01:00',
        'Population growth rate': 1.74,
    },
    {
        name: 'Oct 23rd 02:00',
        'Population growth rate': 1.93,
    },
    {
        name: 'Oct 23rd 03:00',
        'Population growth rate': 1.9,
    },
    {
        name: 'Oct 23rd 04:00',
        'Population growth rate': 1.98,
    },
//...
```

Which results in  a chart like this:
<img width="1047" alt="CleanShot 2022-10-23 at 15 45 47@2x" src="https://user-images.githubusercontent.com/41927988/197395821-425934bc-9dd6-43ae-bd98-7d85b3e46b35.png">

**Comment by j2is** [comment]
Hey, nice thank you
