### ISSUE TITLE
heroicons version 2

### ISSUE THREAD

**Issue by Mrahmani71** [tremorlabs/tremor-npm#144]
About 2-3 months ago, it released the second version of **heroicons**, but you still use the icons of the first version on your site. I have listed the icons that need to be changed.

**[Documentation](https://github.com/tailwindlabs/heroicons)**

https://www.tremor.so/docs/components/dropdown
❌ import { CubeIcon, CubeTransparentIcon } from "@heroicons/react/solid";
✅ import { CubeIcon, CubeTransparentIcon  } from "@heroicons/react/24/solid";

https://www.tremor.so/docs/components/icons
❌ import { MailIcon } from "@heroicons/react/solid";
✅ import { EnvelopeIcon  } from "@heroicons/react/24/solid";

❌ import { HandIcon } from "@heroicons/react/outline";
✅ import { HandRaisedIcon  } from "@heroicons/react/24/outline";

❌ import { CashIcon } from "@heroicons/react/outline";
✅ import { BanknotesIcon  } from "@heroicons/react/24/outline";

https://www.tremor.so/docs/components/select
❌ import { CalculatorIcon } from "@heroicons/react/outline";
✅ import { CalculatorIcon  } from "@heroicons/react/24/outline";

https://www.tremor.so/docs/components/table
❌ import { StatusOnlineIcon } from "@heroicons/react/outline";
✅ import { SignalIcon  } from "@heroicons/react/24/outline";

https://www.tremor.so/docs/components/toggles
❌ import { CheckIcon, CollectionIcon, ReceiptRefundIcon } from "@heroicons/react/outline";
✅ import { CheckIcon, RectangleStackIcon, ReceiptRefundIcon   } from "@heroicons/react/24/outline";

https://www.tremor.so/docs/layout/block
❌ import { SwitchHorizontalIcon } from '@heroicons/react/solid';
✅ import { ArrowsRightLeftIcon   } from "@heroicons/react/24/solid";

https://www.tremor.so/blocks/landing-zone
❌ import {  CogIcon,  ShieldExclamationIcon,  CheckCircleIcon,  ArrowNarrowRightIcon,} from '@heroicons/react/solid';
✅ import {  CogIcon,  ShieldExclamationIcon,  CheckCircleIcon,  ArrowLongRightIcon,} from '@heroicons/react/24/solid';

❌ import {  ShoppingBagIcon,  CashIcon,  UsersIcon,  ShoppingCartIcon,  ArrowNarrowRightIcon,} from '@heroicons/react/solid';
✅ import {  ShoppingBagIcon,  BanknotesIcon,  UsersIcon,  ShoppingCartIcon,  ArrowLongRightIcon} from '@heroicons/react/24/solid';

❌ import { ArrowNarrowRightIcon } from '@heroicons/react/solid';
✅ import { ArrowLongRightIcon } from '@heroicons/react/24/solid';

❌ import { ArrowCircleRightIcon,  ArrowCircleUpIcon,  ArrowCircleDownIcon,  ArrowNarrowRightIcon } from '@heroicons/react/solid';
✅ import { ArrowRightCircleIcon,  ArrowUpCircleIcon,  ArrowDownCircleIcon,  ArrowLongRightIcon } from '@heroicons/react/24/solid';

❌ import { CashIcon, ChatAlt2Icon, SupportIcon, UsersIcon, InformationCircleIcon, ArrowNarrowRightIcon } from '@heroicons/react/solid';
✅ import { BanknotesIcon, ChatBubbleLeftRightIcon, LifebuoyIcon, UsersIcon, InformationCircleIcon, ArrowLongRightIcon } from '@heroicons/react/24/solid';

https://www.tremor.so/blocks/charts
❌ import { CheckCircleIcon } from '@heroicons/react/solid';
✅ import { CheckCircleIcon } from '@heroicons/react/24/solid';

https://www.tremor.so/blocks/kpi-cards
❌ import { CashIcon, TicketIcon, UserGroupIcon } from '@heroicons/react/solid';
✅ import { BanknotesIcon, TicketIcon, UserGroupIcon } from '@heroicons/react/24/solid';

❌ import { TrendingUpIcon, TrendingDownIcon, ArrowNarrowRightIcon } from '@heroicons/react/solid';
✅ import { ArrowTrendingUpIcon, ArrowTrendingDownIcon, ArrowLongRightIcon } from '@heroicons/react/24/solid';

❌ import { ArrowCircleDownIcon, CogIcon, MinusCircleIcon, CheckCircleIcon } from '@heroicons/react/solid';
✅ import { ArrowDownCircleIcon, CogIcon, MinusCircleIcon, CheckCircleIcon } from '@heroicons/react/24/solid';

❌ import { BriefcaseIcon, DesktopComputerIcon, ShieldExclamationIcon, ShoppingBagIcon, ArrowNarrowRightIcon, LightningBoltIcon, HomeIcon, TruckIcon } from '@heroicons/react/solid';
✅ import { BriefcaseIcon, ComputerDesktopIcon, ShieldExclamationIcon, ShoppingBagIcon, ArrowLongRightIcon, BoltIcon, HomeIcon, TruckIcon } from '@heroicons/react/24/solid';

**Comment by severinlandolt** [comment]
Heya @Mrahmani71 thank you for taking the time to write this together. We currently, use the old version on purpose because in the 2.0 version they do not have all the icons from **1.0.6** e.g. the clipboard icons. We will update to 2.0 as soon as the 2.0 version includes all old icons. :)
