### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by alexheiner** [tremorlabs/tremor-npm#145]
I think it would be useful to have a search bar component to filter rows of a table/list or other data. I've seen your examples of using a MultiSelectbox box for filtering, but I think the search functionality would be helpful too.

**Comment by mitrotasios** [comment]
Hey @alexheiner, thanks for the comment! Did you have the chance to check out the `SelectBox` component already, which essentially provides a search-box to filter among the available options? Or are you looking for something different? Feel free to elaborate 🙂

**Comment by alexheiner** [comment]
I actually didn't notice the ability to search in the SelectBox, thanks for pointing that out. Sorry I don't know how I missed that. I was originally thinking of a more general purpose table/data search, such as searching for a specific address, phone number, etc in a table. But I thInk the SelectBox could probably be used to do something similar.

**Comment by christopherkindl** [comment]
@alexheiner Let us know if a simple search bar (including further features, such as auto complete) still would be more appealing to your use cases! :)

**Comment by alexheiner** [comment]
Sounds good! I do think it could be a useful feature, but it could be something that is added down the line in a future release. Thanks for getting back to me about it! I think this is a really cool project, I'm excited to keep using it!

**Comment by tonyxiao** [comment]
SearchBox does no appear to be documented in the list of components here through. https://www.tremor.so/docs/components
