### ISSUE TITLE
Clarification on steps to get started

### ISSUE THREAD

**Issue by hiadamk** [tremorlabs/tremor-npm#157]
Hey! I love the project and what you've built so far ⚡ 

I noticed that the guide for getting started in the [README](https://github.com/tremorlabs/tremor#getting-started) defines getting started using create-react-app whereas the installation guide on the [website](https://www.tremor.so/docs/getting-started/installation) describes that the way to get started is by using Next.js! Just wanted to bring this to your attention; not sure if you intend to have instructions for both or just the shinier next.js :)

Again, great work! 🚀

**Comment by christopherkindl** [comment]
Hey @adamkona, many thanks for the kind words and raising this issue! We will update the README as stated on the website.

You can use tremor either within a React or Next project. For new React projects, we recommend using Next.js, as it also provides a simple deployment workflow through the Vercel platform. On the website, it also states that you have the React option. But we will highlight this better.

If you have any other feedback, feel free to share with us! :)

Best, Chris

**Comment by mitrotasios** [comment]
hey Adam, thanks a lot for the feedback, fixing the docs was long overdue 😅 We fixed it now in the README as well as on our website, I hope its clearer now. See you on Monday 😜

**Comment by hiadamk** [comment]
Closing as it was addressed in #158 :)
