### ISSUE TITLE
High severity vulnerabilities found in npm audit

### ISSUE THREAD

**Issue by hiadamk** [tremorlabs/tremor-npm#159]
Hey, when installing tremor at the moment, npm reports high severity vulnerabilities within the package.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/20659452/198739234-7e6eb841-4e16-4351-8327-055466351a3d.png">

<img width="569" alt="image" src="https://user-images.githubusercontent.com/20659452/198739254-42dce519-de65-4379-8ded-7e04e1c56e3f.png">

**Comment by mitrotasios** [comment]
hi @adamkona, thanks for the comment! This is an [ongoing issue](https://github.com/recharts/recharts/issues/3012) in Recharts (the chart library we are using under the hood). I hope it gets resolved soon!

**Comment by bloomfieldj** [comment]
It seems as though there's been some recent movement:  https://github.com/recharts/recharts/pull/3120

**Comment by pedroresende** [comment]
any news about this ?

**Comment by mitrotasios** [comment]
@pedroresende seems like the [PR](https://github.com/recharts/recharts/pull/3120) in the recharts repo is still open, we hope it gets merged soon. @bloomfieldj, thanks for mentioning this!

**Comment by pedroresende** [comment]
Thanks @mitrotasios

**Comment by stritt** [comment]
Just a heads up – it looks like the PR was [merged](https://github.com/recharts/recharts/pull/3167)!

**Comment by mitrotasios** [comment]
thanks @stritt - will adjust asap!

**Comment by mitrotasios** [comment]
Should be fixed with release `v1.6.0`

**Comment by hiadamk** [comment]
Can confirm it's fixed. Great work! 🚀


![Screenshot 2023-01-18 at 21 51 56](https://user-images.githubusercontent.com/20659452/213303094-d4833c32-01cf-4473-a9db-0930a439123b.jpg)

**Comment by mitrotasios** [comment]
awesome thanks 🥳
