### ISSUE TITLE
Card component decorationColor prop

### ISSUE THREAD

**Issue by asheikho99** [tremorlabs/tremor-npm#161]
Using Tremor with Typescript I was able to spot a misspelled prop in documentation.

Navigate to `Card` component then, `anatomy` section in tremor documentation. Card prop `decorationColor` is misspelled as `decrationColor`
![image](https://user-images.githubusercontent.com/105573050/198897896-a0c86c71-dcd6-463e-8406-6b7662b6bb9e.png)

Card props interface
![image](https://user-images.githubusercontent.com/105573050/198897995-3308ed8e-dce8-4ffa-8501-79ac72c19ca8.png)

Hope this helped.

**Comment by severinlandolt** [comment]
Hey @asheikho99, thank you much for pointing this out, we just fixed it. Thanks!✨
