### ISSUE TITLE
Feature request - Custom legend label

### ISSUE THREAD

**Issue by MatteoGauthier** [tremorlabs/tremor-npm#171]
Hey ! I really like the clean design and the DX of your project, I was using `AreaChart` and I wanted to display a different legend for my incoming data keys. I think it would be useful to be able to format the legend (the visible texts). In particular, because the category names can be in some cases dynamic, keys name can conflict.

Idea : Add a `legendFormatter` prop

Thank you for this project, bye

**Comment by severinlandolt** [comment]
Hi @MatteoGauthier thank you for your feedback! I do not exactly understand the use case behind your proposition. Can you provide some screenshots or an example in pseudocode of what you actually need? Otherwise, I am happy to jump on a call to discuss this issue further, just let me know :)
