### ISSUE TITLE
updating selected item of SelectBox

### ISSUE THREAD

**Issue by jmichelx2** [tremorlabs/tremor-npm#181]
Hi,

I am trying to populate the items of a SelectBox via a state variable which is set according to a selected ToggleItem.
While the items of the SelectBox are updating correctly, the selected item text does not change.

Please see example [here](https://codesandbox.io/s/laughing-kepler-gf9pbv).

Same happens with a MultiSelectBox, the number of selected items text does not change.

Is there something an issue with my code or is this not possible? Thanks.

**Comment by eykrehbein** [comment]
Hi @jmichelx2, you could add a `key` prop to the `<SelectBox>` element, which binds `intervals`. This causes the SelectBox element to be re-rendered each time the `intervals` state changes. 

So the change would be:
```tsx
<SelectBox
    key={intervals}
    defaultValue={selected}
    ...
```

Demo: https://codesandbox.io/s/relaxed-brattain-prt7yy?file=/src/App.js

**Comment by jmichelx2** [comment]
Thanks @eykrehbein.
