### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by cubecleveland** [tremorlabs/tremor-npm#184]
I saw u do not support dark mode but can i pass custom css tailwind classes to do so ?

**Comment by severinlandolt** [comment]
Hey @cubecleveland, you are correct, there is currently no dark mode available. At the moment, our components do not allow for a passthrough using a className. We take this feedback from you into our roadmap discussions.

Here's a related issue, if you want to be updated you can subscribe to issue #75

Best,
Sev
