### ISSUE TITLE
importing dat time picker only

### ISSUE THREAD

**Issue by cubecleveland** [tremorlabs/tremor-npm#185]
HI, can i import only the dat time picker to my library is that possible or do i have to import the whole thing, will my bundler tree shake the dependency ?

Many thanks!

**Comment by severinlandolt** [comment]
Hey @cubecleveland, thank you for reaching out. Currently, we do not export single components. If you want to use the datepicker, you'd have to install the whole `@tremor/react` library. Happy coding :)
