### ISSUE TITLE
Add your .prettierrc

### ISSUE THREAD

**Issue by eykrehbein** [tremorlabs/tremor-npm#186]
I think it might be useful to add your (maintainer's) prettier configuration to the root of the codebase so that all contributors would use the same code styles. Currently, VSCode automatically uses my default prettier configuration, which basically reformats the entire file.

Doing so has two advantages:
- The code style remains consistent 
- The differences between pull requests are easier to understand. Reformatting the entire file could lead to confusion about what has actually changed

**Comment by mitrotasios** [comment]
Yes that sounds good! We will implement this as soon as possile.
