### ISSUE TITLE
Steps to build the library

### ISSUE THREAD

**Issue by eykrehbein** [tremorlabs/tremor-npm#187]
I'm trying to build the library to test some changes I thought of making, however I just couldn't figure out how to build the library.

Actions I tried:
- `yarn rollup` -> resolves in the error `[!] Error: Could not resolve entry module (dist/esm/types/index.d.ts).` 
- `yarn build-storybook` -> resolves in either React not being found, since it's just a peerDependency or the error `Error: PostCSS plugin tailwindcss requires PostCSS 8`, when I manually installed React as regular dependency.

Am I missing something important, in order to be able to build the library locally?

Node: v16.13.1
Yarn: v1.22.17

**Comment by mitrotasios** [comment]
hi @eykrehbein, have you tried using npm?

Build: `npm run rollup`
Run Storybook: `npm run storybook`

Please let me know if that works. We will document these steps somewhere in the future.

**Comment by eykrehbein** [comment]
Works with npm! 👍
