### ISSUE TITLE
Could BarList support multiple value columns?

### ISSUE THREAD

**Issue by sdairs** [tremorlabs/tremor-npm#191]
Hey folks!

We built an open source Google Analytics alternative at Tinybird https://www.tinybird.co/starter-kits/web-analytics 

Which uses some custom components & Apache eCharts for the charts. We've been exploring using Tremor instead.

We have a BarList style chart that has multiple value columns for e.g. Sessions | Hits.

[ Bar ------ ][Value][Value]
[ Bar ------ ][Value][Value]
<img width="317" alt="image" src="https://user-images.githubusercontent.com/8709801/202193334-3a6bff41-d74d-4a94-968d-2f804baa8c65.png">

The length of the Bar is based on the first value; the additional columns have no bearing on the bar itself, but are there for additional info/context.

Could the BarList component support this?

My initial ideas from a naive first glance...

The current data model for BarList looks like
```
const data = [
    { name: 'Twitter', value: 456, icon: TwitterFillIcon },
    { name: 'Google', value: 351, icon: GoogleFillIcon},
    { name: 'GitHub', value: 271, icon: GithubFillIcon },
    { name: 'Reddit', value: 191, icon: RedditFillIcon },
    { name: 'Youtube', value: 91, icon: YoutubeFillIcon },
];
```

Perhaps if the value was an Array, it could create multiple value columns?
```
const data = [
    { name: 'Twitter', value: [456,123], icon: TwitterFillIcon },
    { name: 'Google', value: [456,123], icon: GoogleFillIcon},
...
];
```
Or perhaps multiple values could be supported by using `values` instead of `value` so that the expected type of `value` didn't change?
```
const data = [
    { name: 'Twitter', values: [456,123], icon: TwitterFillIcon },
    { name: 'Google', values: [456,123], icon: GoogleFillIcon},
...
];
```

cc @dmytro-tinybird

**Comment by mitrotasios** [comment]
Hey @sdairs, thanks a lot for the comment! I think that makes sense.  This would be a breaking change however, so I would see this being potentially implemented within our v2 release which is planned for Q1/23 :)

**Comment by christopherkindl** [comment]
Hi @sdairs,

many thanks for these ideas with concrete suggestions 🙏  We strongly try to follow an atomic composability approach in which each component should serve for various use cases. Saying this, we are not 100% happy with the current structure of <BarList> as it very opinionated and might be only appealing to a specific use case. In an ideal scenario, the left bar chart and right metric "column" would represent own components you can stitch together to achieve the current visualization and also your 2-column visualization.

Nevertheless, your architecture suggestion is very interesting, and we will definitely consider this for the next iteration. However, it would come at the cost of new edge cases: if you allow multiple columns, users would *expect* that it will work fine for 3+ columns as well. In this case, it would be very hard to achieve a good looking visualization. However, if you offer them more atomic components with which they can build a 3-column styled BarList, they are *responsible* if it does not look good.

Hope that makes sense to you and feel free to challenge! 

Thanks for your valuable input again. We would be very interested in a closer collaboration between tinybird and tremor :)

Best, Chris

**Comment by sdairs** [comment]
Thanks @christopherkindl totally understand your approach, I'm not a front-end guy so I don't have a strong/good opinion on how its achieved, so appreciate your input :D We'll build this out using the BarList & then add the additional value columns ourselves for now, but will keep an eye out to see if you add a native solution OOTB

Cheers!

**Comment by severinlandolt** [comment]
We actually considered this but ultimately decided not to proceed. This decision was primarily due to layout issues that need to be managed internally but could be altered by the user. Maintaining this balance would have required us to introduce slots for class names, which we generally do not have and do not wish to add. 
**However:** We recently launched Tremor Raw, a copy & paste library for React componets. Here we have a [new version of the Barlist](https://raw.tremor.so/docs/visualizations/barlist), where you have full control over this.

**Comment by severinlandolt** [comment]
Thanks for the submission!
