### ISSUE TITLE
Custom BarList color opacity

### ISSUE THREAD

**Issue by angelhodar** [tremorlabs/tremor-npm#192]
I have noticed that some colors are a little hard to see because if I set it to `purple` the final result is `bg-purple-100` because its taking the `lightBackground` from the config, and in my case the best option would be `bg-purple-300`. This is something that could be solved with #80 but I know its not that easy to allow full customization at the moment, so maybe a new `opacity` prop could do the trick?

**Comment by severinlandolt** [comment]
Hey @angelhodar, thank you for your detailed feedback and for coming up with a potential solution. We will discuss the opacity idea internally. Thanks!

**Comment by severinlandolt** [comment]
Adding an opacity prop will make the component's API rather weird. We changed the styling of the BarList all together, will be released in v3.9.

c.f. #612
