### ISSUE TITLE
Stacked & Percentage based area charts

### ISSUE THREAD

**Issue by bernsno** [tremorlabs/tremor-npm#193]
Hi, Really enjoying using tremor, wondering if there's interest in having options for [stacked](https://recharts.org/en-US/examples/StackedAreaChart) or [percent](https://recharts.org/en-US/examples/PercentAreaChart) area charts? Can open a PR with an implementation if other folks would get value out of having those options.

**Comment by severinlandolt** [comment]
Hey @bernsno, 
First of all, thank you for using tremor and engaging here on GitHub! Having the option to make a chart stacked/percent makes sense and thank you for your PR #194. 

We are currently working on our next minor release. After that, we wanted to give our charts some polishing, so this feedback comes at the right time. Thank you and happy coding ✨

**Comment by bernsno** [comment]
Thanks for the response @severinlandolt. As I was digging into the code and using the library, another approach that I thought could be useful is to provide the primitives to allow people to more easily use recharts more complex features, but keep things looking like the rest of their dashboard. In order to do this I think you'd need to expose and API for the theme and wrapper components for charts.
