### ISSUE TITLE
Feature request - Pie chart

### ISSUE THREAD

**Issue by dmytro-tinybird** [tremorlabs/tremor-npm#198]
Currently, there's only a donut chart which is very close to the pie chart, however, it would be nice to have the ability to add either of those depending on the situation in which it will be used.

**Comment by rauchg** [comment]
+1. I'll die on the hill that pie charts are awesome 😆

**Comment by mitrotasios** [comment]
@rauchg we certainly don't want you to die on any hill for this, so we will include this feature in this week's release as well 😄
