### ISSUE TITLE
Feature request - Calendar from DatePicker as it's own component

### ISSUE THREAD

**Issue by 3ddyBoi** [tremorlabs/tremor-npm#200]
# Context
A nice component to have would be a "Calendar DatePicker". 

## Description
The component would be the modal for the DatePicker Select Date.

## Example image
I have a design that uses this fictional component, here is the how it could be used.
<img width="247" alt="image" src="https://user-images.githubusercontent.com/70267476/203777736-d685828b-a8e0-4a1e-aa81-4d5acbb57c5a.png">

## Is this something that is wanted?

**Comment by severinlandolt** [comment]
Heya @3ddyBoi thanks for your detailed request. This makes sense–we will discuss this in our next planning session. Happy coding :)

**Comment by mitrotasios** [comment]
hey @3ddyBoi, thanks for the suggestion, I think we don't have the resources to implement this for now :/
