### ISSUE TITLE
tremor.so is blacklisted by MetaMask

### ISSUE THREAD

**Issue by MatteoGauthier** [tremorlabs/tremor-npm#201]
https://metamask.github.io/phishing-warning/v1.2.1/#hostname=www.tremor.so&href=https%3A%2F%2Fwww.tremor.so%2Fblocks&newIssueUrl=https%3A%2F%2Fgithub.com%2Fmetamask%2Feth-phishing-detect%2Fissues%2Fnew

**Comment by severinlandolt** [comment]
@MatteoGauthier Thank you for reaching out. We [already created an issue](https://github.com/MetaMask/eth-phishing-detect/issues/9643) over at metamask but it has not been resolved yet -.-

**Comment by mitrotasios** [comment]
Fixed by https://github.com/MetaMask/eth-phishing-detect/pull/9669
