### ISSUE TITLE
Unable to wrap `DropdownItem` inside another component

### ISSUE THREAD

**Issue by joakimbeng** [tremorlabs/tremor-npm#202]
Hi and thanks for a great library! A lot of good looking and useful components in here!

In my use case I want to render a dropdown with the items coming being rendered inside another component but currently that's not possible. The `Dropdown` component crashes when clicked in such case.

Take a look at this code sandbox: https://codesandbox.io/s/angry-grass-mjjy51?file=/src/App.js where I have recreated a similar scenario.

I expected the `Dropdown` and `DropdownItem` components to use contexts to communicate with each other, but apparently that's not the case. Because if so this wouldn't be a problem I guess.

Is that something you think will be addressed? I really think it would be useful and it would also make it easier to solve the current accessibility issue with it, namely that you can't navigate the dropdown list using the keyboard as in a native dropdown.

**Comment by mitrotasios** [comment]
hi @joakimbeng, thanks for the comment, that's a valid point. We also figured that contexts are probably more suited in this case. We'll refactor our select elements as soon as we have time. Also feel free to submit a PR if you like! :)
