### ISSUE TITLE
Feature request: Support dark mode / background colours other than white

### ISSUE THREAD

**Issue by john-tipper** [tremorlabs/tremor-npm#208]
I'd like to use the components with a page that supports dark mode. Currently, there doesn't appear to be a way to set the colours of components to support Tailwind's [dark mode](https://tailwindcss.com/docs/dark-mode). Please could you consider allowing some sort of injection of colours into the components such that non-white backgrounds and other border colours are supported?

**Comment by mitrotasios** [comment]
hi @john-tipper, natively supporting a dark mode is currently not a priority for us unfortunately. However, we will allow to pass intrinsic HTML/React element attributes such as `className` to our components soon.

**Comment by minyan-gu** [comment]
perhaps support `style` attribute as well for convenience.

**Comment by OskarEichler** [comment]
Yes this is a deal breaker for us as our UI is dark. Allowing custom styling or a pre-configured dark mode would be great!

**Comment by samiy803** [comment]
+1

**Comment by ehowey** [comment]
+1 too!

**Comment by ethndotsh** [comment]
+1

**Comment by mitrotasios** [comment]
hey everyone, custom colouring or theming is the next big thing on our roadmap. We don't have a timeline on this yet as there are certain challenges regarding customisation given our tailwind dependency.

**Comment by JPBotelho** [comment]
+1

**Comment by oklex** [comment]
+1

**Comment by rockse** [comment]
Would love to hear if there is any update on this

**Comment by severinlandolt** [comment]
Dark mode has been released, read the documentation on theming here: https://www.tremor.so/docs/getting-started/theming
