### ISSUE TITLE
Feature Request - Loading state for `<Button>`

### ISSUE THREAD

**Issue by rauchg** [tremorlabs/tremor-npm#209]
Ideally with support for a spinner, with a width transition if the button doesn't have an icon set

**Comment by wa1aric** [comment]
@rauchg maybe start with animate-pulse?

**Comment by mitrotasios** [comment]
hey @rauchg, thanks for the suggestion! We are releasing a new minor version this week and included this feature as well now. We just released it on `@beta-1.2.0`, feel free to check it out :)

https://user-images.githubusercontent.com/58337217/204405763-a012560d-490e-417f-bd12-7682a07e535e.mov
