### ISSUE TITLE
Feature Request: Line Chart for Dates

### ISSUE THREAD

**Issue by nmandal** [tremorlabs/tremor-npm#210]
would like to be able to plot time changes using a line chart

**Comment by mitrotasios** [comment]
hey @nmandal. Does that mean you would like to filter for time ranges if I understand correctly? We are planning to add time ranges to our Datepicker as well in the near future.

**Comment by nmandal** [comment]
@mitrotasios Actually would like to plot dates on both the X and Y axis.

Meaning x axis would have dates (ie 11/27, 11/28, 11/29) and y axis would have say times (11:20 PM, 10:45 PM, 12:00 AM, etc.)

**Comment by jschuur** [comment]
Initially, I didn't realize that the current charts already dynamically use as many ticks as will fit if your `dataKey` is a parsable date string. This wasn't obvious from the docs, but once you try it out, this was apparent.

**Comment by erimfranci** [comment]
@jschuur what date format is accepted as parsable here?

**Comment by jschuur** [comment]
> @jschuur what date format is accepted as parsable here?

Anything string that can be parsed with [Date.parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse).
