### ISSUE TITLE
Integration with CubeJS

### ISSUE THREAD

**Issue by moltar** [tremorlabs/tremor-npm#220]
Would be great to have a good integration story for CubeJS.

**Comment by severinlandolt** [comment]
Hey @moltar, thank you for rising this idea. We have not worked with CubeJS yet, could you link some great implementations/docs/guides of what you consider a tool well integrated with Cubejs? Would help us a ton, thanks!

**Comment by moltar** [comment]
Here's the doc: https://cube.dev/docs/frontend-introduction

In essence, CubeJS is a "headless" BI framework. It provides a layer that creates metrics and allows to expose them in various ways. It is up to the user then to create the UI. There's even a bit of codegen tool that is built into the UI.

I think this is a great fit for Tremor because of that, as it is a "Dashboard" framework explicitly.

I am not yet a big CubeJS user, so I can't help much at this point. We are considering switching from a BI solution to a custom CubeJS-based solution, but haven't made that decision yet.

**Comment by moltar** [comment]
Hey, @mitrotasios!

Do you have docs for this implementation? Thanks!

**Comment by mitrotasios** [comment]
hey, sorry for closing this, but I am afraid we don't have the capacity to provide such an integration/template yet.

If you're interested in seeing Tremor with a data connection I suggest checking out @tinybirdco's starter kits that are built with tremor.

https://github.com/tinybirdco/log-analytics-starter-kit
https://github.com/tinybirdco/web-analytics-starter-kit
