### ISSUE TITLE
Feature request: Seperate styling for 'forecasted' data

### ISSUE THREAD

**Issue by jschuur** [tremorlabs/tremor-npm#221]
(following up from the [discussion on Twitter](https://twitter.com/joostschuur/status/1598260938549137408))

Use case: Sometimes in a chart, you want to make it apparent that the last few data points aren't final yet. You might be showing recent daily data and the current day isn't over yet. In this case, you want to avoid creating the false impression of a dip for a measure metric compared to previous days.

Apexcharts calls this [forecast data points](https://apexcharts.com/docs/options/forecastdatapoints/).

In a line chart, this could be done by having the last (few) data point(s) be a dashed line.

For bar charts, this is less of an issue if you already support controlling the color of each bar, although some kind of standard support across both types would be good.

**Comment by mitrotasios** [comment]
hi @jschuur, thanks a lot for the detailed feedback on twitter. This is a valid point as its used in web analytics use cases as well. We will need to consider how to implement this with recharts.

**Comment by mitrotasios** [comment]
hey @jschuur, thanks for the suggestion. I think we will not add this for now, but will keep this in mind!
