### ISSUE TITLE
Bug: BarList uses name as the key, preferably use another key property (if exists)

### ISSUE THREAD

**Issue by amruthpillai** [tremorlabs/tremor-npm#222]
So, my use case was such that I needed to display a react component inside the BarList, as shown in the screenshot below, but to be able to do that, I had to make the `name` property an empty string. Little did I know, the `name` prop was being used as the key, so it's sort of mandatory.

![Screenshot 2022-12-01 at 4 08 34 PM](https://user-images.githubusercontent.com/1134738/205087895-fbb59dbb-49ad-4740-a419-d4b98f22c029.png)

Would it be possible to introduce a `key` property when passing data, and if not passed, fallback to `name` (so it can be backwards compatible)?

**Comment by mitrotasios** [comment]
hey @AmruthPillai thanks for spotting this, I think it makes sense to add this.
