### ISSUE TITLE
Feature Request: Add a SmartTable component that works as the Charts do

### ISSUE THREAD

**Issue by jorgeorejas** [tremorlabs/tremor-npm#227]
I created a new component, called SmartTables, that works the same way charts do.

It has a data, a categories and a valueFormatter input.

Here you have [my Fork ](https://github.com/jorgeorejas/tremor/) and [the PR](https://github.com/tremorlabs/tremor/pull/226)

**Comment by mitrotasios** [comment]
hey @jorgeorejas, thanks so much for the PR! We need a bit more time to consider this approach, I hope you understand 🙂

**Comment by jorgeorejas** [comment]
> hey @jorgeorejas, thanks so much for the PR! We need a bit more time to consider this approach, I hope you understand 🙂

Sure I understand, you are making a great tool and I'm happy to help on whatever you may need! 

Keep going! 🚀
