### ISSUE TITLE
React Native Support

### ISSUE THREAD

**Issue by OskarEichler** [tremorlabs/tremor-npm#230]
Would be amazing to make this library compatible with React Native as well!

**Comment by mitrotasios** [comment]
hey @OskarEichler, thanks for the comment. React native is currently not on our roadmap unfortunately :( We would be open to potentially cooperate with another contributor who is willing to implement it if it is of great interest though. Same goes for other JS frameworks.

**Comment by andrewpriceau** [comment]
Would love this as well - was just searching for this. Disappointed.. there is no support - thoughts on closest alternatives ?
