### ISSUE TITLE
Feature request - dataKey and categories inference

### ISSUE THREAD

**Issue by dmytro-tinybird** [tremorlabs/tremor-npm#238]
Right now, the **data** has an `any[]` type, **dataKey** has a `string` type, and **categories** `string[]` type. And if the values passed to the accessor props aren't keys of data then the chart simply won't render without throwing an error. So, it would be nice to have those accessors be actual keys of the type of data type and see errors if they aren't.

**Comment by mitrotasios** [comment]
hey @dmytro-tinybird, thanks a lot for the PR! Will have a look as soon as I have a bit more time :)
