### ISSUE TITLE
Reset date in Datepicker

### ISSUE THREAD

**Issue by angelhodar** [tremorlabs/tremor-npm#241]
Hey, issues king is back again! :)

I have tried to make a button to reset the dates to the default ones provided as `defaultStartDate` and `defaultEndDate` but the UI doesnt update. I think that just using a `useEffect` with those values as deps would solve the issue

**Comment by mitrotasios** [comment]
hey Angel, thanks for the comment! I am not sure I totally understand the question, have you tried setting `defaultStartDate` and `defaultEndDate` to `undefined` in order to reset the selection?

**Comment by angelhodar** [comment]
@mitrotasios Resetting to undefined doesnt update the UI either. Here you have a codesandbox: https://codesandbox.io/s/adoring-thunder-owrnsj?file=/src/App.js

You can see that when you change the dates and you click Reset, the values change but they dont get reflected in the UI

**Comment by mitrotasios** [comment]
@angelhodar thanks for clarifying, this is because our input components are currently uncontrolled. We are currently working on adding the ability for our input components to be controlled, i.e. to control the state from the parent. In the meantime you can implement a work around: try setting `key={ JSON.stringify(startDate) }`. Let me know if that works :)

**Comment by vedovelli** [comment]
> key={ JSON.stringify(startDate) }



> @angelhodar thanks for clarifying, this is because our input components are currently uncontrolled. We are currently working on adding the ability for our input components to be controlled, i.e. to control the state from the parent. In the meantime you can implement a work around: try setting `key={ JSON.stringify(startDate) }`. Let me know if that works :)

Thanks a lot for this tip. It solved my issue big time!
