### ISSUE TITLE
Too much margin on Tab icon

### ISSUE THREAD

**Issue by ethndotsh** [tremorlabs/tremor-npm#245]
This is mostly just an opinion, but the amount of margin on the right side of the icon on the Tab component is too much - you can see in this picture:
![image](https://user-images.githubusercontent.com/58047023/207907756-db8a553e-0191-4c43-bdd0-cdf4794739fe.jpeg)

When the tab isn't selected, it almost seems like two tabs. One just and icon, and one with just text.

I think that the margin should be more like the toggles:
![image](https://user-images.githubusercontent.com/58047023/207907827-fe3b5482-ddd5-42f3-87f2-f4762720c40d.jpeg)

I would be happy to open a PR for this if you agree.

**Comment by severinlandolt** [comment]
@cursecodes Thanks for checking every pixel :) We agree and will add this to our next release.
