### ISSUE TITLE
Issue in changing color in DonutChart pie variant 

### ISSUE THREAD

**Issue by Antino17** [tremorlabs/tremor-npm#248]
i am using in props in colors={["indigo", "black", "red", "white", "pink", "amber"]} in this DonutChart pie variant  component  but they are not accept all color like white black and some other and also not able to use  hexacode  in this color  props. so if any one  know how to over write this thing???

**Comment by severinlandolt** [comment]
Hey @Antino17, thank you for reaching out. Currently, you can only pass [predefined colors from our color palette](https://www.tremor.so/docs/layout/color-palette). On that note, passing arbitrary hex values is also not possible. This might change in the future, but it's not a priority for us.
