### ISSUE TITLE
Labels for inputs

### ISSUE THREAD

**Issue by ethndotsh** [tremorlabs/tremor-npm#250]
These new inputs are great! Really love them. One thing that I saw was missing was labels.

I would be more than happy to open a PR if you agree.

**Comment by christopherkindl** [comment]
Hi @cursecodes, thanks for using our library and your kind words!

We exclude them by purpose as we try to follow a very atomic approach of how components can be stitched together. In your case, you could do the following:

```tsx
<Text> Full name </Text>
<TextInput ... marginTop="mt-2" />
```

Hope this is what you meant with labels and happy to hear your thoughts! :)
