### ISSUE TITLE
`TextInput` does not allow setting an `id` making the `label` `for` property useless

### ISSUE THREAD

**Issue by rodrigoehlers** [tremorlabs/tremor-npm#252]
Sadly the newly released `TextInput` seems not to support setting an `id` property. A `label` tag used with the `for` property does therefore not work with it.

This would need to be added [here](https://github.com/tremorlabs/tremor/blob/d6a9402593bf056f566b4edd57723a75c10377be/src/components/input-elements/TextInput/TextInput.tsx#L33).

I'm happy to provide a PR which adds this. However, I would like to know whether this decision was on purpose. The ?`TextInputProps` could for example extend the `React.HTMLAttributes<HTMLInputElement>` if that makes sense. This would also make it possible to remove the `name`, `value` and `onChange` (and other) props from the actual definition.

Does this make sense?

**Comment by mitrotasios** [comment]
hey @rodrigoehlers, thanks for raising this! The truth is, we would like to extend **all** of our components to inherit default HTML attributes such as `id`, `className` etc (input elements would then extend `React.HTMLAttributes<HTMLInputElement>`). There are a couple of reasons why we chose not to do this from the start. However, we are currently drafting our new design to accommodate this and aim to implement it in the beginning of the new year.

Anyway, regarding the `id` field, it definitely makes sense and we simply forgot to add it when releasing the new version, so feel free to open a PR for that if you, like 🙂
