### ISSUE TITLE
`autoMinValue` is `false` by default, but in docs says it's `true`

### ISSUE THREAD

**Issue by primenumsdev** [tremorlabs/tremor-npm#255]
For example here: https://github.com/tremorlabs/tremor/blob/main/src/components/chart-elements/AreaChart/AreaChart.tsx#L53

And docs:
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/82666953/209385363-c3562bc2-8357-4fd3-8e4b-8134ae882b8e.png">

Thanks, it's great library!
Not sure what is intended to be default behaviour, hence I didn't create PR.

**Comment by christopherkindl** [comment]
Thanks for this, @primenumsdev! And also thanks for using our library and your feedback. Just fixed it!
