### ISSUE TITLE
Choice to remove bottom border from tabs

### ISSUE THREAD

**Issue by ethndotsh** [tremorlabs/tremor-npm#262]
I love the tabs - but this is something that I need to make them even better. This should be an incredibly easy fix, as well.

**Comment by mitrotasios** [comment]
Hey @cursecodes, would you like to remove the light border or the "bold" one below each individual tab?

**Comment by ethndotsh** [comment]
The light gray border that stays the same no matter which tab you have selected. The reason for this is that I have a border that spans the entire page - but the tabs do not, so it results in a weird 'double border' in the middle.

**Comment by mitrotasios** [comment]
Yeah that makes Sensen! We will migrate our CSS to emotion soon and will then allow for custom styles, so it would then be possible to remove the border :)

**Comment by ethndotsh** [comment]
Is there an ETA on this? Willing to open a PR for just this component if it's a ways out.

**Comment by mitrotasios** [comment]
hey @cursecodes, we didn't end up going with emotion in the end due to the runtime cost. We'll release our v2 in the next couple of days, where you'll be able to override the border through the `className` prop, using regular tailwind classes 🙂

**Comment by ethndotsh** [comment]
> hey @cursecodes, we didn't end up going with emotion in the end due to the runtime cost. We'll release our v2 in the next couple of days, where you'll be able to override the border through the `className` prop, using regular tailwind classes 🙂 

Awesome!
