### ISSUE TITLE
Feature request: Responsive Tabs

### ISSUE THREAD

**Issue by MubashirullahD** [tremorlabs/tremor-npm#263]
![image](https://user-images.githubusercontent.com/45071858/210045853-cd9feeca-1d42-49c8-a574-dc81ac4407cb.png)

![image](https://user-images.githubusercontent.com/45071858/210046141-71970aad-2dde-4ac4-a6e7-4c306ba9e515.png)

These tabs will hide if the screen size gets smaller and there is no way of clicking on them. My designer says I should either make it scrollable or change it to ellipses that onclick becomes a dropdown.

Requesting default scrollability, thank you.

```
      <TabList defaultValue={1} handleSelect={(value) => setSelectedView(value)} marginTop="mt-6">
        <Tab value={1} text="Menu Breakdown" />
        <Tab value={2} text="Product Mix" />
        <Tab value={3} text="Top Items" />
        <Tab value={4} text="Top Groups" />
        <Tab value={5} text="Top Modifiers" />
        <Tab value={6} text="Top Voided" />
      </TabList>
```

**Comment by MubashirullahD** [comment]
![image](https://user-images.githubusercontent.com/45071858/210054870-2f5a3645-1a05-415f-b59f-0aa0a21d1698.png)

Currently, there is this tr overflow x clip that was set to clip. Setting it to auto is my desired behaviour. I cant change this by myself. I think I'll have to render a dropdown on small screen for tabs to continue my work.

**Comment by MubashirullahD** [comment]
Wrapping my TabList in a div with id tab works. 
```
#tab ol {
    overflow-x: auto;
    overflow-y: hidden;
}
```

![image](https://user-images.githubusercontent.com/45071858/210056227-278cd5f8-a9e3-469e-97fe-54e4b070eaef.png)

**Comment by christopherkindl** [comment]
Hi @MubashirullahD,

thanks for your feedback and also congrats to your UI. Looks really great! 

Yes, you pointed it out correctly: the tabs are usually used on large screen size and not mobile screen sizes. This is why we do not want to incorporate x-scroll or something similar. For smaller screen sizes, it is recommended to use a dropdown for better UX.

Hope this helps and happy to jump on a call if you have further feedback. We noticed that you are very active here, so we would love to hear more!

Cheers,
Chris

**Comment by MubashirullahD** [comment]
![image](https://user-images.githubusercontent.com/45071858/211601065-4b9452c2-4ce0-4610-b8b0-33e21fd2e1d0.png)

```jsx
      <div className="hidden sm:block">
        <TabList defaultValue={1} handleSelect={(value) => setSelectedView(value)} marginTop="mt-6">
          <Tab value={1} text="Menu Breakdown" />
          <Tab value={2} text="Product Mix" />
          <Tab value={3} text="Top Items" />
          <Tab value={4} text="Top Groups" />
          <Tab value={5} text="Top Modifiers" />
          <Tab value={6} text="Top Voided" />
        </TabList>
      </div>

      <div className="sm:hidden ">
        <Dropdown maxWidth="max-w-full" defaultValue={1} handleSelect={(value) => setSelectedView(value)} marginTop="mt-6">
          <DropdownItem value={1} text="Menu Breakdown" />
          <DropdownItem value={2} text="Product Mix" />
          <DropdownItem value={3} text="Top Items" />
          <DropdownItem value={4} text="Top Groups" />
          <DropdownItem value={5} text="Top Modifiers" />
          <DropdownItem value={6} text="Top Voided" />
        </Dropdown>
      </div>
```

This certainly is more cooler. Thank you so much for making Tremor. It has made it possible to make analytics for our product in a very short amount of time. I'd definitely would share more if there was a discord community for this tool. Right now my designer is like can we do this with the axis and I'm like no that's not possible and the matter is trivial enough to not be raised as an issue on GitHub.

It would be nice if tremor gave me a time picker so I wouldn't have to rely on Ant (which comes with its own styles and then I have to increase the specificity of some styles to prevent conflicts between: bootstrap; tailwind; our own custom styles and then tremor.) I can now see that tailwind truly is optional and I could style the responsiveness myself and still have tremor work for me which is great. Later down the line, I'll have to style my dashboards to become consistent with all the rest of the styles in our product so that might be a challenge.

Other than that (and the things I've brought up in other threads) I think tremor has sufficiently sufficed our needs here at Roomy.pk. Thank you so much.

**Comment by mitrotasios** [comment]
Thank you very much @MubashirullahD!
