### ISSUE TITLE
Feature improvement request: Date Range Picker i18n

### ISSUE THREAD

**Issue by benoitjoffre** [tremorlabs/tremor-npm#270]
Hi,

is there a possibility to change the language  on calendar ?  (example : US to FR).

if so, is this improvement under development? if not, I would like to offer you a PR, if you wish.

Regards,

**Comment by mitrotasios** [comment]
Hey @benoitjoffre, it's currently not possible unfortunately, so by all means, feel free to submit a PR if you like 🙌🏻
