### ISSUE TITLE
Request: Number Field

### ISSUE THREAD

**Issue by djadriano** [tremorlabs/tremor-npm#271]
Currently we have `Text input` field that only accept text and is not possible to pass a type as a `number` like in a native input HTML field.

Maybe create a generic input that contains only styling and accepts the native HTML input props.

Given the components are for analytics and dashboards, number is super important.

**Comment by mitrotasios** [comment]
hey @djadriano thanks for the suggestion, agree! We wanted to keep these two separate so we are intending to release a "NumberInput" component. I can't give any concrete timeline unfortunately as we are busy with working on our v2 release which will enable all of our components to accept native HTML input props as well. Hopefully we can release the `NumberInput` next month :)

**Comment by djadriano** [comment]
Hello @mitrotasios , oh thanks for reply. 
I'm looking forward for the next releases and I will try to help giving more ideas.

Good luck and congrats for the good job!

**Comment by mitrotasios** [comment]
Thanks a lot, suggestions are always welcome! 🤗
