### ISSUE TITLE
Broken Link in Components Docs

### ISSUE THREAD

**Issue by psikoi** [tremorlabs/tremor-npm#277]
https://www.tremor.so/components links to https://www.tremor.so/docs/components/buttons

it seems like it should link to https://www.tremor.so/docs/components/button instead

Note: I forked the repo thinking the docs were included in it, was looking to submit a PR for this myself, but I couldn't find those 🤔

**Comment by severinlandolt** [comment]
Thank you @psikoi, we just fixed it!
