### ISSUE TITLE
Typo in Charts Block Documentation

### ISSUE THREAD

**Issue by psikoi** [tremorlabs/tremor-npm#278]
https://www.tremor.so/blocks/charts 

There's a title there with the text `Card + Lin Chart + Tabs`

"Lin Chart" should be Line Chart

Note: I forked the repo thinking the docs were included in it, was looking to submit a PR for this myself, but I couldn't find those 🤔

**Comment by severinlandolt** [comment]
Thank you @psikoi for reaching out! You are correct, we will fix this asap!
