### ISSUE TITLE
fill-rule and clip-rule Warning

### ISSUE THREAD

**Issue by Mrahmani71** [tremorlabs/tremor-npm#285]
When using Tremor, the console displays these warnings:

```
Warning: Invalid DOM property 'fill-rule'. Did you mean 'fillRule'

Warning: Invalid DOM property 'clip-rule'. Did you mean 'clipRule'?
```

if it's possible, fix this issue. Thanks

![Capture d’écran 2023-01-22 124532](https://user-images.githubusercontent.com/13013819/213914076-8fc0445a-b5e7-4125-935a-37de18246ba7.png)

**Comment by mitrotasios** [comment]
Hey @Mrahmani71, thanks for submitting this, we will fix asap!
