### ISSUE TITLE
Feature request: expose className for layout components

### ISSUE THREAD

**Issue by sVerentsov** [tremorlabs/tremor-npm#287]
I am having a problem with customizing layout components (Flex, Block, ColGrid, Col) - sometimes I need to apply some style that is not intended by the library, e.g. change flex direction for Flex. And the only way to achieve that right now is just to replace the component with div with the required styles.

This could be improved by adding `className` prop to the layout components and appending the value of this prop to the inner div.

**Comment by christopherkindl** [comment]
Hi @sVerentsov,

thanks for using our library! We are currently working on customization and extending all components to expose native HTML/JSX attributes.

**Comment by mitrotasios** [comment]
@sVerentsov you can checkout [this comment](https://github.com/tremorlabs/tremor/issues/276#issuecomment-1386888872) for more info :)

**Comment by mitrotasios** [comment]
Closing as this should be possible with the v2 release.
