### ISSUE TITLE
Components' size

### ISSUE THREAD

**Issue by HoudhaifaNA** [tremorlabs/tremor-npm#289]
Thank you for the library, it is great . But I had one issue I am using `font-size: 10px` in the global style so 1rem equals 10px.
But your components won't work properly with this declaration, they are so small.

is there a way to control the size of components ?

**Comment by mitrotasios** [comment]
Hey @HoudhaifaNA, thanks for the feedback. It's true that you cannot easily customize font size currently. We are working on a new version that we expect to release end of Q1 that will allow for such customizations

**Comment by HoudhaifaNA** [comment]
Thank you. Keep up the good work

**Comment by sobhardwaj** [comment]
when you guys going to release next stable versions ?

**Comment by mitrotasios** [comment]
Closing as this should now be possible with the v2 release

**Comment by aaronvg** [comment]
how does one customize font size?

**Comment by mitrotasios** [comment]
you can customise the font-size classes (e.g. the `text-sm` class) in your tailwind config like so:
https://tailwindcss.com/docs/font-size#customizing-your-theme

What is not possible for now is replacing `text-sm` with `text-lg` for example in the component.
