### ISSUE TITLE
DateTime picker input for forms

### ISSUE THREAD

**Issue by kharann** [tremorlabs/tremor-npm#290]
Currently, there's a date picker. A lot of times dates are represented as DateTime. Perhaps a DateTime input would be beneficial

**Comment by mitrotasios** [comment]
@kharann, thanks for submitting this. Indeed, having a date time input is necessary for many use cases and we aim to add it at some point

**Comment by ethndotsh** [comment]
A DateTime + DateRangePicker combo would be great as well.

**Comment by mitrotasios** [comment]
Duplicate of #360
