### ISSUE TITLE
`<Button>` component not showing text after update to 1.6.1 version.

### ISSUE THREAD

**Issue by gianllopez** [tremorlabs/tremor-npm#293]
The following code was working perfect before the update:
`
<Button size="sm" text="Nuevo" color="blue" icon={MdOutlineAdd iconPosition="right" handleClick={() =>setCreating(true)}  />
`

But in the [documentation](https://www.tremor.so/docs/components/button), they marked some _props_ as _deprecated_, then i updated to the 1.6.1 version 
`<Button size="sm" value="Nuevo" color="blue" icon={MdOutlineAdd} iconPosition="right" onClick={() => setCreating(true)} />`

The _prop_ called `text` was changed to `value` and `handleClick` to `onClick`, Getting the following result:

![image](https://user-images.githubusercontent.com/63388127/216383881-d9ccdee7-3e9f-4b9e-a2fc-93cfcf03765a.png)

**Comment by mitrotasios** [comment]
@gianlop3z, sorry if this is confusing, but the `text` prop has **not** been replaced by `value`. Instead, the text can be passed as a children as follows:
```
<Button value={1}>
  Some Text
</Button>
```
