### ISSUE TITLE
Feature request: add textAlignment attribute to Metric

### ISSUE THREAD

**Issue by krisalyssa** [tremorlabs/tremor-npm#295]
I don't see any technical reason Metric can't allow the text alignment to be set.

**Comment by mitrotasios** [comment]
@CraigCottingham its true that there is no technical reason for this. Initially we intended to only expose properties which we felt are necessary for each component. We aim to change this in our `v2`, where we will expose a set of style properties for every component (e.g. `width`, `margin`, ...). I think it also makes sense to include `textAlignment`. This new version is expected to be released in the end of Q1.

**Comment by krisalyssa** [comment]
PR #298
