### ISSUE TITLE
Showing focus outline when clicked a part of pie chart sector

### ISSUE THREAD

**Issue by Curo-Dev** [tremorlabs/tremor-npm#299]
I really appriciate to use this library but I found a minor style issue using pie chart sector.
Below are the attached screenshot and code

I found out to fix this problem how can I request PR?

`.recharts-sector:focus { outline: none; }`

<img width="691" alt="image" src="https://user-images.githubusercontent.com/33403861/218014209-e7b5ab39-6fe1-4e93-b06f-43e5728bb518.png">

**Comment by christopherkindl** [comment]
Thank you for using our library and spotting this detail! 

Feel free to submit a PR or we can cover it as well - As you like 🙂
