### ISSUE TITLE
[docs] Missing textAlignment prop on Metric in "Card + Icon + Metric" Block

### ISSUE THREAD

**Issue by khajimatov** [tremorlabs/tremor-npm#302]
Metric component is missing `textAlignment = "text-center"` prop in "Card + Icon + Metric" Block in Documentation.
Link: [https://www.tremor.so/blocks/kpi-cards](https://www.tremor.so/blocks/kpi-cards#:~:text=Card%20+%20Icon%20+%20Metric)

Current version:
<img src="https://user-images.githubusercontent.com/62846961/218458334-ed2ca7f6-7637-4863-b4a1-88dd7fb9b36f.png" width="700" alt="Card + Icon + Metric Block" />
Fixed version:
<img src="https://user-images.githubusercontent.com/62846961/218458512-632fc620-a646-48b5-8712-d550b460c5b0.png" width="700" alt="Card + Icon  + Metric Block" />

**Comment by amirfakhrullah** [comment]
can I pick up this one?

**Comment by mitrotasios** [comment]
@khajimatov thanks a lot for submitting this! We'll fix this asap! 

@amirfakhrullah appreciate the involvement but I am afraid the Blocks codebase is not public so we will have to take care of this :(
