### ISSUE TITLE
Text input shows focus line in Firefox

### ISSUE THREAD

**Issue by birjj** [tremorlabs/tremor-npm#304]
When a text input with `icon={...}` or `error={true}` is focused in Firefox, a blue line will appear between the input and the displayed icon. It does not appear in Chrome. This issue appears on [the tremor docs page](https://www.tremor.so/docs/components/text-input):

![Comparison of Chrome and Firefox](https://user-images.githubusercontent.com/4542461/219125030-cdf98132-8721-4173-86d0-d1c9fdf7918c.png)

This is actually the default focus outline being shown, but cut off by the containing element which has `overflow: hidden`. It appears that Firefox chooses to ignore `outline-width` if `outline-style` is set to `auto`, and instead renders a default blue outline.

Using the `focus:tr-outline-none` class instead of `focus:tr-outline-0` should fix it.

--- 

**Aside:** Just in case you're interested, this behavior is actually permitted by [the CSS specification](https://w3c.github.io/csswg-drafts/css-ui/#typedef-outline-line-style): 

> As such, this specification does not define how the [outline-color](https://w3c.github.io/csswg-drafts/css-ui/#propdef-outline-color) and [outline-width](https://w3c.github.io/csswg-drafts/css-ui/#propdef-outline-width) are incorporated or used (if at all) when rendering auto style outlines. User agents may treat auto as solid

**Comment by mitrotasios** [comment]
@birjj thanks a lot for spotting this! Will fix asap!
