### ISSUE TITLE
Some chart labels are skipped & top of area chart cut off

### ISSUE THREAD

**Issue by nf-projects** [tremorlabs/tremor-npm#306]
I'm using two of the KPI with chart blocks from https://www.tremor.so/blocks/kpi-cards. It looks like this:
<img width="805" alt="image" src="https://user-images.githubusercontent.com/90344282/219882830-8097fd71-d879-464c-9e6d-a9a009586fec.png">

Why is the chart on the left cut off at the top? I'm using next.js.

**Comment by severinlandolt** [comment]
Hey @nf-projects, may you share the data of the chart? You might store the data as a string when it is supposed to be a number. Please refer to #247

**Comment by nf-projects** [comment]
Hey @severinlandolt, seems like that fixed it. Could this also cause another bug where some x-axis labels are skipped? (between 2/07 and 2/19 in the screenshot)
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/90344282/219987727-b022a69f-8359-407b-964f-bc2eda35e9fd.png">

Here is the code for the chart:
```ts
<div className="col-span-1 md:col-span-4 mt-5">
    <Card>
        <Title>Joins Per Day</Title>
        <Text>The number of unique joins per day across the last 90 days.</Text>
        <AreaChart
            marginTop="mt-4"
            data={formattedChartData}
            categories={["Unique Joins"]}
            dataKey="Date"
            colors={["indigo"]}
            valueFormatter={formatLargeNumber}
            height="h-80"
        />
    </Card>
</div>
```

Sample of the data: 
```json
[ 
  { "Date": "11/21/2022", "Unique Joins": 1047 }, 
  { "Date": "11/22/2022", "Unique Joins": 1089 }, 
]
```                

Sidenote: Storing the x-axis values as formatted strings is important here, since showing them as Date objects wouldn't fit on the screen with that many values.

**Comment by severinlandolt** [comment]
Recharts skips labels depending on your breakpoint to avoid overlapping labels, but evenly spaced labels are not enforced. This sometimes results in some whitespace between labels at specific breakpoints. We are in contact with recharts and we were told that there will be a solution to this problem in the next major release. 

I am going to close this issue. If you want to be updated regarding the labels, have a [look at our changelog](https://www.tremor.so/changelog) from time to time.

**Comment by nf-projects** [comment]
Is it possible to expedite this issue? I would argue this is a major issue for a charting/data display library, and I repeatedly receive user complaints about charts cutting off. Referring to both of the aforementioned charting issues.

**Comment by severinlandolt** [comment]
Hey @nf-projects, could you share a minimal working example where the chart is cut off?

**Comment by nf-projects** [comment]
@severinlandolt Here you go: https://gist.github.com/nf-projects/b14fa7726642ff4f4b186e4f4b4a8b18 - this is using the latest versions of Next.js, Tailwind, and Tremor. As you can see, both of the problems mentioned in this issue occur: inconsistent spacing of x axis labels as well as a cutoff at the top of the chart:
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/90344282/234062997-6c486f3a-7a39-4465-b9d3-e96108950653.png">

**Comment by severinlandolt** [comment]
Thanks @nf-projects, you have to store your value as a number, not as a string. 

Regarding the inconsistent spacing, there has been a fix on recharts, we will add equally distant ticks soon.

![CleanShot 2023-04-24 at 18 52 03@2x](https://user-images.githubusercontent.com/41927988/234064473-44d486de-9c9d-486d-834b-9253fd7b275f.png)

**Comment by nf-projects** [comment]
Thanks, wrapping the value in `Number()` seems to have done the trick!

Looking forward to the spacing fix! Thanks!
