### ISSUE TITLE
feature request: radial bar and gauge charts

### ISSUE THREAD

**Issue by avengerweb** [tremorlabs/tremor-npm#307]
That is popular thing in dashboard, do you have any plans to implement it?

examples:
https://apexcharts.com/react-chart-demos/radialbar-charts/gradient/
https://apexcharts.com/react-chart-demos/radialbar-charts/semi-circle-gauge/

**Comment by severinlandolt** [comment]
Hey @avengerweb thank you for reaching out about new chart types. There is definitely a case for an adjusted radial chart like the first example. Regarding the gauge, it gets a little bit more complicated. We see not so many impactful use cases that would justify adding this type of chart.

**Comment by mitrotasios** [comment]
thanks for the suggestion @avengerweb, I am afraid we don't have the resources for now to implement this, so I will close this issue for now.
