### ISSUE TITLE
Tremor global css setting font

### ISSUE THREAD

**Issue by christianjuth** [tremorlabs/tremor-npm#310]
I just started using tremor and I'm glancing at the global css file. I'm not loving that it changes the font for my entire application. I prefer libraries that keep styles local to their own elements. Is it possible to remove the style being applied to the `html` tag or split this into two style sheets (the way tailwind splits it's styles into 3 imports).

```
:root {
  --tr-font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont,
    "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"; /* 4 */
}

html {
  font-family: var(--tr-font-family);
}
```

**Comment by mitrotasios** [comment]
Hey @christianjuth, yeah that is a fair point. In fact this will not be the case anymore with the next major release coming in the next 1-2 weeks.
