### ISSUE TITLE
Barchart height/width or scrolling overflow

### ISSUE THREAD

**Issue by casperleerink** [tremorlabs/tremor-npm#313]
Hi!

I just started using tremor and I am really liking it.

I just noticed on the `<BarChart />` component, when adding more then a few datapoints, it does not make the chart wider or in vertical mode more tall. but rather makes the bars very small and hides some of the labels. 
<img width="1361" alt="Screenshot 2023-02-28 at 10 06 47 AM" src="https://user-images.githubusercontent.com/34733591/221944594-a114be5a-7e57-452b-8fc9-a7b84afd9c81.png">

Is there a way I am missing to make the chart fit the height of the items instead of the items trying to fit within the height of the chart? I already set the height to the maximum `h-96`, but with more than 10 items this still is too little. An option to scroll or even just make the chart height much more would be a great addition. I read that you are in the process of updating the charts API. So I am not sure if this is included in the upcoming update, but I thought I would leave this here as some user feedback.

Thank you, Casper

**Comment by mitrotasios** [comment]
Hey @casperleerink thats a valid point, thanks for submitting. We'll look into how to fix this!

**Comment by mitrotasios** [comment]
@casperleerink you can now increase the height to more than `h-96` by adding using square brackets in the tailwind class, e.g. `h-[100rem]`.
