### ISSUE TITLE
Adding "isLoading" property to Card component

### ISSUE THREAD

**Issue by MatheusChein** [tremorlabs/tremor-npm#314]
Hey guys! First of all, awesome library, we're testing it in our company and it's really straightforward to use!

Also, this is my first issue opened to an open-source project with actual improvement suggestions, instead of reporting a bug 😅 So, if I say something weird, just bear with me, I'm new to this.

I stumbled upon a scenario where I had to wait for the data to be loaded before showing the Cards, so I created a component that needed to receive all of the `Card` properties plus an `isLoading` one. It looked like this: 

![image](https://user-images.githubusercontent.com/57330825/222238743-dcf6a301-2868-49d9-b5b4-ad8dedbb4c43.png)

Here, I used the `CircularProgress` from MaterialUI, but there's certainly a more elegant way to do this, with a loader compatible with Tailwind or a skeleton component.

Also, there's an issue that I had to dig for the `CardProps` interface way down into the library files. If there's an easier way to get it, I must've missed it. 

So, I have 2 features suggestions: 
- Make the `CardProps` available more easily from the library
- Add a native `isLoading` property to the `Card` component, in order to be easier to work with fetching remote data

Thanks!

**Comment by kalmndo** [comment]
hey that's is a good idea.
i think it's better with skeleton loading instead of circular progress.

**Comment by severinlandolt** [comment]
Heya @MatheusChein, thank you for reaching out. We decided not to add this feature because this could be implemented by the user directly. Furthermore, the skeleton we would love to have for ourselves depends on the card's content, which would not be implementable on an abstract/general level.
