### ISSUE TITLE
Donut: how to get legend and values inside or outside each pie

### ISSUE THREAD

**Issue by rmrbytes** [tremorlabs/tremor-npm#315]
In the Donut (both variants):

1. Is there a way to get the Legends esp if tooltip is disabled (e.g. on mobiles).
2. Is  there a way to get pie values (absolute or percentages) inside or outside of the Pie

Thanks

**Comment by rmrbytes** [comment]
I notice that we can add a legend as a separate element using `Legend` and extracting the categories from the data prop.

```
const categories = props.data.map(item => item.name)

<Legend categories={categories} />
```

That leaves the pending how best to get the values put in each Pie?

Thanks

**Comment by rmrbytes** [comment]
I am just loving this library and have made changes to an ongoing project using it. I have been browsing the issues and am delighted that many features are being added. Thanks.

Is adding children props to the components being planned? The above requirement then could easily be user-customised.

Thanks

**Comment by severinlandolt** [comment]
Hi @rrrepos, glad you enjoy the library! it's currently not possible to display any values next to the segments of a donut/pie. We will add HTML attributes and children props to our components in our next release.

**Comment by rmrbytes** [comment]
Thanks. Will await that release. 

To add Tremor is a wonderful and convenient library for recharts and other dashboard widgets. Thanks

**Comment by samirrayani** [comment]
@severinlandolt did this get released? is it possible to display values next to or inside pie chart segments?
