### ISSUE TITLE
Table rows and Cards are not clickable/linkable

### ISSUE THREAD

**Issue by lucafaggianelli** [tremorlabs/tremor-npm#317]
Hi there,

this is probably wanted as many components in the library are not clickable/linkable, are you going to add an onClick handler on table rows and an href and linkComponent props on cards?

BTW amazing work with tremor! I just discovered it and I love it

**Comment by severinlandolt** [comment]
Hi @lucafaggianelli thank you for reaching out. I have good news for you! This will functionality will be added throughout the library with our next release (next 5-10 days).

**Comment by lucafaggianelli** [comment]
Great , thanks 😊
