### ISSUE TITLE
textAlignment "text-end" not working in TableCell and TableHeaderCell

### ISSUE THREAD

**Issue by lucafaggianelli** [tremorlabs/tremor-npm#318]
The `"text-end"` value of the `textAlignment` property in `<TableCell>` and `<TableHeaderCell>` doesn't work, though text-end works in other comopnents

Example:
```tsx
<TableHeaderCell textAlignment="text-end">Duration</TableHeaderCell>
```

**Comment by severinlandolt** [comment]
Hey @lucafaggianelli, thanks for noticing. With our next release, the `textAlignment` property will be deprecated. You will be able to set this within the usual className.

**Comment by lucafaggianelli** [comment]
Ah ok that would be great indeed I was missing the classname
