### ISSUE TITLE
Button: request to add all directions in IconPosition

### ISSUE THREAD

**Issue by rmrbytes** [tremorlabs/tremor-npm#320]
Currently the `iconPosition` in the Button component supports values **left** and **right**. It would help to be able to have the icon on top with the text below.

Thanks

**Comment by severinlandolt** [comment]
Hi @rrrepos, your feedback is much appreciated!

We discussed your idea and have to say no. We are an opinionated library. Hence buttons with `iconPosition` other than left/right are too niche to be included.

**Comment by rmrbytes** [comment]
Respect your views on it.
