### ISSUE TITLE
Feature request: Clear selection on the date range picker

### ISSUE THREAD

**Issue by mrseabass** [tremorlabs/tremor-npm#321]
Currently once you have selected a date range, either via the date picker or the relative time dropdown, there is no way to clear the selection.

![CleanShot 2023-03-08 at 09 52 30@2x](https://user-images.githubusercontent.com/7720873/223762374-bbe6f77c-4131-40c0-b352-f979a93b811e.png)

It would be great if one could enable removing the selection via props on the component.

**Comment by severinlandolt** [comment]
Hello there, @mrseabass! I appreciate your input and agree that a reset button would be beneficial!

**Comment by Souravpakhira** [comment]
@severinlandolt Hi I would like to contribute to this project. So can I fix this issue?

**Comment by mitrotasios** [comment]
@Souravpakhira sorry for the late reply, sure feel free to submit a PR if you like!

**Comment by Souravpakhira** [comment]
@mitrotasios  Sure I will picking up the issue and start working on it.

**Comment by Souravpakhira** [comment]
This issue can be closed
