### ISSUE TITLE
Marker from MarkerBar component on the Progressbar component

### ISSUE THREAD

**Issue by fayazara** [tremorlabs/tremor-npm#322]
It'd be good to have the marker from the `MarkerBar` component on the `ProgressBar` component, something like below.

![Screenshot 09-03 at 14](https://user-images.githubusercontent.com/15716057/223968280-be9c121b-6217-4832-8299-490c9bba6b38.png)

**Comment by mitrotasios** [comment]
hey @fayazara, thanks for the suggestion! I am afraid we will not implement this for now as we believe it gives users the impression that it is a slider they can interact with.
