### ISSUE TITLE
Feature Enhancement: Text Input to extend to email, password and number types 

### ISSUE THREAD

**Issue by rmrbytes** [tremorlabs/tremor-npm#329]
Are there any plans to extend the Text Input component to support other text types viz: email, passwords and numbers? Thanks

**Comment by rawnly** [comment]
+1

**Comment by ethndotsh** [comment]
+1

**Comment by i701** [comment]
Yes this would be really cool.

**Comment by thomasmcinnis** [comment]
100% having text field support password type would be amazing!

**Comment by mitrotasios** [comment]
`TextInput` now supports a `password` type with the newest release [v2.1.0](https://github.com/tremorlabs/tremor/releases/latest). We are currently working on a `NumberInput` component as well.

**Comment by rawnly** [comment]
@mitrotasios awesome! 
Is it possible to have email too? 😅

Anyway tbh, I don't understand why not just exposing the attribute type to the lib user.. I can understand number/date, but why limiting to password and text? (i.e url,email etc)

**Comment by mitrotasios** [comment]
We can't just expose the native prop because we don't allow for number / date and several others as you said. We'll add `email` and `url` as well since people want that but I don't see another another type that would make sense in this context of a plain TextInput.

**Comment by severinlandolt** [comment]
* New [NumberInput](https://www.tremor.so/docs/components/number-input)
* More [types on text](https://www.tremor.so/docs/components/text-input)
