### ISSUE TITLE
Incorrect Documentation for “Card + Metric + CategoryBar”

### ISSUE THREAD

**Issue by Doppelfelix** [tremorlabs/tremor-npm#340]
For the entry of “**Card + Metric + Category Bar**” on the documentation page [https://www.tremor.so/blocks/kpi-cards](https://www.tremor.so/blocks/kpi-cards)
there is a small bug in the code.

Here is the problematic snippet:
```
<Flex justifyContent="justify-start" alignItems="items-baseline" spaceX="space-x-1">
    <Metric>{ item.title }</Metric>
    <Text>/ 10</Text>
</Flex>
```

it should be `item.metric` instead of `item.title`

**Comment by severinlandolt** [comment]
Solved, thank you!
