### ISSUE TITLE
Feature Request: Expose default styles for use in custom components

### ISSUE THREAD

**Issue by bernsno** [tremorlabs/tremor-npm#342]
While Tremor comes with many great components, it will never fulfill 100% of everyone's needs. It would be great if it were easy to reuse Tremor's default styles when we need to build new, custom components. 

Today I believe I need to copy over a bunch of style information in order to stay consistent with the rest of my dashboard, when I build something custom. It'd be awesome if Tremor provided some easy way to reuse those defaults style when new components are needed.

Alternatively, it'd be great if Tremor offered a component designed for extensibility with recharts so if you need to make a more complex, or purpose-specific chart you could keep the design consistent with other Tremor charts.

**Comment by mitrotasios** [comment]
@bernsno, I agree that maintaining design consistency with the remaining app may is difficult with how tremor works currently. Do you have a suggestion on how we could expose our styles for reuse?

Also, our next larger thing on the roadmap is theming / custom colouring, we don't have a specific timeline on that though unfortunately.

**Comment by JPrisk** [comment]
> It'd be awesome if Tremor provided some easy way to reuse those defaults style when new components are needed.

with utility classes being used across the library, inheriting styles doesn't really fit with the methodology 

> Do you have a suggestion on how we could expose our styles for reuse?

wonder if a design methodology page added to the docs would help? calling out things like `shaddow-xl` `rounded-lg` and pointing people to tailwindcss for more info

**Comment by bernsno** [comment]
Sorry I haven't had a chance to open an example PR for this, will try to do next week. @JPrisk you make good points about utility classes. What I'm hoping could be offered are easy ways to create graphs that are more complex than what tremor needs to support for most use cases, but maintain the existing styles (type, color, spacing around components). Your suggestion of highlighting design methodology could be a good starting point, but curious if there's a way to create an extensible chart component that gets someone part of the way to a new component.

**Comment by severinlandolt** [comment]
Hey there, despite not solving all the issues mentioned here, I hope the ability to style root elements through className, as well as the theming added in v3 helps with this issue. If that rings true, I'd say we could close this issue. Let me know @bernsno

**Comment by severinlandolt** [comment]
I am going to close this issue, thanks for the discussion!
