### ISSUE TITLE
[Bug] [Documentation - Layout] Grid layout link is pointing to false path 

### ISSUE THREAD

**Issue by agustinusnathaniel** [tremorlabs/tremor-npm#343]
Really excited to see the 2.0 release! The components page look neat and great

### Problem Description
When I clicked the `Grid` layout link, it directs to false path / url. Would like to sent PR if the site repo is available but looks like it's not 😅 , so will try to report here.

### Link to Reproduction
https://www.tremor.so/components

### Steps to Reproduce
1. Go to https://www.tremor.so/components
2. Scroll down to Layout section
3. Click `Grid` component
4. It will redirect to https://www.tremor.so/docs/layout/col-grid (and showing 404 not found)

### Expected Behavior
Redirect to https://www.tremor.so/docs/layout/grid and not showing 404 not found

**Comment by christopherkindl** [comment]
Oh thanks for that!
