### ISSUE TITLE
The Linechart component returns an error e.split is not a function 

### ISSUE THREAD

**Issue by JumboDaniel** [tremorlabs/tremor-npm#344]
`
import { Card, Title, LineChart as Chart } from "@tremor/react";

const chartdata = [
  {
    year: 1951,
    "Population growth rate": 1.74,
  },
  {
    year: 1952,
    "Population growth rate": 1.93,
  },
  {
    year: 1953,
    "Population growth rate": 1.9,
  },
  {
    year: 1954,
    "Population growth rate": 1.98,
  },
  {
    year: 1955,
    "Population growth rate": 2,
  },
];

const dataFormatter = (number) =>
  `${Intl.NumberFormat("us").format(number).toString()}%`;

 const LineChart = () => (
  <Card>
    <Title>Population growth rate (1951 to 2021)</Title>
    <Chart
      className="mt-6"
      data={chartdata}
      index="name"
      categories={["Population growth rate"]}
      colors={["blue"]}
      valueFormatter={dataFormatter}
      yAxisWidth={40}
    />
  </Card>
);

export default `LineChart``

Then I imported this component into my dashboard/index folder I got an error e.split is not a function -(TypeError: e.split is not a function)

**Comment by JumboDaniel** [comment]
> ` import { Card, Title, LineChart as Chart } from "@tremor/react";
> 
> const chartdata = [ { year: 1951, "Population growth rate": 1.74, }, { year: 1952, "Population growth rate": 1.93, }, { year: 1953, "Population growth rate": 1.9, }, { year: 1954, "Population growth rate": 1.98, }, { year: 1955, "Population growth rate": 2, }, ];
> 
> const dataFormatter = (number) => `${Intl.NumberFormat("us").format(number).toString()}%`;
> 
> const LineChart = () => ( <Title>Population growth rate (1951 to 2021)</Title> <Chart className="mt-6" data={chartdata} index="name" categories={["Population growth rate"]} colors={["blue"]} valueFormatter={dataFormatter} yAxisWidth={40} /> );
> 
> export default `LineChart``
> 
> Then I imported this component into my dashboard/index folder I got an error e.split is not a function -(TypeError: e.split is not a function)
Update: I updated my Tremor package and I got another error
`
./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[7].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[7].use[2]!./node_modules/@tremor/react/dist/esm/tremor.css
Error: ENOENT: no such file or directory, open 'C:\Users\hp\Documents\HTML\Jobs\coinmplifynext\node_modules\@tremor\react\dist\esm\tremor.css'`


I am using-`
    "next": "12.3.1",
    "@tremor/react": "^2.0.0",
    "react": "18.2.0",
`

**Comment by mitrotasios** [comment]
Hey @JumboDaniel, we released a breaking change yesterday which does not export the `tremor.css` file anymore - instead, setting up tailwind is required. Please checkout the [installation guide](https://tremor.so/docs/getting-started/installation) for more infos.

Lmk if you face any more issues 🙂

**Comment by christopherkindl** [comment]
Hey @JumboDaniel, thanks for this feedback! We have now made this point more clear in our [migration guide](https://www.tremor.so/changelog)!

**Comment by JumboDaniel** [comment]
Hello, @mitrotasios @christopherkindl. I did all that already and the error (TypeError: e.split is not a function) has come back again.

**Comment by severinlandolt** [comment]
Hey @JumboDaniel, can you try and replace `index="name"` with `index="year"`? There was a bug in our documentation.
