### ISSUE TITLE
Button Component throws error

### ISSUE THREAD

**Issue by bfourgeaud** [tremorlabs/tremor-npm#346]
## Project Environnement
"@tremor/react": "^2.0.0"
"next": "13.2.4" (with app dir)

`next.config.js`
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
    serverComponentsExternalPackages: ['@tremor/react']
  },
}

module.exports = nextConfig
```

## Issue
Whenever I add a `<Button />` component, the application throws an error and crashes.

## Code
```tsx
import { Button, Title } from "@tremor/react";

export default function TestPage() {
  return (
    <main className="p-4 md:p-10 mx-auto max-w-7xl">
      <Title>Test components</Title>
      <Button>Click me</Button>
    </main>
  )
}
```

## Error
Throws `Error: Cannot set properties of undefined (setting 'props')`

## Workaround
I have found that wrapping the button into a component with `"use client"` seems to work. But It is for now the only component for which it happens. I tried `Card`, `Metric`, `Title`, `Text`, `Grid`, `Col`, `Flex`, `BarList`, `BadgeDelta`, `DeltaType`, and they didn't need client component wrappers.

```tsx
"use client"

import { Button } from "@tremor/react"
export default Button
```

**Comment by jgtvares** [comment]
Same issue here!

**Comment by severinlandolt** [comment]
@bfourgeaud  Thank you for the hint. This looks like a bug to me. May I ask if with Next `13.3` the issue has gone away?

**Comment by mitrotasios** [comment]
This behaviour should be expected as `Button` is not a client component. We generally recommend using the `"use client"` directive with the Next13 app dir, as we haven't migrated to Next13 yet.
