### ISSUE TITLE
Line Chart Component - Typo in Code Sample

### ISSUE THREAD

**Issue by MarcACard** [tremorlabs/tremor-npm#350]
Hey Team, 

When reading through the docs I got tripped up by the code sample within the **[Line Chart Component](https://www.tremor.so/docs/components/line-chart)**. The index prop has a value of "name", but I believe it should be "year"? 

``` javascript
export default LineChart = () => (
  <Card>
    <Title>Population growth rate (1951 to 2021)</Title>
    <LineChart
      className="mt-6"
      data={chartdata}
      index="name"   // <--- Incorrect attribute value. 
      categories={["Population growth rate"]}
      colors={["blue"]}
      valueFormatter={dataFormatter}
      yAxisWidth={40}
    />
  </Card>
 ```

Keep up the great work on the lib!
Cheers

**Comment by severinlandolt** [comment]
Thank you for pointing this out, will be fixed asap!
