### ISSUE TITLE
Wrong classname prefix in migrating to v2

### ISSUE THREAD

**Issue by Lantianyou** [tremorlabs/tremor-npm#351]
After migrating from v1 to v2, I found the classname of `@tremor/react` has a prefix called tr-. My project already use tailwindcss, and I changed the configuration file as instructed from docs.  I believe removing this prefix can solve the problem, but I do not know how. It would be really great if someone can help.
![image](https://user-images.githubusercontent.com/37259750/225505723-b04c5756-2b21-4034-9518-5b538c4e4244.png)

**Comment by Lantianyou** [comment]
This is a project built with `vite`, `turborepo`, `tailwindcss` and `antd`. The tailwindcss config file looks like this:

```js
/** @type {import('tailwindcss').Config} */

module.exports = {
	content: [
		'./index.html',
		'./src/**/*.{js,ts,jsx,tsx}',
		'./node_modules/@tremor/**/*.{js,ts,jsx,tsx}',
	],
	theme: {
		extend: {},
	},
	plugins: [],
	corePlugins: {
		preflight: false,
	},
}
```

**Comment by mitrotasios** [comment]
Hey @Lantianyou, are you sure you have the newest tremor version installed? The v2 should not have any class prefixes.

**Comment by severinlandolt** [comment]
@Lantianyou Is there any update on your project? Otherwise, we are going to close this issue.
