### ISSUE TITLE
`TextInput` does not allow setting a `name` making it inaccessible

### ISSUE THREAD

**Issue by IgnisDa** [tremorlabs/tremor-npm#358]
`TextInput` seems not to support setting a `name` property. This makes in in-accessible and also makes it impossible to work with Remix `action`s because the submitted `TextInput` does not include the field in `request.formData`.

**Comment by mitrotasios** [comment]
@IgnisDa, the `TextInput` component does expose a `name` property as it extends all properties from the type `InputHTMLAttributes`. Have you tried adding a `name` and came across issues?

**Comment by IgnisDa** [comment]
Looks like I was adding the props on the wrong element. The `TextInput` works as expected. Thanks for looking into it!
