### ISSUE TITLE
Feature request : Datetime Picker

### ISSUE THREAD

**Issue by dwimawan** [tremorlabs/tremor-npm#360]
Hellow team very thankfull and apreciate for building tremor, this framework was awsome. I want to build my project fully using this react library framework, but i found the problem when i want to create date time input because in tremor only daterange picker.  so i must use the other library to get datetime picker input like antd datepicker (sadly the size is very big 😢). Hopefully tremor team can provide date / datetime input feature soon. Thanks a lot 🙌🏻
#290 

this is example antd datetime picker for my project, better i use the date picker from tremor 🤙🏻
<img width="751" alt="Screenshot 2023-03-20 at 6 13 45 PM" src="https://user-images.githubusercontent.com/55011109/226326126-b2598a7e-69e6-4aea-b9fb-175563b69689.png">

**Comment by mitrotasios** [comment]
Thanks for the suggestion, that's indeed something we would like to add soon

**Comment by dwimawan** [comment]
Okay thanks a lot, i'll wait for it.

**Comment by severinlandolt** [comment]
Hi @agusismawan, thanks for your feature request. We won't be adding this to the Tremor package. However, if you still need a Date Picker with Time, we recently released one here: https://raw.tremor.so/docs/inputs/date-picker#example-controlled-with-time-input

**Comment by dwimawan** [comment]
Thank you very much,
you really meet customer needs. Very thankfull and good job tremor team.
