### ISSUE TITLE
Possible bug in the Blocks examples on tremor's site.

### ISSUE THREAD

**Issue by joaqo** [tremorlabs/tremor-npm#364]
The example named "Card + Metric + List + ProgressBar" in the KPI section imports "Block" which seems to be outdated as I can't import it myself.

**Comment by joaqo** [comment]
I removed the Block from the sample in my code and replaced it with a div like this:

```jsx
  <Card>
    <Title>{title}</Title>
    <List className="mt-4">
      {data.map((category) => (
        <ListItem key={category.name}>
          <div>
            <Text>{category.name}</Text>
            <ProgressBar
              percentageValue={category.share}
              label={`${category.share}%`}
              tooltip={category.amount}
            />
            </div>
        </ListItem>
      ))}
    </List>
  </Card>
```

but I am getting the following results:
<img width="1593" alt="image" src="https://user-images.githubusercontent.com/14966348/226688153-cc27d6b8-ddd7-4f8e-80fe-96df99841080.png">

Does `ListItem` do something weird to its child nodes? How can I reproduce how it looks in the sample I mentioned earlier in which the text is on top of the progress bar?

**Comment by mitrotasios** [comment]
thanks @joaqo, good catch! There seems to be a w-full missing in the outer `div`. We'll fix it asap!

**Comment by severinlandolt** [comment]
@joaqo Heya! We fixed the code in the block section, can you try it again? There was a missing `div` with `className='w-full'`. Thanks 🙏

**Comment by joaqo** [comment]
Is Block a tremor component? I don't see it in the docs and can't import it.

**Comment by severinlandolt** [comment]
It used to be. The `Block` component was removed in the v2 release. For reference, see the [penultimate bullet point here](https://www.tremor.so/changelog)

Regarding the code snippet you shared above, this should work:

```diff
  <Card>
    <Title>{title}</Title>
    <List className="mt-4">
      {data.map((category) => (
        <ListItem key={category.name}>
+            <div className="w-full">
            <Text>{category.name}</Text>
            <ProgressBar
              percentageValue={category.share}
              label={`${category.share}%`}
              tooltip={category.amount}
            />
            </div>
        </ListItem>
      ))}
    </List>
  </Card>
```

@joaqo Let me know if this works for you 👍

**Comment by joaqo** [comment]
Gotcha thanks, just fyi, you're still using Block on the site's example I mentioned above.

**Comment by severinlandolt** [comment]
Thanks for noticing! I will close this issue now, happy coding 👾
