### ISSUE TITLE
SelectBox is missing the props required and name

### ISSUE THREAD

**Issue by lucafaggianelli** [tremorlabs/tremor-npm#366]
I'm using the standard HTML form element so it would be nice to have the `name` property to handle form data on submit.

SelectBox it's also missing the `required` property.

**Comment by mitrotasios** [comment]
Good points, we'll try to add these props!

**Comment by jorgeramirezamora** [comment]
@mitrotasios can u give some guidance in where to start? I can add those

**Comment by mitrotasios** [comment]
hey @jorgeramirezamora thanks for offering this, we are currently working on migrating our Input elements to use headlessui as it would enable us to make them easily accessible. So I think it wouldn't make sense to start working on this issue until the migration is complete. Should I get back to you once this is the case? Also, feel free to join our Slack community and we can chat about delegating other tasks to you if you're interested in contributing!

**Comment by jorgeramirezamora** [comment]
Makes sense. And yes please, I am interested in contributing 🚀 How can I join Tremor's Slack?

**Comment by mitrotasios** [comment]
Awesome! Here’s the link: https://t.co/g99pltTvIC

**Comment by christopherkindl** [comment]
Hey @jorgeramirezamora, the select boxes now run on Headless UI and we still need to add `id` and `name` and some underlying changes to use them in forms. Let me know if you want to contribute here!

**Comment by jorgeramirezamora** [comment]
Sure, lemme wrap up https://github.com/tremorlabs/tremor/issues/670 first

**Comment by christopherkindl** [comment]
@jorgeramirezamora awesome, thanks!

**Comment by jzfrank** [comment]
I would like to be assigned for this. :)

**Comment by rmn-kh** [comment]
I am using SelectBox and MultiSelectBox in a form and here I dont have props like `required `and `name `for them.
I'm using tremor V2.0.1
is there any idea how to deal with this?

**Comment by mbauchet** [comment]
There is already a PR (#729) on this
