### ISSUE TITLE
Migration to v2 is missing a couple of notes

### ISSUE THREAD

**Issue by lucafaggianelli** [tremorlabs/tremor-npm#367]
Hey guys, great work with v2! I already loved v1 but now with v2 we really have all the necessary flexibility (i.e. className 😄)

I found the migration pretty quick, though there are some missing items in the changelog at https://www.tremor.so/changelog:

- `MultiSelectBox` doesn't accept a generic anymore (before it was needed as it didn't understand automatically the items type in `onValueChange`)

- `ColGrid` replaced with `Grid`

- `Tracking` and `TrackingBlock` replaced with `Tracker`

- `tr-` prefixed CSS classes are not available anymore

- Table headers not sticky anymore. Not sure what change here though

**Comment by mitrotasios** [comment]
@lucafaggianelli thanks a lot for pointing these out!! We'll edit our changelog accordingly. The table-header issue is unexpected indeed, we'll look into it!

**Comment by severinlandolt** [comment]
Hi all, there is a new issue dedicated to the sticky headers. Hence, I will close this issue and take the discussion over there. Thanks, @lucafaggianelli for the hints!
