### ISSUE TITLE
Svelte

### ISSUE THREAD

**Issue by mquandalle** [tremorlabs/tremor-npm#368]
Thank you so much for your work with Tremor! I think you created the best components to build a beautiful and effective dashboard.

I'm currently using Tremor in a Svelte application using https://github.com/bfanger/svelte-preprocess-react, a preprocessor to integrate React components in a Svelte app. This is an ok solution but is slightly complex to set up, is less integrated (doesn't support SSR) and is fragile.

I'm happy continuing using this solution but I wonder if long term you would consider supporting other frontend frameworks, Svelte in particular. I understand that it isn't an easy task (how to share the view logic between frameworks, etc.) but I'm curious what are you thoughts on this.

**Comment by severinlandolt** [comment]
Hey @mquandalle,

Thank you for your feedback and for your interest in Tremor. We appreciate your suggestion to support Svelte. While we understand the value that this feature could bring to our users, we regret to inform you that we do not currently have plans to support Svelte or other frameworks.

As you mentioned, supporting other frameworks is a complex task that requires significant resources and effort. At this time, our development team is focused on other priorities that we believe will bring the most value to our users.

Thank you again for your support of Tremor, and we wish you the best in your future projects 🍀
