### ISSUE TITLE
Bug: Values cut off in Y axis

### ISSUE THREAD

**Issue by bernsno** [tremorlabs/tremor-npm#370]
When the Y axis in a chart has a wide range the values end up cut off. The Y axis in this range runs from $0 to $300k+.

<img width="355" alt="image" src="https://user-images.githubusercontent.com/13946/227638373-6e5c1807-6dff-48e3-9c8b-a55f71107d27.png">
 
The mark up for this graph is effectively 

```
<Card>
  <Title>Chart Name</Title>
  <AreaChart
    ...
   />
</Card>
```

**Comment by mitrotasios** [comment]
In these cases you can set the width of the axis with the `yAxisWidth` prop.

**Comment by bernsno** [comment]
Thanks @mitrotasios, will give this a shot. I'm good to close this, apologies for the issue noise.

**Comment by mitrotasios** [comment]
Np, issues are always welcome! :)
