### ISSUE TITLE
Typo in https://www.tremor.so/docs/components/data-bars

### ISSUE THREAD

**Issue by ImBIOS** [tremorlabs/tremor-npm#373]
![image](https://user-images.githubusercontent.com/41441643/227721326-311f049e-415a-44f9-91f0-b42ccef2642b.png)

You got it 👍
It should be CategoryBar, not RangeBar in the bottom image

**Comment by severinlandolt** [comment]
Thanks for the hint! Fixed!

**Comment by ImBIOS** [comment]
@severinlandolt I actually when found this typo want to fix it directly, but where is the docs webpage in this repo? I couldn't find them.
