### ISSUE TITLE
Integration with existing projects 

### ISSUE THREAD

**Issue by danny-waite** [tremorlabs/tremor-npm#379]
How best to integrate into an existing project, in this case, using the Mantine framework?

I noticed you recently added a prefix to tailwind classes however when I include tailwind in my project it negatively effects some key Mantine components.

removing `@tailwind base` helps with that but it seems Tremor relies of those base styles to properly function.

**Comment by mitrotasios** [comment]
Hey, in fact we removed the tailwind class prefix in the newest version. So there shouldn't be any conflicts with existing tailwind classes, if I understand the question correctly. Note though, tremor does currently **not** support projects that **do include** a prefix.

**Comment by shacthulu** [comment]
> 

Hey Danny, I might be going down this road soon.  Did you have any difficulties using Mantine and Tremor together with the newer version as per mitrotasios?

**Comment by ccrvlh** [comment]
I couldn't make it work with Mantine v5 and NextJS, still playing around but it's not plug and play (styles won't show, charts won't render etc). Will post here if I find something.
