### ISSUE TITLE
termor adds 800kb to remix bundle

### ISSUE THREAD

**Issue by bjruberg** [tremorlabs/tremor-npm#383]
I investigated a quite impressive addition to the JS bundle by importing three tremor components.

![image](https://user-images.githubusercontent.com/41144946/229096271-0b3ea8f8-da1c-43de-8c5b-47a5fc56b02f.png)

I was surprised to see that the imported file `node_modules/@tremor/react/dist/esm/index.js` is 1.2MB in size and seems to include several external libraries like react-dom.production.min.jsm 

This seems unintended and explains the huge amount of bytes.

**Comment by mitrotasios** [comment]
Hey thanks for sharing this, we'll investigate this further!

**Comment by ducan-ne** [comment]
I got the same issue with Vite, tremor adding 1m1 MB to bundle. Contains 2 version of react-dom, which is crashing my (only) prod environment. Just spent a day in investigating to understand this 🙏

**Comment by ducan-ne** [comment]
It contains another react-dom from 2.0.0

<img width="1533" alt="CleanShot 2023-04-10 at 02 29 29@2x" src="https://user-images.githubusercontent.com/16853175/230792800-6571c4b0-927b-490e-8b1b-8fcc7ae94425.png">

**Comment by mitrotasios** [comment]
Thanks all for looking into this! Turns out `react-transition-group` had listed `react-dom` as a peerDep and we hadn't added it to our peerDeps. Should be fixed with `v2.2.0`

**Comment by bjruberg** [comment]
I just see a minor improvement from 800kb to 682kb.
The index.js files in dist still contain the code for classNames and react 16.

Also treeshaking fails for me using remix/esbuild. 

![grafik](https://user-images.githubusercontent.com/41144946/234358423-86ff3195-38cc-483c-aa3b-03be4e63ba2d.png)

**Comment by mitrotasios** [comment]
should be fixed with `v2.4.0`
