### ISSUE TITLE
Documentation improvement request : Provide code example for MultiSelectBox with search functionality

### ISSUE THREAD

**Issue by i701** [tremorlabs/tremor-npm#386]
Hey team!!
Very thankful for building tremor, this framework is turning out to be super clean and easy to work with. I was reading the documentation for `SelectBox` and `MultiSelectBox` and noticed there is no proper code example for `MultiSelectBox` in the docs. The `MultiSelectBox` example with search functionality seems really nice and well implemented and I am interested to see the code for it. The code for many other components is also provided. I don't understand why the code implementation for this is missing. Kindly requesting to update the docs.

![image](https://user-images.githubusercontent.com/72292943/230030106-bc05d119-2934-44ad-a8d4-d11e63d1bcde.png)

**Comment by thomasmcinnis** [comment]
Hi - I've been using a lot. It has the exact same implementation as for SelectBox. Nothing different required! Just replace the `SelectBox` and `SelectBoxItem` for `MultiSelectBox` and `MultiSelectBoxItem`.

There is also an implementation example in step 4 of the onboarding demo dashboard [here](https://www.tremor.so/docs/getting-started/demo-dashboard)!

**Comment by i701** [comment]
> Hi - I've been using a lot. It has the exact same implementation as for SelectBox. Nothing different required! Just replace the `SelectBox` and `SelectBoxItem` for `MultiSelectBox` and `MultiSelectBoxItem`.
> 
> There is also an implementation example in step 4 of the onboarding demo dashboard [here](https://www.tremor.so/docs/getting-started/demo-dashboard)!

Ooh. Thank you.

**Comment by severinlandolt** [comment]
Hey @i701 I added a new example in the docs. Happy coding 🚀

**Comment by tonyxiao** [comment]
@severinlandolt related question - why does the MultiSelect box support search but single select box does not?

**Comment by thomasmcinnis** [comment]
@tonyxiao this is because the select box itself is a search field, and as only one item can be selected at a time it is overwritten by a new search. Nb. there was a [recent fix for a little mis-behaviour of the single select dropdown search](https://github.com/tremorlabs/tremor/issues/388)
