### ISSUE TITLE
Select box appears to be text input search, but typing breaks select box function.

### ISSUE THREAD

**Issue by thomasmcinnis** [tremorlabs/tremor-npm#388]
**Problem:**
When using select box, the box itself is a text input. 

If there is no default value, it works as a search field, filtering select box items. This gives users the impression they should search via type. But the typed text does not render, and after a selection is made, the text field becomes inoperable. 

If a default value property is set then typing in the field immediately filters the items to match the default value, the text field cannot be used to "clear" the selection. 

(User workaround:  if they then select the currently selected item the erroneous filtering is removed.)

**Repro:** 
See the select box demo in the docs. With the select box focussed, type any char. The list is now only showing Option One.

**Possible solution:** 
Add the same search functionality found on multi-select box, separating the current or default value in the select box from typed input, providing users an obvious UI to filter the select box items.

**Comment by severinlandolt** [comment]
Hey @tryanmac, thank you for your feedback, this is a bug indeed. We will sort this out soon. 👍
