### ISSUE TITLE
first dashboard tutorial is error

### ISSUE THREAD

**Issue by ImBIOS** [tremorlabs/tremor-npm#389]
need to fix these duplicate and error props
![image](https://user-images.githubusercontent.com/41441643/230551150-922a38ed-3561-40f7-b629-4f5af72ce54e.png)

marginTop and duplicate numsCol

**Comment by ImBIOS** [comment]
You can assign me to work on this, but... I think this docs is not yet open sourced, right?

**Comment by severinlandolt** [comment]
Hey @ImBIOS, thank you very much for your hint, I just fixed the issues. Thank you for sticking around and happy coding 🫶
