### ISSUE TITLE
Text Enhancements

### ISSUE THREAD

**Issue by bfowle** [tremorlabs/tremor-npm#391]
Hello~ Cheers on v2, the `className` override has been a huge help.

I noticed on `Text` however, the `className` does not persist (it defaults to the normal `text-gray-500 text-sm font-normal` style).

Also, it would be great to be able to add a `title` to these, in cases of truncating a long string of text and showing the full value on the title.

**Comment by severinlandolt** [comment]
Hey @bfowle thank you for the hint on the text element and the title attribute, we will have a look at it. 🙏

**Comment by mitrotasios** [comment]
hey @bfowle, this was a bug and should be fixed in #352 (v2.0.1). Maybe you haven't installed the latest version? Lmk if there's any other issues.
