### ISSUE TITLE
Allow y-axis customizaion

### ISSUE THREAD

**Issue by priosshrsth** [tremorlabs/tremor-npm#394]
## Issue
- Cannot format y-axis to be currency, since providing string seems to always add decimal point.

## Solution
  I think allowing some of the props like disabling decimal on y-axis would help in situations like this.

**Comment by mitrotasios** [comment]
@priosshrsth have you tried using the `valueFormatter` prop to pass a formatter callback?

**Comment by priosshrsth** [comment]
Yes, I am using valueFormatter to remove decimal points and format as currency. But it seems to add decimal points automatically on y axis.

**Comment by mitrotasios** [comment]
Closing as reported as fixed in #395
