### ISSUE TITLE
Date Range Picker end date value is not inclusive of last day

### ISSUE THREAD

**Issue by thomasmcinnis** [tremorlabs/tremor-npm#396]
The end date is being returned with 00:00:00 so the last day is not inclusive.

This also means if you select "tdy" the value of the range is no timespan, when it should be inclusive of today

**Example return value:**
`[Fri Apr 14 2023 00:00:00 GMT+1000 (Australian Eastern Standard Time),
Fri Apr 14 2023 00:00:00 GMT+1000 (Australian Eastern Standard Time),
"tdy"]`

**Work Around:**
`let startDate = selectedDateRange[0];`
`let endDate = selectedDateRange[1];`
 `if (endDate) {`
      `endDate.setHours(23, 59, 59, 999);`
  `}`

**Comment by mitrotasios** [comment]
@tryanmac oh thats a good point, will fix!

**Comment by mitrotasios** [comment]
Thanks again for submitting this. On second thought, I think its best to return the end date as is given that this is a date picker and it should not be concerned with time values. The work around can be implemented downstream if required. Other component libraries have the same behaviour.
