### ISSUE TITLE
BarList individual bar colour option

### ISSUE THREAD

**Issue by aatif24** [tremorlabs/tremor-npm#397]
Hi,
You guys are doing great work!

Can colours be added to the individual bars in BarList?
Thank you :)

ex. 
<img width="508" alt="image" src="https://user-images.githubusercontent.com/46748960/232104982-5890d857-c0cf-4b9c-b7f5-8ffca5b0dee8.png">

**Comment by mitrotasios** [comment]
thanks @aatif24. At the moment we do not support individual colours for the `BarList`. I like the idea though!

**Comment by ehowey** [comment]
+1 for this idea! I was trying to hack this in myself with some fancy CSS selectors!

**Comment by Wake-Up-Donnie** [comment]
+1 I agree this would be great!
