### ISSUE TITLE
Feature request: Expose Recharts / d3-shape interpolation

### ISSUE THREAD

**Issue by dani-z** [tremorlabs/tremor-npm#399]
Hey all, 

Thanks for creating this awesome lib! I was looking into implementing some line and area charts and I was amazed by how simple this is using Tremor.

One small request from my side, would it be possible to export Rechart's interpolation types so we can get smooth points in area and line charts? 
```
[type](https://recharts.org/en-US/api/Area#type)'basis' | 'basisClosed' | 'basisOpen' | 'linear' | 'linearClosed' | 'natural' | 'monotoneX' | 'monotoneY' | 'monotone' | 'step' | 'stepBefore' | 'stepAfter' | Function
```

Is this something you have in mind? I would be more than happy to help with this if needed.

Best,

**Comment by jnsdrssn** [comment]
I second this. Would be super cool!

**Comment by mitrotasios** [comment]
@dani-z sure, feel free to open up a PR if you like!

**Comment by dani-z** [comment]
Sure thing, opened @mitrotasios

**Comment by mitrotasios** [comment]
thanks @dani-z, will look into it!
