### ISSUE TITLE
Unexpected shadow when creating a table

### ISSUE THREAD

**Issue by oldsokkett** [tremorlabs/tremor-npm#402]
Hello!
That's the code i've used (it's from your site docs)
```
<MultiSelectBox
        onValueChange={(value) => setSelectedNames(value)}
        placeholder="Выберите школу..."
        className="max-w-xs"
      >
        {salesPeople.map((item) => (
          <MultiSelectBoxItem
            key={item.name}
            value={item.name}
            text={item.name}
          />
        ))}
      </MultiSelectBox>
      <Table className="mt-6">
        <TableHead>
          <TableRow>
            <TableHeaderCell>Name</TableHeaderCell>
            <TableHeaderCell className="text-right">Leads</TableHeaderCell>
            <TableHeaderCell className="text-right">Sales ($)</TableHeaderCell>
            <TableHeaderCell className="text-right">Quota ($)</TableHeaderCell>
            <TableHeaderCell className="text-right">Variance</TableHeaderCell>
            <TableHeaderCell className="text-right">Region</TableHeaderCell>
            <TableHeaderCell className="text-right">Status</TableHeaderCell>
          </TableRow>
        </TableHead>

        <TableBody>
          {salesPeople
            .filter((item) => isSalesPersonSelected(item))
            .map((item) => (
              <TableRow key={item.name}>
                <TableCell>{item.name}</TableCell>
                <TableCell className="text-right">{item.leads}</TableCell>
                <TableCell className="text-right">{item.sales}</TableCell>
                <TableCell className="text-right">{item.quota}</TableCell>
                <TableCell className="text-right">{item.variance}</TableCell>
                <TableCell className="text-right">{item.region}</TableCell>
                <TableCell className="text-right">
                  <BadgeDelta deltaType={item.deltaType} size="xs">
                    {item.status}
                  </BadgeDelta>
                </TableCell>
              </TableRow>
            ))}
        </TableBody>
      </Table>
```
So, i see this behavior
![Screenshot 2023-04-17 at 23 17 29](https://user-images.githubusercontent.com/64016123/232600478-7d674c5f-10d4-4348-974b-b6ed19ee7718.png)

![Screenshot 2023-04-17 at 23 18 10](https://user-images.githubusercontent.com/64016123/232600628-1f812dd4-c3dd-42a8-a4f9-8066624c27a3.png)

and i cannot remove this shadow

**Comment by severinlandolt** [comment]
Heya @soKKett! I could **not** replicate the exact problem: 
<img width="779" alt="CleanShot 2023-04-18 at 01 25 48@2x" src="https://user-images.githubusercontent.com/41927988/232631892-af4fab06-7ad6-460d-90a6-ba5aa6c9b66c.png">

Could you tell me which version of Tremor and Nextjs(?) you are using?

**Comment by oldsokkett** [comment]
I'm using nextjs 13 (not /app dir)

**Comment by severinlandolt** [comment]
@soKKett Hi Gleb, I just wanted to follow up and ask, if you found a solution for your shadow issue?

**Comment by oldsokkett** [comment]
> @soKKett Hi Gleb, I just wanted to follow up and ask, if you found a solution for your shadow issue?

Hi! I had already stopped using this library, and I vaguely remember whether the problem fixed itself or whether I just put up with it. Thanks for reminding me, I'll try to reproduce this problem soon in my old repositories where I was still using tremor.
