### ISSUE TITLE
Feature Request: Legend for Donut Chart

### ISSUE THREAD

**Issue by TaylorFacen** [tremorlabs/tremor-npm#414]
It would be great if there was a legend for the donut chart or if the chart displayed the categories without the user having to hover.

**Comment by christopherkindl** [comment]
Hi @TaylorFacen,

thanks for using our library! You can use the <Legend/> component for this case. See the examples on tremor.so/blocks/landing-zone

Let us know if you have any other feedback to share!

**Comment by TaylorFacen** [comment]
Oh thanks! I wasn't sure how the legend would know to use the same default colors as the donut chart.
