### ISSUE TITLE
Documentation misleading for Next.js Tailwind CSS configuration

### ISSUE THREAD

**Issue by xyspg** [tremorlabs/tremor-npm#415]
**Describe the issue**
The current Getting Started guide for setting up a Next.js project with Tremor may lead to confusion when using the `src` or `app` directory structure. The guide does not mention updating the `tailwind.config.js` file to include the correct paths for components and pages within the `src` or `app` directory.
<img width="936" alt="CleanShot 2023-04-22 at 13 31 53@2x" src="https://user-images.githubusercontent.com/42668274/233764781-ad665409-6e6f-41c1-9652-10fd6dbe9d88.png">
```
// if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
```
**Proposed change**
Update the Getting Started guide with clear instructions on how to update the `tailwind.config.js` file for projects using the `src` or `app` directory structure. Provide an example of the updated `tailwind.config.js` file with the correct paths.

**Additional context**
Users who follow the current guide may face issues with their Tailwind CSS setup if they use the `src` or `app` directory structure in their Next.js projects. This issue can be resolved by updating the documentation to provide clear instructions on how to configure the `tailwind.config.js` file for these directory structures.

**Comment by mitrotasios** [comment]
hey @xyspg, thanks for the suggestion, we'll try to make it more clear.

**Comment by severinlandolt** [comment]
We adjusted our documentation, hope it helps!
