### ISSUE TITLE
How to reverse x-axis in line/bar charts

### ISSUE THREAD

**Issue by MaskedCoconut** [tremorlabs/tremor-npm#431]
Hello,
I could not find it in the documentation nor the API but I would need to reverse an axis for a graph, any pointers to what I should do?
It seems that I may need to change my source data object's properties order but that sounds a bit exotic so I must be missing something, am I?

**Comment by mitrotasios** [comment]
hey, could you pls elaborate a bit more what you would like to achieve? 🙂

**Comment by MaskedCoconut** [comment]
Sorry for the trouble I found the solution.
To invert x-axis, simply apply Array.reverse() to the chartdata array!

**Comment by mitrotasios** [comment]
no problem!
