### ISSUE TITLE
Feature request: Add in a 'No data' message to components

### ISSUE THREAD

**Issue by adamjdavies** [tremorlabs/tremor-npm#432]
### Discussed in https://github.com/tremorlabs/tremor/discussions/403

<div type='discussions-op-text'>

<sup>Originally posted by **adamjdavies** April 18, 2023</sup>
Hi all, 

Firstly, big props to the Tremor team on what they've created. I've been able to whip up a nice little dashboard in under an hour. 

One question I did have was if there is an easy way to add a message like 'No data' to a chart? The data powering my dashboard is based on a specific time interval and there may be times where no data exists for that time period. I would love to be able to add in message directly on the chart saying 'no data available' or something similar. 

I can obviously go in and create some conditional UI to show this myself, but just wondered if there was an easier way to do it directly in the chart component. 

Thanks!</div>

--
**What is the problem you're trying to solve?**

Currently, when the data feeding a chart (or other component) is empty/null, Tremor does not provide any message indicating that there is no data to display. This can be confusing to users who are expecting to see data in the chart, but instead see an empty space.

**What solution would you like to see?**

I would like to request that Tremor add a "No Data" message to components when the data feeding them is empty/null. This message should be displayed in the component's space and should inform the user that there is no data available to display.

**Comment by mitrotasios** [comment]
Thanks @adamjdavies! We'll try to tackle this soon.
