### ISSUE TITLE
Styling does not seem to be working for me

### ISSUE THREAD

**Issue by Socvest** [tremorlabs/tremor-npm#433]
I just stumbled on this package and think it is clean and nice. Wanted to get started on it though the styling does not seem to be working for me. I am currently testing it in a codesandbox and have seen other codesandbox examples though they employ later versions which allows them to use the imported css file. Though when I attempt to upgrade it to the latest version the imported css file springs an error. 

I have also tried importing these into my global.css file to no avail. 
``` 
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Would really like some help on how to get this working. 

[Codesandbox](https://codesandbox.io/s/young-pine-tffhek?file=/src/App.tsx) for my example. 

Thanks

**Comment by severinlandolt** [comment]
Hey @Socvest, you are missing the correct tailwind setup, notably a `tailwind.config.js` file. Make sure you have installed/added all the relevant dependencies for Tailwind as well (Postcss, autoprefixer, tailwint init). You can read it up here:

https://www.tremor.so/docs/getting-started/installation

**Comment by severinlandolt** [comment]
@Socvest Did it work out for you?
