### ISSUE TITLE
Support for mixed units in line/bar chart

### ISSUE THREAD

**Issue by MaskedCoconut** [tremorlabs/tremor-npm#434]
Hello, I have a case where I want to show km (kilometers) and km/hours on a (line or bar) graph.
The issue is to show the units properly. 

It seems that I cannot discriminate by category in my valueFormatter.

Any tips? For now I put the units in category name and I don't display any units in valueFormatter.
Is there plan for support of secondary Y axis?

**Comment by severinlandolt** [comment]
Hey @MaskedCoconut, thank you for reaching out. This issue is connected to https://github.com/tremorlabs/tremor/issues/233, I will give an update there once we decided in what direction we want to the secondary axis topic.

**Comment by MaskedCoconut** [comment]
thanks
