### ISSUE TITLE
docs: Unexisting props for AreaChart in docs

### ISSUE THREAD

**Issue by andrsdt** [tremorlabs/tremor-npm#436]
[Docs](https://www.tremor.so/docs/components/area-chart) for the `<AreaChart/>` component indicate that we can assign the value `basis` for the new `curveType` prop:

| curveType   | optional                             |
|-------------|--------------------------------------|
| Description | Controls the type of the chart curve |
| Type        | string                               |
| Default     | `linear`                               |
| Values      | `basis, linear, step`                  |

However, there must be a typo either with the docs or with the Typescript declarations, because `basis` does not exist in the `CurveType` type:

```typescript
// index.d.ts

type CurveType = "linear" | "natural" | "step"; // <-- Where is "basis"? We have "natural" instead

// (...)

interface AreaChartProps extends BaseChartProps {
    stack?: boolean;
    curveType?: CurveType;
    connectNulls?: boolean;
}
```

This happens in the latest release as of today, `"@tremor/react": "^2.4.0"`. Thanks.

**Comment by mitrotasios** [comment]
good catch, thanks for submitting! Will fix.
