### ISSUE TITLE
Feature request: Expose component types

### ISSUE THREAD

**Issue by amirhhashemi** [tremorlabs/tremor-npm#438]
Currently if I want to extend one of your components, let's say `TextInput`, I have to copy `TextInputProps` type from your code.

It would be nice if we had access to the component types. It would make it easier to extend your components with typescript.

I my case, I want to create `FormTextInput` component that extends `TextInput` and adds some `react-hook-form` builerplates. It's a very important component because I have a lot of forms. It should accept all the props of `TextInput` and that's why I need `TextInputProps`.

**Comment by shaunsaker** [comment]
Hey @amirhhashemi! FYI I was looking for the same thing but found a workaround that might help you :)

```
import { TextInput  } from '@tremor/react'
import React, { ComponentProps } from 'react'

type TextInputProps = ComponentProps<typeof TextInput>
```

**Comment by amirhhashemi** [comment]
Hey @shaunsaker. Thanks for the response.

I've already tried it but it doesn't work:
```tsx
const props = {} as TextInputProps
// props = contextTypes | defaultProps | displayName | propTypes
```
