### ISSUE TITLE
[feature request]: Allow key events on line chart

### ISSUE THREAD

**Issue by thiskevinwang** [tremorlabs/tremor-npm#443]
<sub>First of all, amazing project here ❤️ . </sub>

### Feature Request

As a user of `LineChart` or `AreaChart`, it would be nice to have the ability to _annotate_ the chart with "key chronological events"

For inspiration, here's a screenshot of Vercel speed insights

<img width="882" alt="CleanShot 2023-05-09 at 21 35 13@2x" src="https://github.com/tremorlabs/tremor/assets/26389321/9c8fa2e1-729f-424c-aa0c-c85b513b06b7">

**Comment by severinlandolt** [comment]
Hey @thiskevinwang, Thanks for your submission. There are some things to consider. In the example you posted, the event gets added to the legend. I am not sure if this pattern is generalizable. Let's say you have three different lines and three different types of events? The legend would then have three colors for the lines and three patterns for the different events? How do you distinguish different events? Dotted, dashed, and ?. What when you have 4 events?

Maybe allow one event only?

Would be interested to hear more about your use case for that? Happy to have a call as well.

**Comment by thiskevinwang** [comment]
Current use case (very similar to the screenshot): I'm tracking a metric over time (daily application build times) and I want to be able to correlate any changes in trends with key events (code changes, infra changes, etc.)

---

> In the example you posted, the event gets added to the legend.
>
> Maybe allow one event only?

I think one "type" of event seems reasonable as it would be nice to annotate a chart multiple times with this single "type".
My thinking is:
- One legend pattern
  - This implies there's only 1 event type. (ex. pull request merged)
  - It's up to the end user to decide what to name this "bucket" of events.
- You can add multiple events to the chart. (visually this would be multiple vertical dashed lines)
- Would also be nice to have a tooltip show when hovering an event

(Another screenshot displaying multiple events)

![CleanShot 2023-05-11 at 08 56 16@2x](https://github.com/tremorlabs/tremor/assets/26389321/bdc5bfd1-ba64-49f3-8394-491e8a6a80aa)

**Comment by severinlandolt** [comment]
Thank you for your thorough follow-up! Will take this into the next discussion.

**Comment by lacymorrow** [comment]
This is something preventing us from using the library in production.
Annotating event ranges would be amazing:
![image](https://github.com/tremorlabs/tremor/assets/1311301/2b3e8634-c988-479b-8ac9-d079effd0bb6)

**Comment by christopherkindl** [comment]
Thanks @lacymorrow, we are already reworking our charts and consider to integrate such features.

**Comment by lacymorrow** [comment]
Some "nice-to-haves" would be:
- Events marking (single line) or ranges (box/gradient)
- Hovering event shows a popover similar to hovering the graph with X details
- Clicking an item in the legend toggles the item visibility in the graph
- clicking and dragging to "zoom and crop" into the map ([example](https://apexcharts.com/javascript-chart-demos/line-charts/zoomable-timeseries/))

**Comment by severinlandolt** [comment]
Hey @thiskevinwang, Thanks for your idea to add "key chronological events" annotations. While it's a compelling feature, we're cautious about adding complexity to the charting components. The challenge of effectively representing multiple event types and maintaining a clean user interface leads us to hold off on this addition for now. I will keep this marked as a feature → might be picked up in the future. We appreciate your input and encourage you to keep the great suggestions coming!

**Comment by gsilvan** [comment]
This feature would be really helpful.
