### ISSUE TITLE
Feature request: Checkbox component

### ISSUE THREAD

**Issue by amirhhashemi** [tremorlabs/tremor-npm#456]
A Checkbox component would be great. In my recent app I needed a checkbox for a few things:

- In the login page, there is a "Remember me" checkbox that if checked, makes the login session last longer.
- To on/off some user account settings
- I have a chart which shows a list of categories and the user can select/unselect the categories. In my case, it didn't make sense to use the `MultiSelectBox` component to show all the available categories, so I show them in a grid with a checkbox that toggles that category.

You can argue that all of them can be achieved with the `Toggle` component, but I think having a traditional `Checkbox` is a good thing because it takes less space and it's simpler. Also the value of Toggle can only be string but sometimes a boolean is needed.

I'm willing to prepare a PR for this, just let me know.

**Comment by severinlandolt** [comment]
Hey there @amirhhashemi! We won't be adding a Checkbox component anytime soon. **However**: We recently launched Tremor Raw, a copy & paste library for React components. Here we have a [Checkbox](https://raw.tremor.so/docs/inputs/checkbox) component. Happy coding! ⌨️
