### ISSUE TITLE
improvement: provide a failsafe enumeration of icon sizes

### ISSUE THREAD

**Issue by erikarenhill** [tremorlabs/tremor-npm#457]
if providing an invalid value to the size property of the Icon component, there will be an error thrown that paddingX can not be read.

I strongly believe it a better way is to do an console.error and log the error with the valid values instead with a failover to avoid crashing.

**Comment by amirhhashemi** [comment]
Typescript is exactly for that.

The `console.error` you mentioned requires runtime checks which:
1. Increases the complexity of the code. A lot of `if` statements are required
2. Might increase the bundle size
3. Might have a tiny effect on the performance. Even though it's probably negligible, I personally don't see enough reasons to implement such a thing. It feels like re-creating Typescript to me.

They provide Typescript types exactly for this problem. If you pass an invalid value Typescript gives you a nice error. Also you can see all the valid values in you editor.

Please correct me if I'm wrong.

**Comment by erikarenhill** [comment]
> Typescript is exactly for that.
> 
> The `console.error` you mentioned requires runtime checks which:
> 
> 1. Increases the complexity of the code. A lot of `if` statements are required
> 2. Might increase the bundle size
> 3. Might have a tiny effect on the performance. Even though it's probably negligible, I personally don't see enough reasons to implement such a thing. It feels like re-creating Typescript to me.
> 
> They provide Typescript types exactly for this problem. If you pass an invalid value Typescript gives you a nice error. Also you can see all the valid values in you editor.
> 
> Please correct me if I'm wrong.

generally I would agree, but I also think a library should not set the conditions for whether consumers of it should use typescript or not. Normally you'd use PropTypes for these kind of checks which means InferProps for example could be used in cases where a library want to give both worlds a good developer experience without having to duplicate all the definitions, even with libraries written in typescript.

Also it's not uncommon to generate user-interfaces dynamically where typescript would not be able to catch these errors in runtime.

So for your arguments about performance and increased bundle-size and complexity they could all be avoided this way.
PropType checks are excluded in production builds, and it does not require any logic either as it's taken care of for you.

My suggestion was a bit vague and incorrectly written in a stressful way so I understand it could be misinterpreted as a bad solution. I should have taken time to write a suggestion about introducing InferProps from the beginning

**Comment by severinlandolt** [comment]
Thank you for bringing this up and the discussion. In my view, the typescript hints will be sufficient, hence I will close this issue. Thank's all for being active in the community!
