### ISSUE TITLE
Error when try to use "ProgressBar" component

### ISSUE THREAD

**Issue by Toledodev** [tremorlabs/tremor-npm#464]
When we try to use this component we are having the following error:

![image](https://github.com/tremorlabs/tremor/assets/87545086/ddec6e15-755d-40c1-b094-3e960d592e62)

I already fix this issue so I will open a pr to this

**Comment by mitrotasios** [comment]
@Toledodev thanks, feel free to open the PR. What is the bug being caused by?

**Comment by Toledodev** [comment]
Hey @mitrotasios , I checked now and this is a duplicate of this issue https://github.com/tremorlabs/tremor/issues/387
