### ISSUE TITLE
Irregular timed data in line charts?

### ISSUE THREAD

**Issue by OfficialCRUGG** [tremorlabs/tremor-npm#467]
Hey there,

are the line charts in this library able to handle irregularly timed data?

So for example if my data set looks like this:

0 | 15:00
1 | 15:30
2 | 16:00
3 | 17:00

The spacing between 2 & 3 should be double what it is for the others. Is this somehow possible?

**Comment by mitrotasios** [comment]
hi @OfficialCRUGG, currently you have to manage this yourself unfortunately. We may add some time intelligence functionality in the future.
