### ISSUE TITLE
Compatibility with Qwik

### ISSUE THREAD

**Issue by carlosfernandezcabrero** [tremorlabs/tremor-npm#469]
Hello,

I’m interest in know if Tremor have compatibility with new Framework Qwik.

Regards thank you very much

**Comment by amirhhashemi** [comment]
Qwik supports both React and Tailwindcss, so Tremor should work there without any problem.

The only thing is that some Tremor components have `"use client"` at the beginning of their files to make them compatible with Next.js 13. If that's not a problem I think you are good to go! (disclaimer: I haven't worked with Qwik in a long time and I'm not up-to-date with Qwik's React compatibility status)

**Comment by mitrotasios** [comment]
Closing as covered by @amirhhashemi 🙏
