### ISSUE TITLE
Partial donut or pie chart

### ISSUE THREAD

**Issue by mastoj** [tremorlabs/tremor-npm#474]
I can't see there is a way to generate a partial donut/pie chart. I think a donut would be nice to use as a "gauge" where I could give some values and a max value and the donut would only be partially filled based on how many percentage the values cover based on the max value.

**Comment by mitrotasios** [comment]
Sounds good, we will consider this!

**Comment by severinlandolt** [comment]
Thanks a lot for your suggestion to improve the donut chart component. It's an interesting idea, but currently, we're prioritizing features with broader use cases.
