### ISSUE TITLE
Feature request: Spinner component

### ISSUE THREAD

**Issue by amirhhashemi** [tremorlabs/tremor-npm#477]
`<Button>` in its "loading" state shows a spinner instead of its icon. I needed the same spinner in my app and I had to copy it from you code. I would be great if we had access to that spinner as standalone component.

I would be more than happy to add this component in a PR, but I need your approval first.

**Comment by mitrotasios** [comment]
Thanks for the suggestion but I think this would be out of scope for the library at the moment 🙂
