### ISSUE TITLE
Line chart out of chart

### ISSUE THREAD

**Issue by santgr11** [tremorlabs/tremor-npm#478]
I'm having this issue with my chart used to compare two different values, one of the lines is going out of the graphic.

I'm using next.js 13

The component's code:
```javascript
export default async function SalariesChart({ salariesInfo }) {
  if (!salariesInfo || salariesInfo.length < 1)
    return <div className="text-error">Nada para mostrar</div>;

  salariesInfo = salariesInfo.reverse();
  return (
    <div className="mx-3">
      <Card className="bg-base-300 ring-base-300">
        <Title className="text-accent-content">
          Sueldos vs Ajustado por inflación
        </Title>
        <LineChart
          data={salariesInfo}
          index="fecha"
          categories={['sueldoARS', 'ajustado']}
          colors={['green', 'rose']}
          curveType="steps"
          className="bg-base-100"
          maxValue={Math.max(salariesInfo.map(s => s.ajustado))}
        />
      </Card>
    </div>
  );
}
```

![image](https://github.com/tremorlabs/tremor/assets/38112957/8307e85f-47be-4d2d-a69e-0fd8948bdfe9)
![image](https://github.com/tremorlabs/tremor/assets/38112957/cb994f38-06a7-4516-be66-b893bd6ac470)

I guess it is using the green line to build the scale, but it should use the biggest one.

Any advice on how to fix this?

**Comment by santgr11** [comment]
I kept searching for similar previous issues and found this happens when the data is parsed as a string, I was changing it to a string when using toFixed, so I fixed it parsing back to a number.

**Comment by severinlandolt** [comment]
Thank you for the hint, this happens quite often. I will make a hint in the documentation.  Happy coding!
