### ISSUE TITLE
Feature request: polymorphic components (`as` prop)

### ISSUE THREAD

**Issue by amirhhashemi** [tremorlabs/tremor-npm#479]
In my app I have links that should look like a button. Corrently I have to copy `<Button>` styles from your code and do the navigation manually:
```tsx
import Router from "next/router"

<Button onClick={() => Router.push("/")} className="...">Link</Button>
```
But if we could change the element that `Button` renders , it would be way simpler:
```tsx
import Link from "next/link"

<Button as={Link} href="/">Link</Button>
```
My app is a monitoring tool that will be available to a handful of companies but we have a few public pages that we use for marketing. I use Tremor on those pages too because I want to keep the UI consistant. SEO is very important on those pages and using a `<button>` for navigation is not recommanded. I know Tremor is focused on admin panels but every admin panel could have a few public pages that SEO matters for them.

My proposal is to make some components polymorphic. Or in another words, provide a way to change the underlying element that those components render. Most component libraries have this feature. Add a prop named `as` or `component` that can accept the name of an HTML element (like "span" or "a") or a another component (like `Link` in the example above) and use that instead of the default element that the component renders. 

- https://react-typescript-cheatsheet.netlify.app/docs/advanced/patterns_by_usecase/#polymorphic-components-eg-with-as-props
- https://gist.github.com/amirhhashemi/9e4d5313543baadec1f8f9762249eac1

The components that I think this feature could be useful for them:
- Button
- Badge
- Icon

I would be more than happy to do it myself, but I want to know your opinion first.

**Comment by mitrotasios** [comment]
I think that makes sense, feel free to implement!

**Comment by amirhhashemi** [comment]
I tried to implement it a few days ago but due to a Typescript limitation I had to convert all `interface`s to `type`s. For example `export interface ButtonProps` becomes `export type ButtonProps`. This is a breaking change because `interface` and `type` have different features and limitations. 

So this approach is not applicable unless you are ok with the breaking change.

**Comment by severinlandolt** [comment]
Thank amirhhashemi you for the hint. We think due do reason you mentioned, polymorphism wont be something we well implement anytime soon. I will keep the Feature label if we might get back to this. Thank you for being an active part of this community!
