### ISSUE TITLE
Feature Request: Different colors on non-grouped bar charts

### ISSUE THREAD

**Issue by rebasedming** [tremorlabs/tremor-npm#487]
### What problem does this feature solve?

Allow different colors to be used for bars in bar charts when there is no grouped data.

### What does the proposed API look like?

Currently if you have a bar chart with no grouped data and pass in `colors=["red", "blue", "green"]`, only the first color takes effect and the rest are ignored. I would like my bar chart to cycle through these colors for each bar.

**Comment by mitrotasios** [comment]
This is a bit counter-intuitive to the way things work at the moment where each color maps to one category, so it is tricky to implement for now. We will take this into account in the future however, when we plan to allow overriding colors on a component level.

**Comment by severinlandolt** [comment]
Hey! I see your point. As mentioned, this would mean a big change in how our charts work. For your case, check out our copy & paste charts at http://tremor.so/charts and add this feature yourself. Happy coding!
