### ISSUE TITLE
[Feature]: allow custom display text and placeholder in MultiSelectBox

### ISSUE THREAD

**Issue by vitorsavedra** [tremorlabs/tremor-npm#491]
### What problem does this feature solve?

In `MultiSelectBox` component not is possible to define/customize display text of selected values or placeholder in search field. Example:

![image](https://github.com/tremorlabs/tremor/assets/4504831/589b3a3e-7525-4561-aa9a-d3b71379f9d7)

However, there are cases where other nomenclatures may make sense for users or even for language reasons.

### What does the proposed API look like?

Adding new props on component:

```js
const MultiSelectBox = React.forwardRef<HTMLDivElement, MultiSelectBoxProps>((props, ref) => {
  const {
    // [...]
    selectedDisplayText = "Selected",
    searchPlaceholder = "Search",
    ...other
} = props;
```

Using this when defined:

```js
const displayText = hasSelection ? `${selectedItems.length} ${selectedDisplayText}` : placeholder;
```

```js
<input
  name="search"
  type="input"
  placeholder={searchPlaceholder}
  // [...]
/>
```

**Comment by MuhammadAakash** [comment]
Hi, @mitrotasios I would like to work on this issue too.

**Comment by mitrotasios** [comment]
sure, we haven't tackled this problem yet because we'd like something like this ideally:
<img width="401" alt="image" src="https://github.com/tremorlabs/tremor/assets/58337217/386bda9e-c23a-4368-bea5-1df7c5e8e820">
Source: https://retool.com/components/multiselect

I wouldn't tackle this before the v3 release though because we are migrating our select elements to headlessui. But feel free to take this on afterwards :)

**Comment by MuhammadAakash** [comment]
Sure @mitrotasios . I will start working on this as you described.

**Comment by MuhammadAakash** [comment]
I apologize for the delay. I have been quite busy lately.
@mitrotasios, could you please confirm the props that I need to add to the component?

**Comment by pbaveja** [comment]
@MuhammadAakash Hey, are you still working on a PR for this?

**Comment by MuhammadAakash** [comment]
@pbaveja Yeah I need some assistance here from Tremor team.
And then will made the PR.

**Comment by pbaveja** [comment]
@MuhammadAakash  Okay sounds good. Since you're working on it already. I wanted to know how you would suggest overriding this component in a custom file in my project?

**Comment by severinlandolt** [comment]
Merged and there is also a new placeholerSearch prop :)
