### ISSUE TITLE
[Feature]: Change order of label / value in tooltips

### ISSUE THREAD

**Issue by njbmartin** [tremorlabs/tremor-npm#492]
### What problem does this feature solve?

![image](https://github.com/tremorlabs/tremor/assets/5699471/376011d2-e863-4f41-bced-1ea6bd547bb1)

The current tooltip can be difficult to read. When reading from left to right, your eyes see the value before you know what the value is referring to. So your brain goes "heres a value, what is it for? It's for active subscriptions. Ok, so wait, what was the value again?" Repeat. vs "active subscribers is x"

### What does the proposed API look like?

Introduce a prop called `tooltip` to allow customisation, and use `labelFirst: boolean` to switch the ordering.

```jsx
<LineChart
        className="mt-6"
        autoMinValue={true}
        data={tremorData}
        index="date"
        categories={[
          'Active subscribers',
          'Active subscriptions',
          'Active products (subscription lines)',
        ]}
        curveType="linear"
        tooltip={{ labelFirst: true }}
      />
```

**Comment by MuhammadAakash** [comment]
Hi @njbmartin , I would like to work on this issue.

**Comment by severinlandolt** [comment]
Heya! Thanks for the thorough description. This sound like a reasonable change to me, will take this to the team.

**Comment by mitrotasios** [comment]
@MuhammadAakash feel free to take this. We think its better to not add a new prop but just to reverse the values as suggested by @njbmartin.

**Comment by MuhammadAakash** [comment]
Sure @mitrotasios . Thanks, will start working on it.

**Comment by MuhammadAakash** [comment]
@mitrotasios Can you please confirm whether I should move the dot, which is currently positioned on the left side of the number, to the right side after reversing the position of the label and value? Or should I leave it as it is right now?
