### ISSUE TITLE
[Docs]: Typo in the example code for BarList component

### ISSUE THREAD

**Issue by aidoskanapyanov** [tremorlabs/tremor-npm#495]
### Tremor Version

latest

### Link to minimal reproduction

none

### Steps to reproduce

When you visit the [docs](https://www.tremor.so/docs/components/barlist) for the BarList component, there is a small typo in the codeblock under the "Usage example BarList" section. It's written `GoogleIcon` when it should be `TwitterIcon`.

P.s. awesome project btw!

<img width="353" alt="image" src="https://github.com/tremorlabs/tremor/assets/65722512/c39f549b-7ed8-4fb1-8caf-a6d9c29909e1">

### What is expected?

The icon is expected to be named `TwitterIcon`.

### What is actually happening?

Right now the icon is named `GoogleIcon`.

**Comment by severinlandolt** [comment]
Thank you for the hint, will be fixed with updated docs soon!

**Comment by MuhammadAakash** [comment]
Hi @severinlandolt. 
I believe I can be helpful here. Could you please provide instructions on how to set up the project?

**Comment by severinlandolt** [comment]
Heya, thank you for reaching out! Your assumption of "only the team members might be working on the issues" is correct. We are currently working on our v3 release with lots of breaking changes and ongoing discussions. In light of this, it's hard to assign any issues just yet. Once we are out with V3 (soon) we have more capacity delegate issues. We will have an updated issues list after our release, this will give us (and you) much more insight on how/where to contribute.

**Comment by MuhammadAakash** [comment]
Sure @severinlandolt .
