### ISSUE TITLE
Any way to support you?

### ISSUE THREAD

**Issue by angelhodar** [tremorlabs/tremor-npm#497]
Hi guys! I have been a bit out of the tremor journey (still on v1.8.0 hahaha). This week I will probably update to v2 and I was just wondering if you have any paypal so I can support you, or some sponsor. Sadly I cant help by making PRs because I am very busy, so I would like to support you in another way. How is the project going? Is v3 soon? Should I wait for it before update? :)

**Comment by mitrotasios** [comment]
hey @angelhodar, thanks for reaching out! Feel free to join our slack so we can talk about contributing if you're interested :) Yup, v3 is coming out this week!
