### ISSUE TITLE
[Feature]: New tabs api can't replace all Toggle usecases

### ISSUE THREAD

**Issue by juanmarin-co** [tremorlabs/tremor-npm#504]
### What problem does this feature solve?

Hi! Thank you all for this fantastic project!

I'm currently using tremor 2 and Toggle to render a component similar to this one:

![image](https://github.com/tremorlabs/tremor/assets/13415603/5894ad75-dfc1-425b-b8fd-03a3e8f053f5)

But instead of loading all the content of the card at once, I'm using a router to load the content depending on the selected ToggleItem, something like this:

```jsx
<Toggle
  value={currentPath}
  onValueChange={(value) => {
    navigate(`.${value}`);
  }}
>
  <ToggleItem value="/shipments" text="Shipments" />
  <ToggleItem value="/movements" text="Movements" />
</Toggle>

<Outlet />
```

But the new Tabs API can't support this navigation pattern as the content switch is being handled automatically based on the tab's index.

I would love to migrate to tremor 3, but this blocks me. Is there a way to enable this pattern?

**Comment by mitrotasios** [comment]
Hi! We are thinking of a way to also allow values (i.e. string values) for the tabs. The reason the API changed is that we use headlessui under the hood now which uses indexes. 
In the meantime I would suggest the work around of mapping the indexes to your routes or just using an array. Something like:

```
const routes = ['shipments', 'movements']

...

onIndexChange={(index)=>{
  navigate(`.${routes[index]}`);
}}
```

**Comment by juanmarin-co** [comment]
But how TabPanels should be created? Do I have to create multiple TabPanel?

**Comment by mitrotasios** [comment]
`TabPanels` are not mandatory if you don't need them. You can just use `TabGroup` and `TabList`.

**Comment by juanmarin-co** [comment]
@mitrotasios you're right, thanks! Should I close this issue or do you want to use it to track the development of non-numeric values for tabs?
