### ISSUE TITLE
[Bug]: Pie-charts in v3 has weird looking gaps

### ISSUE THREAD

**Issue by erikarenhill** [tremorlabs/tremor-npm#506]
### Tremor Version

3

### Link to minimal reproduction

N/A

### Steps to reproduce

Create a pie chart.

### What is expected?

A pie chart that looks something like this (screenshot taken with v2), nice even and straight gaps between the different sections

![image](https://github.com/tremorlabs/tremor/assets/758402/99db463d-e12e-48a5-9c1a-0c3a86a8d0cc)

### What is actually happening?

The gaps is not looking good in v3

![image](https://github.com/tremorlabs/tremor/assets/758402/91ad4453-5962-4f96-b436-ea8682b3f17f)

### What browsers are you seeing the problem on?

Chrome

### Any additional comments?

Could not create a codesandbox for it as v2.1 is latest tremor available there.

**Comment by severinlandolt** [comment]
#509
