### ISSUE TITLE
[Feature]: Add "enableYearPagination" to the DateRangePicker

### ISSUE THREAD

**Issue by severinlandolt** [tremorlabs/tremor-npm#510]
### What problem does this feature solve?

Currently, the [DateRangePicker](https://github.com/tremorlabs/tremor/tree/main/src/components/input-elements/DateRangePicker) is missing the feature to sift through years quickly.

Adding year pagination, helps users to skip through years, not only months as it's currently the case. 

### What does the proposed API look like?

```diff
export interface DateRangePickerProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, "value" | "defaultValue"> {
  value?: DateRangePickerValue;
  defaultValue?: DateRangePickerValue;
  onValueChange?: (value: DateRangePickerValue) => void;
  enableSelect?: boolean;
  minDate?: Date;
  maxDate?: Date;
  placeholder?: string;
  selectPlaceholder?: string;
  disabled?: boolean;
  color?: Color;
  locale?: Locale;
  enableClear?: boolean;
+ enableYearPagination?: boolean
  children?: React.ReactElement[] | React.ReactElement;
}
````

![CleanShot 2023-06-09 at 14 26 39@2x](https://github.com/tremorlabs/tremor/assets/41927988/019abb6c-9e72-404d-a4fd-15f4b59b71a9)

**Comment by jorgeramirezamora** [comment]
I can take this one 🤚

**Comment by frozenBranch** [comment]
This would be great

**Comment by severinlandolt** [comment]
Hey @jorgeramirezamora, I wanted to just check, if you are still working on this issue?
