### ISSUE TITLE
[Feature]: Add pagination to Table component

### ISSUE THREAD

**Issue by qurashiakeel** [tremorlabs/tremor-npm#512]
### What problem does this feature solve?

The pagination feature is really important for the table component, most of the times we have hundreds of items which can't be shown in single page and it if we need to handle it manually that messes up the code. It would be awesome to have the built in pagination feature.

**Comment by severinlandolt** [comment]
This is a duplicate of #283

**Comment by Iqueal** [comment]
So where is the pagination?
