### ISSUE TITLE
[Bug]: Theming won't apply to ProgressBar component in v3.1.0

### ISSUE THREAD

**Issue by vishalkdotcom** [tremorlabs/tremor-npm#522]
### Tremor Version

3.1.0

### Link to minimal reproduction

https://github.com/vishalkdotcom/progressbar-theme-bug-repro

### Steps to reproduce

Just follow the official installation (Next.js) and theming guide. And don't provide the `color` attribute to `ProgressBar`.
You can also check the github repo to reproduce this issue.

Installation
https://www.tremor.so/docs/getting-started/installation

Theming
https://www.tremor.so/docs/getting-started/theming

### What is expected?

ProgressBar colors should change as per the brand colors in `tailwind.config.js`

### What is actually happening?

ProgressBar colors remain blue

### Any additional comments?

If you try the [repro example](https://github.com/vishalkdotcom/progressbar-theme-bug-repro) I provided, the theming works on Badge component but not on ProgressBar.

I believe this issue occurs because there is a default color passed during props destructuring at line [#23](https://github.com/tremorlabs/tremor/blob/main/src/components/vis-elements/ProgressBar/ProgressBar.tsx#L23).

**Comment by vishalkdotcom** [comment]
I spent a lot of time today in debugging this. I was thinking the issue is at my end (pnpm, npm or stale packages etc). 😅

This issue could exist in other components as well. But I didn't get time to check.

**Comment by severinlandolt** [comment]
Hi! There is an issue on our end. We are working on it!

**Comment by severinlandolt** [comment]
Should work now: `npm i @tremor/react@latest`

**Comment by vishalkdotcom** [comment]
@severinlandolt
Thanks a lot, not only for this specifc bugfix, but for all the amazing work being done on this brilliant library.

**Comment by Greg-Mukuria** [comment]
What of pnpm?
