### ISSUE TITLE
new MultiSelect component showing close icon before selecting anything

### ISSUE THREAD

**Issue by thethmuu** [tremorlabs/tremor-npm#523]
In the previous MultiSelectBox component, it doesn't show a close icon before user select an option. That is good user experience. 
Now with the new MultiSelect, it shows that icon at the start before selecting any option.

**Comment by mitrotasios** [comment]
@thethmuu fair point, will fix!

**Comment by thethmuu** [comment]
@mitrotasios I am working on it. Will submit PR soon.

**Comment by mitrotasios** [comment]
Ah awesome, thanks!

**Comment by thethmuu** [comment]
https://github.com/tremorlabs/tremor/pull/526

@mitrotasios I submitted. This is my first Open Source PR. Please check and suggest me if I can improve.

**Comment by mitrotasios** [comment]
@thethmuu, thanks for fixing :)
