### ISSUE TITLE
[Bug]: Should render child texts instead of values in DateRangePicker

### ISSUE THREAD

**Issue by devrsi0n** [tremorlabs/tremor-npm#524]
### Tremor Version

3.2.1

### Link to minimal reproduction

https://stackblitz.com/edit/stackblitz-starters-ynay4j?file=pages%2Findex.js

### Steps to reproduce

- click select on date picker component

<img width="1854" alt="image" src="https://github.com/tremorlabs/tremor/assets/7880675/5302ad05-1295-4891-8121-02f3c3c6e914">

### What is expected?

Should see children texts

### What is actually happening?

Seeing values instead

### What browsers are you seeing the problem on?

Chrome

### Any additional comments?

This issue can also be repro on storybook

<img width="1070" alt="image" src="https://github.com/tremorlabs/tremor/assets/7880675/6fcfc148-4e5f-468f-a40d-bc8294b1860c">

**Comment by mitrotasios** [comment]
@devrsi0n thanks for submitting this, we're on it!

**Comment by devrsi0n** [comment]
Thanks for the quick fix
