### ISSUE TITLE
[Bug]: After Updating on v^3.2.2, I am facing an issue with LineChart

### ISSUE THREAD

**Issue by devwithnaveed** [tremorlabs/tremor-npm#527]
### Tremor Version

3.2.2

### Link to minimal reproduction

.

### Steps to reproduce

 ```
        
const chartdata = [
  {
    year: 1970,
    "Export Growth Rate": 2.04,
    "Import Growth Rate": 1.53,
  },
  {
    year: 1971,
    "Export Growth Rate": 1.96,
    "Import Growth Rate": 1.58,
  },
  {
    year: 1972,
    "Export Growth Rate": 1.96,
    "Import Growth Rate": 1.61,
  },
  {
    year: 1973,
    "Export Growth Rate": 1.93,
    "Import Growth Rate": 1.61,
  },
  {
    year: 1974,
    "Export Growth Rate": 1.88,
    "Import Growth Rate": 1.67,
  },
  //...
];

const dataFormatter = (number: number) => `${Intl.NumberFormat("us").format(number).toString()}%`;

<LineChart
          showLegend={false}
          className="mt-6"
          data={chartdata}
          index="year"
          categories={["Export Growth Rate", "Import Growth Rate"]}
          colors={["emerald", "gray"]}
          valueFormatter={dataFormatter}
          yAxisWidth={40}
        />
       
```

this is code just copied from official documentation 

### What is expected?

Should Show lines like this
![b48e0bbf-7a53-4279-a4b8-f238136694e4](https://github.com/tremorlabs/tremor/assets/49093438/f27dbb5e-15ae-4272-a33c-fe0a48ae9132)

### What is actually happening?

Not able to see Axis Lines, 
![image](https://github.com/tremorlabs/tremor/assets/49093438/744c0ab7-0651-4fd5-8c1f-bdeeba543515)

### What browsers are you seeing the problem on?

Chrome

**Comment by jocarrd** [comment]
working on it https://github.com/recharts/recharts/issues/3615

**Comment by jocarrd** [comment]
Still not working
![image](https://github.com/tremorlabs/tremor/assets/55456507/00a29ecb-563f-403e-ad33-1789ce7829f5)
