### ISSUE TITLE
[Feature]: Show/hide value in text input password

### ISSUE THREAD

**Issue by LauraCSDev** [tremorlabs/tremor-npm#530]
### What problem does this feature solve?

It's impossible see the value in text input password

### What does the proposed API look like?

A decorator for text input password, works like the eye icon to show/hide the password when clicked.

![image](https://github.com/tremorlabs/tremor/assets/60747616/587c2886-8d20-46d1-95c5-a2b8e102dbba)
![image](https://github.com/tremorlabs/tremor/assets/60747616/0e76b284-54ee-411a-b420-48c49945f02a)

**Comment by Devkant21** [comment]
I would like to work on this feature. Just wanted to confirm whether I could use other libraries to implement the feature.

**Comment by LauraCSDev** [comment]
> I would like to work on this feature. Just wanted to confirm whether I could use other libraries to implement the feature.

I suppose that it is unnecessary, this function is enough with the use of the same icon and some validations when the text entry is of the password type.
