### ISSUE TITLE
[Feature]: Radar Chart

### ISSUE THREAD

**Issue by daoleno** [tremorlabs/tremor-npm#532]
### What problem does this feature solve?

Users can display radar charts conveniently.

### What does the proposed API look like?

https://www.chartjs.org/docs/latest/charts/radar.html

More: https://ossinsight-lite.vercel.app/

**Comment by lakeesiv** [comment]
May I have a go at this!

**Comment by carlospombeiro** [comment]
Any progress on this?

**Comment by severinlandolt** [comment]
Hi! We've built dashboards for dozens of clients over 4 years, with backgrounds in data science and software. In all that time, we've never found radar charts to be the best solution for any case. So we're not planning to add this feature anytime soon.
