### ISSUE TITLE
[Bug]: Using tremo and Material Tailwind together may cause some icon colors to become invalid.

### ISSUE THREAD

**Issue by pickedbrian** [tremorlabs/tremor-npm#535]
### Tremor Version

3.2.5,3.2.3

### Link to minimal reproduction

https://github.com/creativetimofficial/material-tailwind?ref=material-tailwind

### Steps to reproduce

1.install termor and matterial tailwind
2.Code and preview
`          <TextInput
            placeholder="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            onBlur={validateForm}
            error={Boolean(errors.password)}
          />`

### What is expected?

If I remove withMT, the icons can revert to their normal state.
![image](https://github.com/tremorlabs/tremor/assets/100608404/747ad2f7-b13b-4583-82d4-c3476aaf1184)

### What is actually happening?

Once using withMT, some icons will lose their colors.
![image](https://github.com/tremorlabs/tremor/assets/100608404/fc24c75b-9c23-4d6d-8220-78fa06c4310a)
![image](https://github.com/tremorlabs/tremor/assets/100608404/83a55d1a-0b96-430d-9066-97c5781d6660)

### What browsers are you seeing the problem on?

Chrome

### Any additional comments?

Should I ask this question at Material Tailwind or here?

**Comment by pickedbrian** [comment]
seems that the color attribute has been overridden

material Tailwind config withMT:

1.https://github.com/creativetimofficial/material-tailwind/blob/main/packages/material-tailwind-react/src/utils/withMT.js

2.https://github.com/creativetimofficial/material-tailwind/blob/main/packages/material-tailwind-react/src/theme/base/colors.js

**Comment by pickedbrian** [comment]
still。

**Comment by pickedbrian** [comment]
![image](https://github.com/tremorlabs/tremor/assets/100608404/3de4232d-e37d-49e2-8fa6-b6d6c408e1c5)
![image](https://github.com/tremorlabs/tremor/assets/100608404/ba4f181f-f1f1-405a-8fd2-75cd6d1e879a)

**Comment by severinlandolt** [comment]
Hi! To solve this problem, please consult with Material Tailwind.
