### ISSUE TITLE
[Bug]: DateRangePicker options not localized

### ISSUE THREAD

**Issue by EdoMon93** [tremorlabs/tremor-npm#536]
### Tremor Version

3.2

### Link to minimal reproduction

https://www.tremor.so/docs/components/daterangepicker

### Steps to reproduce

whatever locale im using its not translating the relative range options in the dropdown, this is seen in the example.

### What is expected?

for the locale to be applied to the dropdown options or to be able to override the options as to translate manually

### What is actually happening?

the locale is in es, but the options are in en

### What browsers are you seeing the problem on?

Chrome

**Comment by severinlandolt** [comment]
Hey @EdoMon93, thank you for noticing. It is indeed true, that the locale is not affecting the selection. The localization is only possible for the date picker itself. I adjusted the corresponding documentation with an example. This example also shows, how to add custom select values. I hope this helps! 

The updated docs will be online soon.

**Comment by EdoMon93** [comment]
Thank you!!
Ive seen the updated doc now, makes sense. 
Seemed strange not to be able to customize options.
cheers
