### ISSUE TITLE
[Bug]: incorrect "Controlled state example" in the documentation

### ISSUE THREAD

**Issue by DenysVuika** [tremorlabs/tremor-npm#537]
### Tremor Version

latest

### Link to minimal reproduction

https://www.tremor.so/docs/components/select

### Steps to reproduce

The `SelectControlled` component has no controlled state implementation.

### What is expected?

The documentation should provide a valid working example

### What is actually happening?

it's a copy-pasted `SelectExample` component with the added "useState" line, no integration with the state is provided

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Safari, Firefox, Vivaldi, Brave

**Comment by severinlandolt** [comment]
Thank you for the hint!
