### ISSUE TITLE
[Feature]: Sticky header property for tables

### ISSUE THREAD

**Issue by FS75** [tremorlabs/tremor-npm#541]
### What problem does this feature solve?

Having a sticky header property for tables would benefit tables with large amount of data and require scrolling down. Users tend to forget what the values mean when they scroll down too far, due to the headers being all the way up. Tried looking for the property in the Table API but to no avail. 

### What does the proposed API look like?

Description: Enable sticky headers for the table
Type: boolean
Default: false
Values: true, false

I'm new to Tailwind CSS and I am unsure of what the solution would look like. I was dabbling with flex, flex-grow, and overflow-auto but realised that the Table component has overflow-auto enabled already.

**Comment by FS75** [comment]
Closed issue as I have solved it through other means already.

**Comment by severinlandolt** [comment]
Hi @FS75, would like to follow up on your solution. Did you use `className="sticky bg-white"` on the TableHead component?

**Comment by FS75** [comment]
> Hi @FS75, would like to follow up on your solution. Did you use `className="sticky bg-white"` on the TableHead component?

Hi @severinlandolt, I realised that the table does indeed have sticker headers when I render a standalone one. It was some other CSS property in the parent component of my table that was affecting the sticky headers not working. So there was actually no issue at all, thank you so much for replying though!

**Comment by deepchandra02** [comment]
Hi @FS75 , I want to have sticky headers as well, but cannot implement it. Could you share how it worked?

**Comment by ghost** [comment]
bump on this?
