### ISSUE TITLE
[Bug]: DatePicker modal is not closed once the date is chosen

### ISSUE THREAD

**Issue by bart-krolak** [tremorlabs/tremor-npm#544]
### Tremor Version

3.4.0

### Link to minimal reproduction

https://www.tremor.so/docs/components/daterangepicker

### Steps to reproduce

1. Click on the single DatePicker,
2. Choose a new Date,

### What is expected?

Once the date is chosen the modal with calendar should be closed.

### What is actually happening?

The modal with calendar is still visible - it closes once the user clicks outside of it.

### Any additional comments?

I was playing around with the new DatePicker right after Tremor update to v3.4.0

**Comment by christopherkindl** [comment]
Thanks Bart, working on it!
