### ISSUE TITLE
[Bug]: It is not clear for non UI experts how to use "dark mode" 

### ISSUE THREAD

**Issue by AbdelrhmanHamouda** [tremorlabs/tremor-npm#545]
### Tremor Version

latest

### Link to minimal reproduction

N/A

### Steps to reproduce

Reading the docs says that i have to use prefers-color-scheme  from tailwind which I have no idea what it is. 

### What is expected?

something more straightforward or  simply a set of steps to get darkmode activated 

### What is actually happening?

docs are lacking this part making it not possible without previous frontend knowledge!

**Comment by jordaniscrosby** [comment]
usually this is in your browser appearance settings. 

I am on edge and it looks like this:
![image](https://github.com/tremorlabs/tremor/assets/28069571/80956e9c-e64a-4319-bfac-d2c6fa36e2f7)

I agree the whole prefers-scheme is annoying, and prefer a system like MUI but thats just the tradeoff you make when choosing SSR tailwind

**Comment by lakeesiv** [comment]
If you are using Nextjs then `pacocoursey/next-themes` handles the switching to dark mode very nicely https://github.com/pacocoursey/next-themes#with-tailwind

**Comment by severinlandolt** [comment]
Hey there! I added some notes to our documentation and linked`next-themes` for further reading, I hope this helps!
