### ISSUE TITLE
[Bug]: Natural curve line oscillates, overshoots or undershoots

### ISSUE THREAD

**Issue by EdoMon93** [tremorlabs/tremor-npm#550]
### Tremor Version

3.4.1

### Link to minimal reproduction

NA

### Steps to reproduce

use as datapoints 0 value and next datapoint as a high value.

### What is expected?

interpolation of natural curve not to oscillate, undershoot or overshoot

### What is actually happening?

Line Charts using curveType natural interpolate points in an unexpected way, showing misleading values.

This also causes for line to be cut due to overflow.

value would seem to have been higher than 2.3 (not the case):
![image](https://github.com/tremorlabs/tremor/assets/32374370/ff0edb44-26ed-4a88-9710-bba9313330a4)
value would seem to drop below 0 (not the case):
![image](https://github.com/tremorlabs/tremor/assets/32374370/118fe7ed-989a-4a3e-aff2-e442e477f1d2)
![image](https://github.com/tremorlabs/tremor/assets/32374370/b3ca72a4-6d29-4818-b9cc-6674c3d9a5ef)

### What browsers are you seeing the problem on?

Chrome

**Comment by motinados** [comment]
This is a characteristic of curveType "natural".
Please take a look at the following recharts sample. 
(recharts is a library that tremor uses internally.)

https://codesandbox.io/s/recharts-linechart-sample-kc39qq?file=/src/App.tsx

**Comment by motinados** [comment]
This might not be a bug, it could be a characteristic of the curveType natural.
I've created sample code with recharts.
(recharts is a library used internally by tremor)

https://codesandbox.io/s/recharts-linechart-sample-kc39qq

**Comment by severinlandolt** [comment]
Indeed! Is there a particular reason you wanted to use natural? Have you tried monotone?

**Comment by severinlandolt** [comment]
Added a new curve type `monotone` which oscillates a lot less. → https://github.com/tremorlabs/tremor/releases/tag/v3.5.0
Also removed the natural curve type from the recommendation in the docs.

**Comment by EdoMon93** [comment]
thx! will look into it. Monotone was not a documented option
