### ISSUE TITLE
[Feature]: Add "toggleIcon" to the DatePicker

### ISSUE THREAD

**Issue by bart-krolak** [tremorlabs/tremor-npm#554]
### What problem does this feature solve?

In the current implementation of `DatePicker` there is no possibility to customize the toggle-icon.

Adding the possibility to add a custom toggle-icon gives users more flexibility and improves UX.

### What does the proposed API look like?

```diff
export interface DatePickerProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, "value" | "defaultValue"> {
  value?: Date;
  defaultValue?: Date;
  onValueChange?: (value: Date | undefined) => void;
  minDate?: Date;
  maxDate?: Date;
  placeholder?: string;
  disabled?: boolean;
  color?: Color;
  locale?: Locale;
  enableClear?: boolean;
  children?: React.ReactElement[] | React.ReactElement;
+ toggleIcon?:React.ReactElement;
}
```

**Comment by severinlandolt** [comment]
Hi @bart-krolak and thanks for your feedback. Could you provide a little bit more context on why this feature would be helpful to you? Love to hear about our specific use case for that. Screenshots appreciated. Thanks!

**Comment by bart-krolak** [comment]
Hello @severinlandolt,

It would be good to follow **Material-Design/MaterialUI** example by adding a  possibility to display the switch-to-calendar view icon. Below are the examples from MD and MUI:

- https://m2.material.io/components/date-pickers#anatomy

<img width="839" alt="image" src="https://github.com/tremorlabs/tremor/assets/85454149/a9a2aa53-5e01-419d-b3cd-53a7ab9837a4">

- https://mui.com/x/react-date-pickers/date-picker/
<img width="399" alt="image" src="https://github.com/tremorlabs/tremor/assets/85454149/485394f4-a8d4-4161-865b-bfe8a2a31eb0">

<img width="439" alt="image" src="https://github.com/tremorlabs/tremor/assets/85454149/cf57e032-ac21-4cda-be5b-e78238d51530">

**Comment by severinlandolt** [comment]
Hey there, we reviewed your proposal and decided not to implement this feature. Thanks for your interest!
