### ISSUE TITLE
With NextJS turborepo, @tremor is only in the root folder /node_modules which prevents Tailwind styling to work

### ISSUE THREAD

**Issue by jpvalery** [tremorlabs/tremor-npm#555]
Hi there,

I followed the documentation to the letter, but I'm running into an issue with Tailwind. 

That project being a turborepo, the `@tremor` folder is only present in the root `node_modules` (i.e. not in the `/projects/xxx/node_modules` folder). 

If I manually copy/paste it from the root to the project folder, everything works as expected but that's not really a solution. 

If I leave it as is, I get a compilation error with next build
```
Module not found: Can't resolve '@tremor/react'
```
but next dev works (albeit with an unstyled output)

If I update my next.config.js to transpile it, then it compiles
```
const nextConfig = {
	transpilePackages: ['@tremor/react'],
};
```

I tried searching in Issues and Discussions for something similar but couldn't find one. 

Is there something obvious I'm missing here?

Thanks in advance for any help/insights 🙏

**Comment by erikarenhill** [comment]
try updating your tailwind.config.js to look at root level instead, e.g. 
instead of
`"./node_modules/@tremor/**/*.{js,ts,jsx,tsx}"`
try using
`"../../node_modules/@tremor/**/*.{js,ts,jsx,tsx}"`

**Comment by jpvalery** [comment]
Hey Erik! Thanks for the reply. 

Yeah I ended up doing that last night (actually doing both):
```
		'./node_modules/@tremor/**/*.{js,ts,jsx,tsx}', // local
		'../../node_modules/@tremor/**/*.{js,ts,jsx,tsx}', // root
```
So that it worked locally. I also kept the transpile option.

I wasn’t sure if it’d work when deploying but it did :raised_hands:  I’m happy to open a PR to update the docs to highlight that use case if that’s helpful
