### ISSUE TITLE
[Feature]: OnMouseEnter in DonutChart

### ISSUE THREAD

**Issue by DanailPenev** [tremorlabs/tremor-npm#557]
### What problem does this feature solve?

We have a classic pie chart that looks similar to the one from the docs.
![image](https://github.com/tremorlabs/tremor/assets/14945759/661799d1-d98c-4a6a-8d33-e975d978d966)

Since the pie chart lives alongside other data, we want to have some functionality where hovering a sector in the pie chart highlights the data on the page that this sector relates to. Basically, we will map the sector of the pie chart to a row in the table and highlight that row.

### What does the proposed API look like?

The recharts PieChart API that is used in Tremor looks like this
```
  onMouseEnter?: (data: any, index: number, e: React.MouseEvent) => void;
  onMouseLeave?: (data: any, index: number, e: React.MouseEvent) => void;
```
[Source](https://recharts.org/en-US/api/PieChart#onMouseEnter)

One option would be to propagate these handlers to Tremor. Alternatively, the complexity could be abstracted but I am not certain what would be a nicer API.

**Comment by severinlandolt** [comment]
Hi @DanailPenev, sorry for getting back to you so late. Thank you for providing a detailed description. I like the proposed feature but I am not sure if a `onMouseEnter` is the correct event for that. This is because of compatibility on mobile i.e. touch devices. In light of this, we are currently working on `onClick` events for the charts.

**Comment by severinlandolt** [comment]
Heya! Due to the reasons above and the fact that we will be adding onClick events soon, so I am going to close this issue. Thank you for being an active part of the tremor community :)
