### ISSUE TITLE
[Bug]: unable to translate MultiSelect when items are selected

### ISSUE THREAD

**Issue by EdoMon93** [tremorlabs/tremor-npm#562]
### Tremor Version

3.2

### Link to minimal reproduction

NA

### Steps to reproduce

Trying to translate/customize what is shown when options are selected.

### What is expected?

For there to be a way to customize what is shown when items are selected, for translation purposes, pill usage, etc.

### What is actually happening?

MultiSelect always shows "n Selected"
![image](https://github.com/tremorlabs/tremor/assets/32374370/f85c5128-9d1e-4a7e-80ea-2abed21e1ba7)

### What browsers are you seeing the problem on?

Chrome

### Any additional comments?

maybe its a doc issue

**Comment by EdoMon93** [comment]
@severinlandolt  How would one go as to translate the "N Selected" label?

**Comment by severinlandolt** [comment]
An updated version of the Multiselect has been released, making this issue not applicaple. Note that there also a new placeholderSelect prop.
