### ISSUE TITLE
[Bug]: Incorrect description in Donut Chart API reference for valueFormatter

### ISSUE THREAD

**Issue by deepchandra02** [tremorlabs/tremor-npm#564]
### Tremor Version

3.4.1 (latest)

### Link to minimal reproduction

https://www.tremor.so/docs/components/donut-chart

### Steps to reproduce

N/A

### What is expected?

Controls the text formatting for the **tooltip** values. When using Typescript, import the ValueFormatter type provided by tremor.

### What is actually happening?

Controls the text formatting for the **y-axis** values. When using Typescript, import the ValueFormatter type provided by tremor.

**Comment by severinlandolt** [comment]
Hey @deepchandra02, thanks for the hint!

**Comment by deepchandra02** [comment]
Hey @severinlandolt, this was my first time reporting an issue XD. I am using tremor to build a dashboard in my internship, and occasionally come across such documentation issues. Would adding more issues here help?

**Comment by severinlandolt** [comment]
Hi @deepchandra02, absolutely, please feel free to add as many issues as you can. Your work is very helpful to improve our product!
