### ISSUE TITLE
[Bug]: 'DateRangePickerValue' (imported as 'DateRangePickerValue') was not found in '@tremor/react' 

### ISSUE THREAD

**Issue by deepchandra02** [tremorlabs/tremor-npm#568]
### Tremor Version

3.4.1 (latest)

### Link to minimal reproduction
The code given in the example:
[https://www.tremor.so/docs/components/daterangepicker](url)
N/A

### Steps to reproduce

import { useState } from "react";
import { DateRangePicker, DateRangePickerItem, DateRangePickerValue } from "@tremor/react";
import { es } from "date-fns/locale";

export function DateRangePickerSpanish() {
  const [value, setValue] = useState<DateRangePickerValue>({
    from: new Date(2023, 1, 1),
    to: new Date(),
  });

  return (
    <DateRangePicker
      className="max-w-md mx-auto"
      value={value}
      onValueChange={setValue}
      locale={es}
      selectPlaceholder="Seleccionar"
      color="rose"
    >
      <DateRangePickerItem key="ytd" value="ytd" from={new Date(2023, 0, 1)}>
        Año transcurrido
      </DateRangePickerItem>
      <DateRangePickerItem
        key="half"
        value="half"
        from={new Date(2023, 0, 1)}
        to={new Date(2023, 5, 31)}
      >
        Primer semestre
      </DateRangePickerItem>
    </DateRangePicker>
  );
}

### What is expected?

No errors. Documentation provides this example at [https://www.tremor.so/docs/components/daterangepicker](url)

### What is actually happening?

export 'DateRangePickerValue' (imported as 'DateRangePickerValue') was not found in '@tremor/react' (possible exports: Accordion, AccordionBody, AccordionHeader, AccordionList, AreaChart, Badge, BadgeDelta, BarChart, BarList, Bold, Button, Callout, Card, CategoryBar, Col, DatePicker, DateRangePicker, DateRangePickerItem, DeltaBar, Divider, DonutChart, Flex, Grid, Icon, Italic, Legend, LineChart, List, ListItem, MarkerBar, Metric, MultiSelect, MultiSelectItem, ProgressBar, SearchSelect, SearchSelectItem, Select, SelectItem, Subtitle, Tab, TabGroup, TabList, TabPanel, TabPanels, Table, TableBody, TableCell, TableHead, TableHeaderCell, TableRow, Text, TextInput, Title, Tracker)

### Any additional comments?

Please update the documentation

**Comment by lakeesiv** [comment]
Weird, I could not reproduce this with `3.4.1`, do you have a minimal example? Perhaps try deleting `node_modules` and reinstalling your packages

**Comment by deepchandra02** [comment]
You are right, I deleted the node_modules and reinstalled, it worked all good. Sorry for the mistake

**Comment by deepchandra02** [comment]
I updated the issue and the way to reproduce the error, turns out just importing the module name wasn't enough to trigger the error, its when the following code runs, the error occurs:

`const [value, setValue] = useState<DateRangePickerValue>({
    from: new Date(2023, 1, 1),
    to: new Date(),
  });`
  
  Note: I am using this is a .jsx file. Is that the issue?

**Comment by lakeesiv** [comment]
You can only use types in a `.tsx` file. So in a `.jsx` file, you would write

`const [value, setValue] = useState({ from: new Date(2023, 1, 1), to: new Date(), });`

**Comment by deepchandra02** [comment]
Thank you so much!
