### ISSUE TITLE
I found a small typo in the documentation

### ISSUE THREAD

**Issue by p-rohitt** [tremorlabs/tremor-npm#583]
I was going through [the installation part of the docs](https://www.tremor.so/docs/getting-started/installation) where I stumbled upon this 
![image](https://github.com/tremorlabs/tremor/assets/102830723/cad94f00-46a1-4f32-aefb-ce17c6a4dd2c)

**Comment by christopherkindl** [comment]
Hi @p-rohitt,

thanks for this! Fixed it.
