### ISSUE TITLE
[Bug]: Missing calendar icon in date (range) picker

### ISSUE THREAD

**Issue by christopherkindl** [tremorlabs/tremor-npm#585]
### Tremor Version

v3.5.0

### Link to minimal reproduction

https://www.tremor.so/docs/components/daterangepicker

### Steps to reproduce

applicable in Tremor's documentation

### What is expected?

Show (1) calendar icon and (2) chevron down icon in input field

<img width="762" alt="Screenshot 2023-07-25 at 10 48 40" src="https://github.com/tremorlabs/tremor/assets/53372002/61d82aef-9e76-45e9-9467-98d929190c22">

Icon library:

- Calendar icon: https://v1.heroicons.com/ (solid variant)
- Chevron-down icon: https://v1.heroicons.com/ (outline variant)

### What is actually happening?

No icons used currently, busy Tremor team forgot to add them

### Any additional comments?

If a contributor want to grab this issue, please comment and we will assign it to you.

**Comment by mbauchet** [comment]
I can take this one

**Comment by christopherkindl** [comment]
Damn, that was fast! Thanks so much 🙏
