### ISSUE TITLE
[Bug]: current date not highlighted in Calendar

### ISSUE THREAD

**Issue by mitrotasios** [tremorlabs/tremor-npm#590]
### Tremor Version

3.5.0

### Link to minimal reproduction

Check website

### Steps to reproduce

Check website

### What is expected?

The current date should be highlighted in some way

### What is actually happening?

The current date is NOT highlighted

**Comment by mbauchet** [comment]
<img width="290" alt="Capture d’écran 2023-07-27 à 07 44 08" src="https://github.com/tremorlabs/tremor/assets/90607026/efbef04d-d4ad-48cc-86ec-04c71f48a9bd">
<img width="288" alt="Capture d’écran 2023-07-27 à 07 43 36" src="https://github.com/tremorlabs/tremor/assets/90607026/d8081439-836e-499c-bea9-d7d2b1fd540b">

Something like that?
