### ISSUE TITLE
[Bug]: NumberInput component stepper does not fire onChange event

### ISSUE THREAD

**Issue by fabioriva** [tremorlabs/tremor-npm#592]
### Tremor Version

3.5.0

### Link to minimal reproduction

no link

### Steps to reproduce

no steps

### What is expected?

onChange event should be fired when stepper buttons are clicked

### What is actually happening?

onChange event is not fired when stepper buttons are clicked

### Any additional comments?

No

**Comment by deepchandra02** [comment]
Well, when I used this component yesterday, I used onValueChange, and it works

**Comment by severinlandolt** [comment]
Hi, have you tried the onValueChange property?

**Comment by fabioriva** [comment]
Hi all, today I had some time to do some additional tests and yes, I can confirm that the onValueChange event is triggered both by clicking on the stepper buttons and by editing the input field.
Below is the code I used for testing. Thank you @deepchandra02 and @severinlandolt.

`"use client";

import { useEffect, useState } from "react";
import { Card, NumberInput } from "@tremor/react";

export default function TestNumberInput(params) {
  const [value, setValue] = useState(1);

  useEffect(() => {
    console.log("useEffect", value);
  }, [value]);

  // const handleOnChange = (e) => {
  //   console.log("onChange", e);
  //   setValue(e.target.value);
  // };

  const handleOnValueChange = (value) => {
    console.log("onValueChange", value);
    setValue(value);
  };

  return (
    <Card>
      <h1>Value is {value}</h1>
      <NumberInput
        className="mt-3"
        value={value}
        // onChange={handleOnChange}
        onValueChange={handleOnValueChange}
      />
    </Card>
  );
}
`

**Comment by severinlandolt** [comment]
That is great! Thank you for sticking around and sharing your test🤘
