### ISSUE TITLE
[Feature]: Add angle property to BarChart for XAxis

### ISSUE THREAD

**Issue by osagit** [tremorlabs/tremor-npm#593]
### What problem does this feature solve?

BarChart axis label is always horizontal which cause some trouble with large text.
Could you add the angle property which is available in the recharts XAxis component: https://recharts.org/en-US/api/XAxis

 // New: angle for XAxis labels
`<XAxis angle={angle || 0} ... />`

**Comment by severinlandolt** [comment]
#128

**Comment by severinlandolt** [comment]
cf. #128
