### ISSUE TITLE
[Bug]: BarList bars have incorrect color strength, when custom color set, for dark theme marking text unreadable

### ISSUE THREAD

**Issue by sbargon** [tremorlabs/tremor-npm#612]
### Tremor Version

3.6.0

### Link to minimal reproduction

https://www.tremor.so/docs/components/barlist

### Steps to reproduce

create a BarList, add color values for the Bars in the data field and set theme to dark

![Screenshot (18)](https://github.com/tremorlabs/tremor/assets/1121158/40615c7c-01d3-431b-9200-f91c3ddd66bc)

### What is expected?

text inside bar should be readable, bars need more color strength when in dark mode (like 600)

Something like (got this by setting color to 'orange-600 ' etc, in-case anyone needs a workaround, notice space at end)

![Screenshot (19)](https://github.com/tremorlabs/tremor/assets/1121158/48053191-de6f-429d-8fc7-bac1a67df3ea)

### What is actually happening?

bar color weight is set to 100, when a custom color is set, making the whitish text unreadable as colors is so weak

**Comment by severinlandolt** [comment]
Thanks for the feedback! We will address definitely address that.

**Comment by severinlandolt** [comment]
New dark mode colors will ship with v3.9
![CleanShot 2023-10-01 at 19 59 13@2x](https://github.com/tremorlabs/tremor/assets/41927988/2eb66307-50e6-4eaf-a553-5c7b1a101391)
