### ISSUE TITLE
[Bug]: TabGroup has incorrect usage of ARIA

### ISSUE THREAD

**Issue by ed-g-c** [tremorlabs/tremor-npm#613]
### Tremor Version

v3.6.1

### Link to minimal reproduction

https://pagespeed.web.dev/analysis/https-www-tremor-so/2t6l76cftd?form_factor=mobile

### Steps to reproduce

1. Open Pagespeed Insights link
2. Go to Accessibility > ARIA

### What is expected?

No ARIA-related errors

### What is actually happening?

An error is displayed: `[aria-*]` attributes do not match their roles.

**Comment by severinlandolt** [comment]
Oh, thank you for catching this @ed-g-c. Will take a look at it!

**Comment by ed-g-c** [comment]
> Oh, thank you for catching this @ed-g-c. Will take a look at it!

Thanks @severinlandolt, here's a PR to address it https://github.com/tremorlabs/tremor/pull/614

**Comment by severinlandolt** [comment]
As mentioned in the PR #614, we won't be taking this further. **However**: We recently launched Tremor Raw, a copy & paste library for React components. Here we have a [new version of the Tabs](https://raw.tremor.so/docs/ui/tabs), where improved accessibility and more control over your tabs!
