### ISSUE TITLE
[Feature]: Add ability to set Y-axis labels in Tremor charts

### ISSUE THREAD

**Issue by bart-krolak** [tremorlabs/tremor-npm#616]
### What problem does this feature solve?

Currently there is no possibility to set axis labels in Tremor charts:

- Area Chart,
- Line Chart,
- Bar Chart,
- Scatter Chart,

It would be great, if there was put text rotated next to the Y-axis displaying like e.g. "pv of page" to make it clear what this chart is saying.

<img width="844" alt="image" src="https://github.com/tremorlabs/tremor/assets/85454149/bb94aad7-8a3f-45f6-9a64-f8af9ce2d6b6">

### What does the proposed API look like?

For every chart type there could be added an additional prop e.g. `yAxisLabel`.

**Comment by severinlandolt** [comment]
Thanks @bart-krolak for your feedback. Adding new features to your charts is a priority right now, will definitely take a look at this one!

**Comment by bart-krolak** [comment]
Hi @severinlandolt,
Nice to hear that!

**Comment by severinlandolt** [comment]
Hi! We had a look at it and also tested a few variants. Unfortunately, we concluded that adding lables comes with a few extra parameters that have to be configured depending on your y-axis input etc, making the feature not very predictable. Thus, we are not going to add this, at least for now.
