### ISSUE TITLE
[Test]: Unit tests for select elements

### ISSUE THREAD

**Issue by mitrotasios** [tremorlabs/tremor-npm#618]
### What problem does this feature solve?

Currently, components are only tested via storybook. However, select elements are prone to bugs and should be unit tested based on user interaction.

The components that should be unit tested are:
* Datepicker
* DateRangePicker
* Select
* MultiSelect
* SearchSelect
* TextInput
* NumberInput
* Button

If anyone from the community is willing to take this issue, feel free to comment below. :)

**Comment by jzfrank** [comment]
Hi @mitrotasios, I would like to be assigned for this!

**Comment by mitrotasios** [comment]
@jzfrank awesome, thank you! Just assigned you

**Comment by severinlandolt** [comment]
Thanks. @jzfrank ! Will take a look at it this week!
