### ISSUE TITLE
[Feature]: Using colors other than standard tw colors

### ISSUE THREAD

**Issue by needim** [tremorlabs/tremor-npm#619]
### What problem does this feature solve?

I am using custom colors (radix colors), so the default `bg-rose-500` is not applicable to me.

### What does the proposed API look like?

allow me to specify the colors map for the used colors in tremor.

```
 rose-50: #aabbcc;
 rose-100: #aabbcc;
 rose-200: #aabbcc;
 .
 .
 .
```

**Comment by severinlandolt** [comment]
https://www.tremor.so/docs/getting-started/theming#custom-charts-colors
