### ISSUE TITLE
[Feature]: make Calendar et al. useable with uncontrolled forms

### ISSUE THREAD

**Issue by tompeace** [tremorlabs/tremor-npm#620]
### What problem does this feature solve?

I would like to use the calendar component and its different flavours (DatePicker, DateRangePicker) as uncontrolled form fields. Currenty the only way to extract the value is to pass state to the component, if I want to add this to the outgoing formData i think the only way would be to do some trickery with the outgoing onSubmit event and then hook the value in somehow.

The components could include an `<input type="hidden" name={props.name} value={state.currentValue} />` within them so that form onsubmit could detect the value automatically.

### What does the proposed API look like?

The proposed API is as follows:
Add something like `<input type="hidden" name={props.name} value={state.currentValue} />` to each component somewhere, not directly in the Calendar component itself, then serialised accordingly (for eg. DateRangePicker would have 2 value).

**Comment by mitrotasios** [comment]
@tompeace would you mind sharing an example where the Calendar elements are not working for uncontrolled forms? They appear to work in the stories

**Comment by severinlandolt** [comment]
Hi @tompeace, were you able to use the calendar with uncontrolled forms?
