### ISSUE TITLE
[Bug]: DateRangePicker Calendar not changing `month` for locales

### ISSUE THREAD

**Issue by jzfrank** [tremorlabs/tremor-npm#622]
### Tremor Version

3.6.1

### Link to minimal reproduction

https://stackblitz.com/edit/stackblitz-starters-2xymze?file=pages%2FDatePickerDemo.js

### Steps to reproduce

```javascript
import * as React from 'react';
import { DateRangePicker, DateRangePickerItem } from '@tremor/react';
import { useState } from 'react';
import { enUS, es } from 'date-fns/locale';

const DatePickerDemo = () => {
  const [value, setValue] = useState({
    from: new Date(2023, 1, 1),
    to: new Date(),
  });

  const [locale, setLocale] = useState('es');

  return (
    <div className="container w-1/2">
      <div className=" mb-4">
        <span>Current Locale: {locale}</span>
        <button
          onClick={() => setLocale((prev) => (prev === 'enUS' ? 'es' : 'enUS'))}
          className="bg-blue-400 px-1 rounded ml-2 mt-2 hover:bg-blue-300"
        >
          Toggle Locale
        </button>
      </div>
      <div className=" mx-auto mt-5">
        <DateRangePicker
          className="mx-auto max-w-md"
          value={value}
          onValueChange={setValue}
          locale={locale === 'enUS' ? enUS : es}
          color="rose"
          enableSelect={false}
        ></DateRangePicker>
      </div>
    </div>
  );
};

export default DatePickerDemo;
```

### What is expected?

When the locale is set to locales other than `en`, for example: `es`, the datePicker should show month in locale of `es`. For example, `August` should be `Agosto`. 

### What is actually happening?

The month remains to be in `enUS` locale. 

<img width="295" alt="image" src="https://github.com/tremorlabs/tremor/assets/77217626/88ea95d1-a143-4572-a52f-e637967e299f">

### What browsers are you seeing the problem on?

Chrome

**Comment by jzfrank** [comment]
It's an easy to solve bug. I would like to be assigned and fix it quickly.

**Comment by christopherkindl** [comment]
Hi @jzfrank, thanks for this and helping. I just tagged you.
