### ISSUE TITLE
[Bug]: fix typo in documentation

### ISSUE THREAD

**Issue by jzfrank** [tremorlabs/tremor-npm#623]
### Tremor Version

3.6.1

### Link to minimal reproduction

https://www.tremor.so/docs/components/select

### Steps to reproduce

<img width="818" alt="image" src="https://github.com/tremorlabs/tremor/assets/77217626/89e71e63-5fc3-4c68-9063-3484e6f9bda9">

### What is expected?

The `value` or `defaultValue` for `MultiSelect` component should be of type array `string []` instead of `string`. 

### What is actually happening?

Now the doc shows `string` type. This may create unnecessary misunderstandings. 

### What browsers are you seeing the problem on?

Chrome

**Comment by severinlandolt** [comment]
Thanks for catching this!

**Comment by jzfrank** [comment]
@severinlandolt 
Thanks for the prompt action and reply. However, as I'm checking the doc today, it doesn't get completely corrected. 
<img width="809" alt="image" src="https://github.com/tremorlabs/tremor/assets/77217626/9ac5bc22-9572-4259-809f-7734d70ee24a">

For the `defaultValue`, we should give `Values: E.g. ["1", "2"]`

For the `value`, we should give `Type: string[]` and  `Values: E.g. ["1", "2"]`

They are just minor typos anyway. Really thanks for your efforts!
