### ISSUE TITLE
[Bug]: Block templates use an old version of heroicons

### ISSUE THREAD

**Issue by hulk-konen** [tremorlabs/tremor-npm#627]
### Tremor Version

3.6.0

### Link to minimal reproduction

https://www.tremor.so/blocks/charts

### Steps to reproduce

For example: Card + Tracker + Line Chart uses:

import { CheckCircleIcon } from "@heroicons/react/solid";

Should be since heroicons v 2.0:

import { CheckCircleIcon } from "@heroicons/react/24/solid";

Also there are some old icon names on the other blocks. 

### What is expected?

No errors

### What is actually happening?

Errors

**Comment by severinlandolt** [comment]
Hi! That is actually correct, we like the old icons better than the new ones. This is also noted in installation section: 

> To use the icons in our Blocks we install the heroicons library. To get the same icons from the examples, we use version 1.0.6.

**Comment by hulk-konen** [comment]
Ok!
