### ISSUE TITLE
[Feature]: TextInput should have onValueChange props

### ISSUE THREAD

**Issue by FrederickOB** [tremorlabs/tremor-npm#628]
### What problem does this feature solve?

Controlled state for the TextInput component 

### What does the proposed API look like?

   <TextInput
                    icon={SearchIcon}
                    placeholder="Search by order ID or phone number"
                    enableClear
                    onValueChange={(value) => {
                      setSearch(value);
                    }}
                    value={search}
                  />

**Comment by subhajit20** [comment]
Hey @FrederickOB  would like to work on it.
Could you assign it to me ?

**Comment by jzfrank** [comment]
It would certainly be nice to have this feature. But before this feature is released, there are workarounds by using `onChange`:

```javascript
<TextInput
  onChange={(e) => {
    setSearch(e.target.value);
    }}
  value={search}
  />
```

**Comment by jzfrank** [comment]
> Hey @FrederickOB would like to work on it. Could you assign it to me ?

I think you should @ the members of Tremor. 

Do it for you. 
@mitrotasios @severinlandolt @christopherkindl
