### ISSUE TITLE
DefaultProps Warning

### ISSUE THREAD

**Issue by jcbraz** [tremorlabs/tremor-npm#629]
Greetings,

Is there a solution to solve this warning or a new version to the package?

Currently, I'm using the LineChart, BarChart and all the wrapping components like Card, Col, Title, ...

![image](https://github.com/tremorlabs/tremor/assets/73346618/ee845860-db26-4555-95d0-b94e3d85a52f)

**Comment by ghost** [comment]
+1, I'm seeing this error when using Bar charts on a new NextJS project.

**Comment by severinlandolt** [comment]
Hey there, it's an issue [over at Recharts](https://github.com/recharts/recharts/issues/3615) but the team is behind it. We will update as soon as an update is released.

**Comment by ckifer** [comment]
Hijacking this for a plug - Recharts needs more contributors/help if anyone over here wants to contribute :)

(But trying to address this asap)

**Comment by ckifer** [comment]
Should be resolved in 2.8.0

**Comment by ghost** [comment]
I can confirm that this error is no longer showing for me after doing `npm update`. Thanks @ckifer !

**Comment by Elmosh** [comment]
Just an update, the warning is back, but I see @ckifer already working on a fix.

**Comment by ckifer** [comment]
Its probably a different component. There are a few components we can't fix yet due to unfortunate legacy implementation details of recharts. Known issue and close to the top of the list of things to fix though!
