### ISSUE TITLE
[Bug]: Chart cannot render correctly in responsive mode

### ISSUE THREAD

**Issue by hh54188** [tremorlabs/tremor-npm#632]
### Tremor Version

3.6.5

### Link to minimal reproduction

https://www.npmusage.com/

### Steps to reproduce

- Use Chrome DevTools to enter responsive mode.
- Access the website [https://www.npmusage.com/](https://www.npmusage.com/)
- Enter "react" into the left top input 

### What is expected?

This is the screenshot video in Desktop mode:

[001.webm](https://github.com/tremorlabs/tremor/assets/1318911/46649d52-06bc-4b3f-ae83-b902e8811046)

### What is actually happening?

This the screenshot video in responsive mode, no chart rendered:

[002.webm](https://github.com/tremorlabs/tremor/assets/1318911/78b0eadf-a4ac-405b-b0db-dd6ac300cb9f)

### What browsers are you seeing the problem on?

Chrome

### Any additional comments?

However, the chart seems rendered but not showed in the browser, because if I set the viewport bigger, it can show the chart correctlly

[003.webm](https://github.com/tremorlabs/tremor/assets/1318911/a14709fe-3e7b-43fb-a17f-1ef7287f6d37)

My code is simple:

```javascript
export default function TrendChart() {
  const {
    data,
    isLoading,
  } = useStore();

  const valueFormatter = number => `${(number * 100).toFixed(3)}%`;
  let categories = [];
  if (data && data.length) {
    categories = Object.keys(_.pickBy(data[0], (value, key) => {
      return key !== 'totalRepo' && key !== 'calDate'
    }))
  }

  return (
    <div className='h-full'>
      {isLoading && <LoadingCircle></LoadingCircle>}
      {!isLoading && <LineChart
        className="h-full"
        data={data}
        index="calDate"
        categories={categories}
        valueFormatter={valueFormatter}
        showLegend={true}
        startEndOnly={true}
      />}
    </div>
  )
}
```

**Comment by severinlandolt** [comment]
Hey, @hh54188! It's necessary to set a height on your chart.

> Note: For the height, a number value has to be set (e.g, h-72, or h-[500px]. Keep in mind that h-full won't work.)

See the usage example in our doc: https://www.tremor.so/docs/components/area-chart

**Comment by hh54188** [comment]
Thanks for that! Problem solved!
