### ISSUE TITLE
Redundant tailwind utility class code on the documentation.

### ISSUE THREAD

**Issue by uy-scuti100** [tremorlabs/tremor-npm#633]
On the " Your first dashboard" page, there seem to be an unnecessary repetition of tailwind utility class code. On the className given to the <main></main> tag , its written as " px-12 py-12 " i think its better as "p-12"

<main className="px-12 py-12">
      <Title>Dashboard</Title>
      <Text>Lorem ipsum dolor sit amet, consetetur sadipscing elitr.</Text>

      <TabGroup className="mt-6">
        <TabList>
          <Tab>Overview</Tab>
          <Tab>Detail</Tab>
        </TabList>
        <TabPanels> ...........

**Comment by severinlandolt** [comment]
Fixed!
