### ISSUE TITLE
[Feature]: Improve readability of selected items in <MultiSelect/>

### ISSUE THREAD

**Issue by christopherkindl** [tremorlabs/tremor-npm#635]
### What problem does this feature solve?

Show selected items in `<MultiSelect/>` instead of summarizing the selection ("3 selected", see current version: https://www.tremor.so/docs/components/select). This improves accessibility / user-friendliness as selected items can be directly seen in the input field.

### What does the proposed API look like?

![MultiSelect](https://github.com/tremorlabs/tremor/assets/53372002/2ea61c67-3fda-4693-a987-7e9184804b4d)

**Requirements:**
- Each selected item can be deselected via close button 
- global close button allows to deselected all items
- Fixed width for selected items with `truncate` 
- Selected items are horizontally scrollable

**Comment by jzfrank** [comment]
Hi Christoph, I would like to be assigned for this feature.

**Comment by anmol-fzr** [comment]
Hi Christoph, hope you're well! Kindly assign the task to me on GitHub? Excited to contribute!

**Comment by christopherkindl** [comment]
Thank you both! Assigned it to @jzfrank because he was first, but feel free to tackle it together :)

**Comment by severinlandolt** [comment]
https://github.com/tremorlabs/tremor/releases/tag/v3.7.0
