### ISSUE TITLE
[Feature]: There should be a error and errorMessage field (props) for Select Element, something similar to TextInput error and errorMessage

### ISSUE THREAD

**Issue by anmol-fzr** [tremorlabs/tremor-npm#636]
### What problem does this feature solve?

Currently the Select Elements don't have  error and  errorMessage field .

**Comment by shivam-jainn** [comment]
Can i work on this?

**Comment by severinlandolt** [comment]
Hey there! We decided to not taking this further. Thank you for your request and happy coding ⌨️
