### ISSUE TITLE
[Feature]: Ability to add a dotted line on Area chart

### ISSUE THREAD

**Issue by gondar00** [tremorlabs/tremor-npm#637]
### What problem does this feature solve?

Issue Description:
As of now, the area chart component in our application lacks the capability to display dotted lines. This feature enhancement request pertains to the inclusion of dotted lines within the area chart, providing users with the ability to visualize data trends more effectively.

Expected Behavior:
When configuring an area chart, users should be able to designate specific lines as dotted lines. This can be achieved by introducing a parameter in the chart configuration that controls the line style. The dotted line style should be visually distinct from solid lines, ensuring clear differentiation between data series where the chart is being built for prediction purposes.

**Comment by mbauchet** [comment]
#579 could probably do the trick ?

**Comment by gondar00** [comment]
Thanks @mbauchet! Exactly what I was looking for.

**Comment by gondar00** [comment]
Closing as dup of #579
