### ISSUE TITLE
[Bug]: NumberInput does not pass event to onChange when clicking stepper

### ISSUE THREAD

**Issue by jzfrank** [tremorlabs/tremor-npm#645]
### Tremor Version

3.6.6

### Link to minimal reproduction

https://tremor-number-input-bug-demo.vercel.app/

### Steps to reproduce

Click on the stepper buttons to increase/decrease the value.
Say you clicked up for 5 times, the value should be 5.
Now, click your mouse elsewhere on the page.

### What is expected?

The value should be nonzero, but it is 0.

### What is actually happening?

The value should be nonzero, but it is 0.

### What browsers are you seeing the problem on?

Chrome

### Any additional comments?

To be fair, this bug could be avoided if using `onValueChange` handler. 

However, in some scenarios people may need to get the event (as `onChange` handler is exposed) as dealing with normal html input element. 

I was upgrading `input` to `NumberInput`, naturally reused `onChange` field. Then the bug occurred,

**Comment by jzfrank** [comment]
I had a hunch that this is caused by `BaseInput` 

```javascript
        <input
          ref={mergeRefs([inputRef, ref])}
// ...
```

where the `mergeRefs` could hide the `onChange` event propagating to `NumberInput`'s `ref`. 

As a side note, why do we need to maintain an internal ref, instead of just passing them down the way?

**Comment by christopherkindl** [comment]
Hi @jzfrank, fair point and thanks for identifying this issue. Feel free to open a PR and suggest your solution!

**Comment by severinlandolt** [comment]
Thank you for the thorough issue and the corresponding PR. Great work!
