### ISSUE TITLE
[Bug]: Evenly spaced labels/ticks on axis

### ISSUE THREAD

**Issue by christopherkindl** [tremorlabs/tremor-npm#647]
### Tremor Version

v3.6.6

### Link to minimal reproduction

n/a

### Steps to reproduce

see image below

### What is expected?

Ticks/labels should be evenly spaced along the axis.

### What is actually happening?

There are some cases in which the gap between two labels is larger than the rest of it. This also happens on the y-axis. According, to the Recharts team this has something to do with the `padding` prop in their `<XAxis/> / <YAxis/>` component.  This is a weird bug/behavior that probably requires changes in Rechart's root code. We posted the issue in their repo as well. If anyone in our community has a smart solution for this, you would be our star! ⭐  

![evenly_spaced](https://github.com/tremorlabs/tremor/assets/53372002/dbc52b4d-faa7-453e-9ddf-3c49370f829a)

**Comment by omriluz** [comment]
Hey I explored it a bit and, it seems that this whole section is made out of SVG? anyway it seems like the calculation is wrong for the spacing since there is no flex or grid layout it relies solely on Math, Just a lead for anyone that wants to take a crack as well, I'll keep trying

**Comment by christopherkindl** [comment]
Hi @omriluz, thanks for your expertise here! 👍

**Comment by christopherkindl** [comment]
We moved our feature request for Recharts to an another, existing issue: https://github.com/recharts/recharts/issues/3305

**Comment by christopherkindl** [comment]
Recharts pushed hard for this feature and it will be released soon. We just tested the new option, and it looks muuuuch better!

https://github.com/recharts/recharts/pull/3768
