### ISSUE TITLE
[Bug]: Multiselect does not search with spaces

### ISSUE THREAD

**Issue by ivantypes** [tremorlabs/tremor-npm#650]
### Tremor Version

3.6.6

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-8m4gn4?file=src%2Fmain.tsx

### Steps to reproduce

Try searching with spaces.

### What is expected?

The input value should have spaces.

### What is actually happening?

The input value does not have the spaces added by the user.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Firefox, Other

### Any additional comments?

N/A

**Comment by christopherkindl** [comment]
oh, thanks for spotting this, Ivan!
