### ISSUE TITLE
[Bug]: Improve "Today" marker in DatePicker / DateRangePicker

### ISSUE THREAD

**Issue by christopherkindl** [tremorlabs/tremor-npm#653]
### Tremor Version

v3.7.1

### Link to minimal reproduction

https://www.tremor.so/docs/components/daterangepicker

### Steps to reproduce

see current date picker version on doc website

### What is expected?

The style of today marker should be more distinct compared to the styling of the selected range/date
![Datepicker](https://github.com/tremorlabs/tremor/assets/53372002/499a8d5a-eab2-4367-a4b6-aa359e4345dc)

We are not sure about the new styling yet, so we want to ask the community. Please let us know which option you prefer! 🙂

### What is actually happening?

Current styling causes confusion as it can imply that the markers represents the selection of a date.

**Comment by christopherkindl** [comment]
Some input from @Sh4yy (Creator of LogSnag):

_"I'd say keep the background colors and try to differenciate it somehow. A is a bit hard to see, the contrast is minimal, and B reminds me that I have some event on that day (think of Apple's calendar)"_

**Comment by mbauchet** [comment]
Maybe underline the actual day could be great

**Comment by zvolcsey** [comment]
Hi! I like this repo. I think the current version with blue background would be great, like in the Google Calendar.
![calendar](https://github.com/tremorlabs/tremor/assets/41576384/2bfe2a79-0749-4f27-942e-a5974c8b18f9)

**Comment by ivantypes** [comment]
Bold is probably the most elegant and clean way, but it will depend a lot on how the component is used.

Certain predefined styles could be provided in the API. For example, bold, dotted... and any others you want to share, even changing the colour between all the existing ones in [Colors](https://github.com/tremorlabs/tremor/blob/225ae6b6739ba8dd4a516e9ef435c95c046c6d5f/src/lib/inputTypes.ts#L56). And it could be the user who chooses between all the available ones, just like in the variants of some components or in the curve type of the charts.

Have a nice day!

**Comment by severinlandolt** [comment]
+1 for bold

**Comment by jaipaljadeja** [comment]
I would prefer bold as well, looks clean and minimal.

![image](https://github.com/tremorlabs/tremor/assets/61868840/6bbcbddb-1848-4cff-b18f-7f57a58f1a9e)

Also if possible can I take this issue? it will be my first open source contribution : )

**Comment by christopherkindl** [comment]
Let's aim for bold. Whoever wants to tackle this issue, please comment below and we will assign you. Many thanks for your work in advance!

**Comment by jaipaljadeja** [comment]
I am just starting with open source contribution. I would love to take this issue as my first ever contribution 😬

**Comment by christopherkindl** [comment]
Awesome, the stage is yours! 🙂

**Comment by christopherkindl** [comment]
If you need any help, reach out to us on tremor.so/slack
