### ISSUE TITLE
[Bug]: Multiselect is toggling when deleting single items 

### ISSUE THREAD

**Issue by mbauchet** [tremorlabs/tremor-npm#654]
### Tremor Version

3.7.1

### Link to minimal reproduction

[Tremor.com](https://www.tremor.so/docs/components/select)

### Steps to reproduce

Select multiple items and then delete items one by one. The select options are toggling.

### What is expected?

Keep the actual state (if open keep the menu open, if closed keep it closed)

### What is actually happening?

It toggle

**Comment by christopherkindl** [comment]
Funny, I just noted this weird behavior as well, after using it in a real-world example. Feel free to submit a PR!

Thanks for notifying!

**Comment by severinlandolt** [comment]
The direction I would have taken, curious about what you are thinking of @mbauchet 

```diff
onClick={(e) => {
+                             e.preventDefault();
                              const newValue = value.filter((v) => v !== option.props.value);
                              onValueChange?.(newValue);
                              setSelectedValue(newValue);
                            }}
```

**Comment by mbauchet** [comment]
I was exactly thinking about that! 😄
I'm actually on holliday without computer, so I can't do it before next weekend 😉
