### ISSUE TITLE
[Feature]: Is there a Skeleton / Loading function?

### ISSUE THREAD

**Issue by biapar** [tremorlabs/tremor-npm#657]
### What problem does this feature solve?

Skeleton / Loading function.

**Comment by severinlandolt** [comment]
Hi @biapar! No, this is something you would have to implement yourself.

**Comment by thomasmcinnis** [comment]
@biapar here is a really low-tech solution I use in my app with Tremor. You can add these three tailwind classes to anything with a height and width (in this case a Card in a Grid layout

`<Card className='bg-gray-300 dark:bg-gray-700 animate-pulse'>`

**Comment by biapar** [comment]
Thanks. I'll try it.
