### ISSUE TITLE
[Bug]: Minor typo in Theming documentation

### ISSUE THREAD

**Issue by onlyphantom** [tremorlabs/tremor-npm#658]
### Tremor Version

3.6.6

### Link to minimal reproduction

-

### Steps to reproduce

In the documentation [for Theming](https://www.tremor.so/docs/getting-started/theming), there exist a minor typo for `dark-tremor.content.DEFAULT`'s comment. 

```
module.exports = {
  // ...
  theme: {
    // ...
    extend: {
      colors: {
      // ...
        "dark-tremor": {
          ...,
          content: {
            subtle: "#4b5563", // gray-600
            DEFAULT: "#6b7280", // gray-600
            emphasis: "#e5e7eb", // gray-200
            strong: "#f9fafb", // gray-50
            inverted: "#000000", // black
          },
        },
      },
```

`4b5563` is gray-600 but `6b7280` is actually gray-500. 

### What is expected?

The correct comment for these values, so it's easier to do a site-wide replacement using Find All etc. in code editors. 

### What is actually happening?

In the documentation [for Theming](https://www.tremor.so/docs/getting-started/theming), there exist a minor typo.

```
module.exports = {
  // ...
  theme: {
    // ...
    extend: {
      colors: {
      // ...
        "dark-tremor": {
          ...,
          content: {
            subtle: "#4b5563", // gray-600
            DEFAULT: "#6b7280", // gray-600
            emphasis: "#e5e7eb", // gray-200
            strong: "#f9fafb", // gray-50
            inverted: "#000000", // black
          },
        },
      },
```

`4b5563` is gray-600 but `6b7280` is actually gray-500.

**Comment by severinlandolt** [comment]
Fixed, thank you!
