### ISSUE TITLE
[Feature]: <TextArea/> component

### ISSUE THREAD

**Issue by christopherkindl** [tremorlabs/tremor-npm#670]
### What problem does this feature solve?

`<TextArea/>`has been requested by a lot of users. Tremor team is also reworking their entire block section where they find a need for this component.

### What does the proposed API look like?

Please use HTML's native [<textarea/>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) component. Styling same as in other input elemens, such as `<TextInput/>`.

Explicit props:
- placeholder?: string
- error?: boolean
- errorMessage?: string
- disabled?: boolean
- maxLength?: number

other native props, such as `autocomplete`, `autofocus` or `required`, should be passed via `...other` (see `<TextInput/>`). 

Please comment below if you want to work on this issue and we will assign you. Many thanks for your contribution in advance.

![_TextArea](https://github.com/tremorlabs/tremor/assets/53372002/cce5a9b8-4821-4aad-8d23-a30cd7bec372)

**Comment by jorgeramirezamora** [comment]
I can take this one @christopherkindl

**Comment by christopherkindl** [comment]
Thanks so much, @jorgeramirezamora!

**Comment by christopherkindl** [comment]
Hi @jorgeramirezamora, just wanted to check in whether you still want to tackle this issue? Otherwise happy to re-assign it :)

**Comment by jorgeramirezamora** [comment]
> Hi @jorgeramirezamora, just wanted to check in whether you still want to tackle this issue? Otherwise happy to re-assign it :) 

Hey @christopherkindl, yeah sorry. I hope to finish by THE end of this week.

**Comment by christopherkindl** [comment]
@jorgeramirezamora Awesome, thank you!

**Comment by Harsh-0986** [comment]
Is this issue resolved?

**Comment by lucafaggianelli** [comment]
hey @jorgeramirezamora @christopherkindl how's it going with this issue? I'll be happy to work on it if you need help
