### ISSUE TITLE
[Bug]: Improve styling in <Tabs> for variant solid

### ISSUE THREAD

**Issue by christopherkindl** [tremorlabs/tremor-npm#671]
### Tremor Version

v3.7.4

### Link to minimal reproduction

https://www.tremor.so/docs/components/tabs

### Steps to reproduce

Tabs > See second version in hero section

### What is expected?

**For `solid` version only:**
- Change padding in outer container to p-0.5 (better aesthetics)
- Use `tremor-content-emphasis` instead of `tremor-brand` for selected tab

<img width="454" alt="_github" src="https://github.com/tremorlabs/tremor/assets/53372002/fb968d61-ef8d-49f4-a0d6-8ef3f09cbefe">

### What is actually happening?

n/a

**Comment by ManavJoshi111** [comment]
@christopherkindl I would like to work on this

**Comment by christopherkindl** [comment]
Assigned - Happy coding!
