### ISSUE TITLE
[Feature]: Preact support

### ISSUE THREAD

**Issue by NuroDev** [tremorlabs/tremor-npm#676]
### What problem does this feature solve?

React is one of the most popular frameworks out there. However it of course does have its quirks, which is why some may prefer to use drop in replacements like `preact`. As such it would be amazing if there was a 1st party Tremor Preact package (`@tremor/preact`).

In my use case, I am using [Deno Fresh](https://fresh.deno.dev) which uses [Preact](https://preactjs.com) instead of React & as such there is some issues with some packages, many of which [can be worked around](https://github.com/denoland/fresh/issues/1395). However I have tried a fair few methods to get Tremor to work with Preact in a Deno environment but have had no luck due to this error:
```bash
error: Uncaught TypeError: A is not a function
    at https://esm.sh/v132/dom-helpers@3.4.0/denonext/class/addClass.js:4:1202
    at https://esm.sh/v132/dom-helpers@3.4.0/denonext/class/addClass.js:4:452
    at https://esm.sh/v132/dom-helpers@3.4.0/denonext/class/addClass.js:4:1483
```

This is a big ask for this one niche use case considering it will require a lot more additional work, maintenance, etc, but I thought I would ask to see what the Tremor would respond to the possibility of creating forked versions of Tremor for other frameworks, like [what Lucide does](https://lucide.dev/packages).

If this is too much of an ask & it is better I seek trying to get Deno / Preact compat working instead I understand 🙂

**Comment by severinlandolt** [comment]
Hi @NuroDev, 

Sorry for getting back to you so late.  So, thanks a bunch for opening this issue about a Tremor Preact package! We totally get how it could help in a Deno environment. Unfortunately, we're a bit strapped for resources and can’t dive into this niche feature right now. Maybe check out some alternative fixes? And hey, if you or anyone else finds a cool workaround, we’re all ears! Thanks for being part of the Tremor community!
