### ISSUE TITLE
[Feature]: ColSpan and RowSpan in Table

### ISSUE THREAD

**Issue by LucasSequeDev** [tremorlabs/tremor-npm#677]
### What problem does this feature solve?

Hello, I hope you have a great day.

I think it should be interesting to add colspan and rowspan properties in TableHeaderCell.

Thanks!

### What does the proposed API look like?

Create an advanced tables with the tremor components

**Comment by LucasSequeDev** [comment]
add the topic with interesting
https://github.com/tremorlabs/tremor/discussions/89

**Comment by severinlandolt** [comment]
Hi there, 
Thank you for your suggestion on enhancing the <TableHeaderCell /> component! While the idea is appreciated, we're currently prioritizing simplicity in our components. Adding colspan and rowspan might complicate its usage. We truly value your contributions and are looking forward to more in the future!
