### ISSUE TITLE
[Feature]: <StraightAnglePie/> Component

### ISSUE THREAD

**Issue by srejitk** [tremorlabs/tremor-npm#679]
### What problem does this feature solve?

Requesting for a Straight angle pie component which can be an extension of the current DonutChart component.

Which can be achieved by opening up the **startAngle** and **endAngle** for customization.

> 

### What does the proposed API look like?

The following would be the 2 options I believe we can take this forward:

1. Open up the props **startAngle** & **endAngle** of the current `<DonutChart />` Component
2. Create a new component for the same

Here's an example from the recharts docs :

 
![image](https://github.com/tremorlabs/tremor/assets/13405260/60265518-4278-4820-98bf-3e0381a9c541)

If approved, I'm ready to build and contribute to the same. Thank you!

**Comment by severinlandolt** [comment]
Duplicate of #474

**Comment by srejitk** [comment]
> Duplicate of #474

Is this being worked on? Or is open for contribution?

**Comment by severinlandolt** [comment]
There is already a [PR for it](https://github.com/tremorlabs/tremor/pull/494), but this feature is not a priority right now, hence not merged but still open.

**Comment by severinlandolt** [comment]
Cf. #474
