### ISSUE TITLE
[Feature]: <Switch/>

### ISSUE THREAD

**Issue by christopherkindl** [tremorlabs/tremor-npm#682]
### What problem does this feature solve?

<Switch/> has been requested by a lot of users. Tremor team is also reworking their entire block section where they find a need for this component.

### What does the proposed API look like?

Please use [headless' switch](https://headlessui.com/react/switch) for the underlying logic. See styling in the image below.

Explicit props:

- checked?: (value: string) => void;
- onChange?: (value: string) => void;
- color?: string // only for isChecked color
- id?: string
- name?: string
- error?: boolean
- errorMessage?: string
- disabled?: string

![_gh_switch](https://github.com/tremorlabs/tremor/assets/53372002/e4d59e4c-e030-4feb-ad7d-ebd0c4644c8d)

**Comment by mrkirthi-24** [comment]
Hi @christopherkindl, I would like to work on this issue

**Comment by christopherkindl** [comment]
Hi @mrkirthi-24, awesome, thank you! We just assigned you 🙂

**Comment by mrkirthi-24** [comment]
Hey @christopherkindl I need some help to start working on this issue. I don't know where to start

**Comment by nicolasVenard** [comment]
Hey, I would also like to work on this issue, is that possible? Or do I have to find another one that's not assigned? 🙂

**Comment by mrkirthi-24** [comment]
@nicolasVenard I am working on this.

**Comment by christopherkindl** [comment]
@mrkirthi-24 just wanted to check-in whether you still want to tackle this? Otherwise happy to re-assign :)

**Comment by mrkirthi-24** [comment]
I apologize for the delay. I am working on it.

**Comment by christopherkindl** [comment]
Awesome, thank you! :)

**Comment by mrkirthi-24** [comment]
Hi @christopherkindl, I think disabled should be boolean?
And what should i do if explicit props "checked and onChange" are same as headless ui switch default props ? Should i change it??

**Comment by mrkirthi-24** [comment]
I am sorry but I cannot solve it

**Comment by mbauchet** [comment]
@AlexRousseau92

**Comment by AlexRousseau92** [comment]
Hello, i would like to work on this issue :)
