### ISSUE TITLE
[Bug]: weird typescript error when mapping SearchSelectItems in SearchSelect component

### ISSUE THREAD

**Issue by sudhamjayanthi** [tremorlabs/tremor-npm#686]
### Tremor Version

@tremor/react@3.7.2

### Link to minimal reproduction

https://codesandbox.io/p/sandbox/still-voice-q9sxfn?file=%2Fpages%2F_app.tsx%3A7%2C1

### Steps to reproduce

- Setup a NextJS + Tailwind project in Typescript 
- (Ofc) Install tremor labs
- Use SearchSelect component anywhere you like
- Add a SearchSelectItem component inside it
- Now, map over a list of strings to generate some more SearchSelectItem components below the previously created SearchSelectItem component
- And then you'll see a type error like this for the line where you use map
```
Type error: Type 'Element[]' is missing the following properties from type 'ReactElement<any, string | JSXElementConstructor<any>>': type, props, key
```

OR 

Just checkout the above reproduction link and run `npm run build`

### What is expected?

It works without any errors

### What is actually happening?

It throws the error during build process (`npm run build`)

### Any additional comments?

Also, I figured this error only happens when you have the first single SearchSelectItem seperately along AND the rest of the SearchSelectItems through map. Commenting out either one of those fixes the bug — quite weird — but I need to have both of them since currently there is no way to clear the input otherwise. 

If this would take time to figure out and fix... I hope that atleast #681, where I extended the `enableClear` functionality for SearchSelect, could be merged so that I get away by just using the map. Thanks! :)

**Comment by severinlandolt** [comment]
Interesting, will take a look at this next week

**Comment by severinlandolt** [comment]
Hi @sudhamjayanthi, may you try the latest beta and tell me if the mapping is now working for you?

```
npm i @tremor/react@3.11.1-beta.2
```
