### ISSUE TITLE
[Feature]: <ProgressCircle /> component

### ISSUE THREAD

**Issue by christopherkindl** [tremorlabs/tremor-npm#687]
### What problem does this feature solve?

Introduction of a new component to visualize progress in new ways as opposed to our data bars.

### What does the proposed API look like?

Component to be coded only using html / svg. **Proportion and size details** can be found in the image below.

Explicit props:

- **value:** number [0-100]
- **size?:** string ["xs", "sm" (default), "md", "lg", "xl"]
- **color?:** string // please use same color mapping logic as in [ProgressBar](https://github.com/tremorlabs/tremor/blob/cbd580a12c5972ef3b1ac5a134e1a8d68d7dd933/src/components/vis-elements/ProgressBar/ProgressBar.tsx#L11)
- **showLabel?:** boolean
- **showAnimation?:** boolean // please use CSS animation (fill up to threshold, same as in ProgressBar)
- **tooltip?:** string // please use same logic as in [Icon](https://www.tremor.so/docs/components/icons)

for `className` prop it should be possible to adjust the size via tailwind heights (e.g. h-10)

<img width="2335" alt="ProgressCircle" src="https://github.com/tremorlabs/tremor/assets/53372002/cf85856b-a2f6-4626-9b0d-315c53dbf861">

**Comment by jzfrank** [comment]
I would like to be assigned for this one ;)

**Comment by srejitk** [comment]
I would love to be assigned this one! :D
