### ISSUE TITLE
[Bug]: MultiSelectBox changed name in v3 and it's not in the migration guide

### ISSUE THREAD

**Issue by lucafaggianelli** [tremorlabs/tremor-npm#699]
### Tremor Version

v3

### Link to minimal reproduction

none

### Steps to reproduce

Just a missing point in the migration docs:

- `MultiSelectBox` and `MultiSelectBoxItem` have been renamed (dropped the Box)
- the `text` attribute is gone (I think has been replaced with children, but it's not clearly stated in the doc)

### What is expected?

To have MultiSelectBox in the migration guide

### What is actually happening?

MultiSelectBox doesn't exist anymore in v3 so the build fails

### What browsers are you seeing the problem on?

Chrome

**Comment by readikus** [comment]
Where is the migration guide? I'm just updating a bunch of dependancies, and hit these issues.

**Comment by lucafaggianelli** [comment]
here: https://www.tremor.so/changelog

scroll to the v3.0.0 tag

indeed a direct link from the home page to the migration guide for the v3 could be nice

**Comment by christopherkindl** [comment]
Thanks for spotting!

**Comment by severinlandolt** [comment]
Hope this helps, thanks!

https://www.tremor.so/docs/getting-started/v2-doc
