### ISSUE TITLE
[Feature]: Create a Tooltip component to use it on Tremor (or generic) components

### ISSUE THREAD

**Issue by lucafaggianelli** [tremorlabs/tremor-npm#700]
### What problem does this feature solve?

Some Tremor components already support tooltips, but sometimes you need a tooltip on a regular HTML component or on another React component or on a Tremor component that doesn't have the `tooltip` property. So in general it would be nice to extract the tooltip functionality into a component 

### What does the proposed API look like?

```tsx
<Tooltip content="hey click me">
  <Button/>
</Tooltip>
```

**Comment by severinlandolt** [comment]
Interesting, have you seen this somewhere else? I would like to check out a few examples :)

**Comment by mbauchet** [comment]
NextUI do it well
https://nextui.org/docs/components/tooltip

**Comment by lucafaggianelli** [comment]
Yep sure, here the Mui tooltip as well:

https://mui.com/material-ui/react-tooltip/

**Comment by abdullah-txfusion** [comment]
Would love a component like this! Much cleaner and extensible than having it as a prop in previous components.

**Comment by anmol-fzr** [comment]
I Would like to Contribute and fix this issue, please assign this to me

**Comment by severinlandolt** [comment]
Hi @lucafaggianelli, @abdullah-txfusion, @anmol-fzr! We won't address this issue in our NPM package. **However**: We recently launched Tremor Raw, a copy & paste library for React components. Here we have a [new Tooltip component](https://raw.tremor.so/docs/ui/tooltip), working exactly like the proposal! Thank you all for the discussion and happy coding ⌨️
