### ISSUE TITLE
[Bug]: Badge background in dark mode seems off

### ISSUE THREAD

**Issue by lucafaggianelli** [tremorlabs/tremor-npm#704]
### Tremor Version

v3

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-nxehxc?file=src%2FApp.tsx

### Steps to reproduce

Create a `<Badge>` and specify a color so it doesn't use the primary color, i.e. `<Badge color="emerald">`, then be sure to be in dark mode and to have a dark page background, i.e. `bg-slate-100 dark:bg-slate-950`.

### What is expected?

The badges should look nice both in light and dark mode

### What is actually happening?

In dark mode the background stays the same as in light mode and looks off, it's too whitish.

Here an example from my open source project https://github.com/lucafaggianelli/plombery:
![image](https://github.com/tremorlabs/tremor/assets/4471043/46ec13a4-9ff3-46be-93e3-c933e29deebd)

### What browsers are you seeing the problem on?

Chrome

### Any additional comments?

I'm using the default tailwind config found in tremor's docs

**Comment by christopherkindl** [comment]
Thanks, we are working on a facelift.

**Comment by DevGajjar28** [comment]
@lucafaggianelli use dark:bg-slate-950 only in div tag.it will give work in both light and dark mood good.

**Comment by lucafaggianelli** [comment]
> Thanks, we are working on a facelift.

Happy to help with a PR if you want

**Comment by christopherkindl** [comment]
Hi @lucafaggianelli, awesome! Feel free to submit a PR with a first draft that you might think looks better.

**Comment by bfowle** [comment]
Same problem with other types such as `ProgressBar`, when passing a `color` attribute.
This pattern is repeated in several types:
```
color
  ? getColorClassNames(color, colorPalette.lightBackground).bgColor
  : "bg-tremor-brand-faint dark:bg-dark-tremor-brand-faint",
```
Which gets the `lightBackground` shade (100) when passing a `color`.
Cheers~
