### ISSUE TITLE
[Feature]: shadcn ui theme

### ISSUE THREAD

**Issue by RhysSullivan** [tremorlabs/tremor-npm#705]
### What problem does this feature solve?

Given the popularity of shadcn/ui it could make sense to have an alternate theme for Tremor that lets you use the same Tailwind config that you use for shadcn/ui with Tremor without having to duplicate & change the styles to make them look like they belong to the same library

**Comment by severinlandolt** [comment]
This is not a feature planned on our development roadmap. Furthermore, Tremor operates with a private color scheme that is instrumental in activating the color="blue" properties for example, and in exemplifying the logic within the badges. Essentially, this entails two divergent conceptual approaches.
