### ISSUE TITLE
Pie charts / Donut charts

### ISSUE THREAD

**Issue by driaug** [tremorlabs/tremor-npm#71]
Hi lads!

Any chance of pie charts and donut charts being added in an upcoming update?

Are they on the roadmap, are they already kicked-off?

**Comment by christopherkindl** [comment]
Hi @driaug! Thank you for this suggestion. It is already on our roadmap, so just a matter of time!

In the current release, we just wanted to ship the most basic charts to find out whether the corresponding props (and the opinionated design) are appealing to end users.

**Comment by severinlandolt** [comment]
Released under #165
