### ISSUE TITLE
[Bug]: AreaChart/LineChart single data point renders blank chart

### ISSUE THREAD

**Issue by bfowle** [tremorlabs/tremor-npm#713]
### Tremor Version

3.8.0

### Link to minimal reproduction

N/A

### Steps to reproduce

Take any example `AreaChart`/`LineChart` from the docs and update the test data to only have one item in the array.
Previously (3.7.9 and before) there would be a set of dots shown by default in the middle of the chart.
In 3.8.0 it renders a blank chart, until hovering - which shows the dots again with the tooltip; de-hovering shows a blank chart again.

### What is expected?

The default behavior from <3.8.x, to show a single data point in the center with the dots rendered:
![tremor_3 7 9](https://github.com/tremorlabs/tremor/assets/240658/e66b8a1e-cacf-4aa8-9651-ebbaa9694f7d)

### What is actually happening?

3.8.x introduced a regression where the chart renders blank when only a single x-axis data point is given:
![tremor_3 8 0](https://github.com/tremorlabs/tremor/assets/240658/f3d4d287-7a96-4afe-9a2c-a8ad0abbe2f2)
...and upon hovering it shows them again:
![tremor_3 8 0-hover](https://github.com/tremorlabs/tremor/assets/240658/fd3108c4-250d-4cd8-bdc6-083615c7fe9b)

### What browsers are you seeing the problem on?

Chrome

**Comment by severinlandolt** [comment]
Hi @bfowle, released a beta which should fix this. Would you like to test in your app? 

```
npm i @tremor/react@3.8.1-beta.2
```

**Comment by bfowle** [comment]
Hi @severinlandolt -- yep, it looks like it fixes this issue. I noticed the dot used to be outlined only (not filled) until hovering (when it became filled), which isn't a big concern on my end, but figured I'd point that out in case it was unintended.
Thanks, cheers~
