### ISSUE TITLE
[Feature]: Allow adding custom Recharts elements as children

### ISSUE THREAD

**Issue by lymperis-e** [tremorlabs/tremor-npm#726]
### What problem does this feature solve?

Tremor really solves my hands when building dashboards, but the charts options may be limiting in certain cases. I need a simple LineChart but also need to add a simple, red, straight line, marking the max allowed value for the variable I am plotting. In recharts this is [fairly straight-forward](https://recharts.org/en-US/examples/LineChartWithReferenceLines). I believe other people might find this useful as well. 

I am proposing to include the **children** prop in the LineChart component, allowing the user to pass custom recharts nodes to the chart render method.

![Screenshot 2023-10-02 at 3 35 48 AM](https://github.com/tremorlabs/tremor/assets/76447999/a43b900c-0aa3-41d2-9a11-b61e7a084142)

### What does the proposed API look like?

Adding ``` children?: React.ReactNode;``` either to BaseChartProps or to LineChartProps, and including the *children* argument in the component's props and render method. 
On the user's end it looks like:
```
import { ReferenceLine } from "recharts";

<LineChart
            className="mt-6"
            data={chartData} 
             ...
          >
            <ReferenceLine y={maxAllowedValue} label="" stroke="red" />
</LineChart>
```

**Alternatively**, a verbose option called **referenceLines** may be added. It should accept a list of *ReferenceLineOptions* (y, label, stroke)

I've already implemented the **children** solution for my use case and will happily open a PR

**Comment by severinlandolt** [comment]
Heya! Thank you, @lymperis-e, for your proposal. We just discussed this. Initially, we were in favor of your idea, but it turns out this leads to unpredictable behavior. It's unclear which Recharts props can be passed and which cannot, depending on the Recharts components to which you want to add a prop. Hence, we thank you for your suggestions, but we won't move this forward.

Edit: Pasted from Slack:

> Here's a different perspective. Adding a new feature could mean you have to tweak small things on other parts like the margin or stackOffset, that are currently handled by Tremor, hence you ned even more flexibility. Ultimately, you could just use Recharts then, no abstractions,
