### ISSUE TITLE
Support for dark mode

### ISSUE THREAD

**Issue by rmrbytes** [tremorlabs/tremor-npm#73]
Hello:

This is more of a question. Is there support for dark mode? 

I tried `<Text color="blue" dark:color="green">Check</Text>` and it gave an error.

Thanks

**Comment by severinlandolt** [comment]
Hey! Thank you for your working with tremor. Much appreciated! 💫

At the time, we do not support any kind of dark mode. All components and their properties are designed for light mode only. Given the community feedback, we will evaluate the need for dark mode from time to time.

**Comment by rmrbytes** [comment]
Thanks @severinlandolt . I do find tremor to be a useful UI component library. I will look forward to the addition of darkmode to its wonderful capabilities

**Comment by ceIia** [comment]
sadge. i was almost ready to run `pnpm add @tremor/react` :(
looking forward to dark mode being implemented though!

**Comment by maakle** [comment]
Could you please either support the customizing of the background color of individual components? e.g. for the Card component. Then we could handle something like dark mode ourselves. 

Or perhaps even better that we could overwrite the default styles from you via the className or styles prop of the component and also use tailwinds syntax to add additional styles. e.g. something like this

```
<Card key={title} className="dark:bg-black">
   <Flex alignItems="items-start">
      <Block truncate={true}>
         <Text>{title}</Text>
         <Metric truncate={true}>{metric}</Metric>
      </Block>
      <BadgeDelta deltaType={deltaType} text={delta} />
   </Flex>
   <Flex marginTop="mt-4" spaceX="space-x-2">
      <Text truncate={true}>{`${progress}% (${metric})`}</Text>
      <Text>{target}</Text>
   </Flex>
   <ProgressBar percentageValue={progress} marginTop="mt-2" />
</Card>
```
