### ISSUE TITLE
[Feature]: Add an option to position the TextInput icon at the end

### ISSUE THREAD

**Issue by lucafaggianelli** [tremorlabs/tremor-npm#731]
### What problem does this feature solve?

Today when I add an icon to TextInput, it's always at the start/left position of the input container, though I'd like to move it at the end, typically when I use a button rather than an icon.

I have a workaround using the class `flex-row-reverse`, but that feels a bit hacky and risk to break if you add more HTML elements into the TextInput container:

```tsx
<TextInput
              className="flex-row-reverse"
              placeholder="Add a comment"
              icon={SendCommentButton}
/>
```

### What does the proposed API look like?

```tsx
<TextInput
              placeholder="Add a comment"
              icon={SendCommentButton}
              iconPosition="end"
/>
```

**Comment by severinlandolt** [comment]
Hi @lucafaggianelli, thank you for your proposal. We want to keep the input component very basic, so we won't be adding this particular feature anytime soon. As mentioned in the tooltip issue, there is a new Tremor Raw release, which adds a [improved version of the Input](https://raw.tremor.so/docs/inputs/input), where you have full control over this. Hint: Take a look at the variant where `type = "search"` 🔎
