### ISSUE TITLE
[Bug]: Documentation has wrong component import

### ISSUE THREAD

**Issue by motinados** [tremorlabs/tremor-npm#749]
### Tremor Version

latest

### Link to minimal reproduction

none

### Steps to reproduce

[The documentation for the DatePicker](https://www.tremor.so/docs/components/daterangepicker) has an incorrect component import. It's in the 'Usage example date picker' section.
![164939](https://github.com/tremorlabs/tremor/assets/69296148/2582ae79-0383-4b7c-ab8f-997287100433)

### What is expected?

```js
import { DatePicker } from "@tremor/react";
```

### What is actually happening?

```js
import { DateRangePicker } from "@tremor/react";
```

**Comment by christopherkindl** [comment]
Thanks!
