### ISSUE TITLE
[Bug]: Handle Chrome autofill styles on Password-type TextInput

### ISSUE THREAD

**Issue by bfowle** [tremorlabs/tremor-npm#751]
### Tremor Version

3.9.2

### Link to minimal reproduction

N/A

### Steps to reproduce

With the addition of the eye-icon button on `TextInput` with `type="password"` attribute, Chrome's autofill styles override the `input` element, but the toggle button shows a different color.

### What is expected?

For the background of the `input` and `button` elements to be the same.

It could also be helpful to have the ability to disable this button from being included, as an optional attribute.

### What is actually happening?

Chrome is applying the following style to the `input` element:
```
input:-internal-autofill-selected {
    appearance: menulist-button;
    background-image: none !important;
    background-color: -internal-light-dark(rgb(232, 240, 254), rgba(70, 90, 126, 0.4)) !important;
    color: fieldtext !important;
}
```

Tremor adds a `bg-transparent` style but that is overridden by the `!important` of the user stylesheet from Chrome.

---

Light mode:
![pw_light](https://github.com/tremorlabs/tremor/assets/240658/90da0fe5-fa93-4716-9760-64160c1ceb66)

Dark mode:
![pw_dark](https://github.com/tremorlabs/tremor/assets/240658/75e1f45f-df11-4c17-be04-189cb9f0233c)

Default (remove text that is autofilled):
![pw_default](https://github.com/tremorlabs/tremor/assets/240658/ba4ce9e9-140b-4e4e-87ba-a80514fb181c)

### What browsers are you seeing the problem on?

Chrome

**Comment by severinlandolt** [comment]
Having a hard time replicating this issue, could you please tell me:
* What Password Manager are you using?
* What operating system are you on?
Thank you!

**Comment by mbauchet** [comment]
![image](https://github.com/tremorlabs/tremor/assets/90607026/82f331b3-a4ca-49cd-a269-8fd377d1a237)
Got the same here, no password manager (default Google autofill), WIndows

**Comment by bfowle** [comment]
Same as @mbauchet 
No specific password manager; tested using Chrome in Windows / OSX / Ubuntu.

**Comment by severinlandolt** [comment]
Thanks! I tried adding the tailwind `autofill:bg-transparent` prefix, but it's not working in every browser. Since I do not want to mess with individual browser styles, I added a slight roundness to the input filed itself.

![CleanShot 2023-10-18 at 02 15 51@2x](https://github.com/tremorlabs/tremor/assets/41927988/f868be4c-a3bf-4677-af04-4b559fa83bd6)
