### ISSUE TITLE
[Bug]: Wrong ring color for Date(Range)Picker

### ISSUE THREAD

**Issue by mbauchet** [tremorlabs/tremor-npm#755]
### Tremor Version

3.9.2

### Link to minimal reproduction

https://www.tremor.so/docs/components/daterangepicker

### Steps to reproduce

focus datepicker

### What is expected?

use the tailwind config colors

### What is actually happening?

default blue for ring

### What browsers are you seeing the problem on?

Chrome

### Any additional comments?

![image](https://github.com/tremorlabs/tremor/assets/90607026/00c4d027-7335-4ec3-bf56-0ddadcda4479)

**Comment by severinlandolt** [comment]
Interesting, what is this green ring/border thing? Never have seen that 👀

**Comment by mbauchet** [comment]
I've override the default tailwind conf to have a green theme. The problem here is the blue ring
