### ISSUE TITLE
Add the source for the demo site

### ISSUE THREAD

**Issue by christopher-caldwell** [tremorlabs/tremor-npm#76]
Although the docs do have a walkthrough on how to create the dashboard from the demo site, it would be cool if I could just download or clone it, whatever the method you prefer. I just want to quickly copy / paste it and then tinker around. It looks great, and I want to replicate it quickly.

Great lib so far! Thanks

**Comment by christopherkindl** [comment]
Hi @christopher-caldwell, thank you for your comment. Yes, we will release it in the next days.

We just didn't want to have a big bang launch and make everything publicly available from day 0.

Thanks for trying tremor and your patience! 🙏

**Comment by jllosas** [comment]
has the source for the demo site been released?

**Comment by mitrotasios** [comment]
@huwyane not yet unfortunately, we are busy gathering feedback from our users at the moment but we will release it soon. If you're interested, follow [tremor](https://twitter.com/tremorlabs) on twitter to get the newest updates.

**Comment by jllosas** [comment]
https://www.tremor.so/docs/getting-started/demo-dashboard

"If you are still interested in using them in your first dashboard, have a look at the [GitHub repository](https://www.tremor.so/docs/getting-started/github.com/tremorlabs/demo.tremor.so) of the demo dashboard."

Any updates on when the source code for the demo dashboard will be released?

**Comment by christopherkindl** [comment]
Hi @huwyane, sorry for having to wait longer! End of next week as we will introduce some new components that make building the demo dashboard even easier along with some fixes of the input components! 🤞

**Comment by christopher-caldwell** [comment]
I think it's a little odd that it's taking this long to just release the source of the demo site. I'm not sure what there is to consider. FWIW, I have mentally moved on from using this library.

**Comment by joaqo** [comment]
Any updates on this? Love the idea of the library, but gotta admit it seems a bit odd that something that should be a simple copy paste is taking months.

Even if it doesn't use the latest components, it would be useful for me just to see how to place the datetime picker at the top right next to the title, like you do in your demo. Cheers!

**Comment by mitrotasios** [comment]
We have deprioritised this issue for now and will create a new demo dashboard some time in the future which will be open-sourced. 
In the meantime check out @tinybirdco's awesome dashboards, built with tremor and fully open-source:
* https://github.com/tinybirdco/web-analytics-starter-kit
* https://github.com/tinybirdco/log-analytics-starter-kit

**Comment by christopher-caldwell** [comment]
> We have deprioritised this issue for now and will create a new demo dashboard some time in the future which will be open-sourced. 
> 
> In the meantime check out @tinybirdco's awesome dashboards, built with tremor and fully open-source:
> 
> * https://github.com/tinybirdco/web-analytics-starter-kit
> 
> * https://github.com/tinybirdco/log-analytics-starter-kit

Does anyone else find this **really** weird? Just make a new repo and throw the source in there, it's really straightforward. Put a disclaimer that this may change or whatever is needed for people to be aware. 

At this point, it's shady to me that you can't just put the demo source out there.

**Comment by joaqo** [comment]
@mitrotasios Thanks for the links, was able to get some good ideas from those repos. Also congrats on the v2.0 release!

@christopher-caldwell Yeah, it is a bit odd. Having said that, they just released version 2.0 yesterday, and they may want to release a demo build for that. If I had had access to the demo when I asked for it, I would've started building my site based on it, and today it would've been totally outdated.

**Comment by nikhiljay** [comment]
Hey guys, I created this repo based on the Tremor demo dashboard and the [tremor docs](https://www.tremor.so/docs/getting-started/demo-dashboard). Feel free to use/contribute: https://github.com/nikhiljay/tremor-demo-dashboard

**Comment by christopher-caldwell** [comment]
Has the source been added anywhere? I couldn't find it.

**Comment by severinlandolt** [comment]
The guys form RedwoodJS have put together some resources around the demo dashboard:
[https://community.redwoodjs.com/t/build-dashboards-fast-with-tremor/4865](https://community.redwoodjs.com/t/build-dashboards-fast-with-tremor/4865)

**Comment by DenysVuika** [comment]
@severinlandolt thanks for composing the example. 

@mitrotasios to make the community members happy, you could have just put the example code somewhere in the repo, this one or separate. Yet you keep closing this issue for the second time with some weird comments.
