### ISSUE TITLE
[Bug]: Minor error in documentation of NumberInput

### ISSUE THREAD

**Issue by eehnsio** [tremorlabs/tremor-npm#760]
### Tremor Version

Latest

### Link to minimal reproduction

https://www.tremor.so/docs/components/number-input

### Steps to reproduce

**errorMessage** is described incorrectly in the description

![image](https://github.com/tremorlabs/tremor/assets/55081594/e08638b8-d8fb-45da-bc37-a0ed4df3cfe7)

![image](https://github.com/tremorlabs/tremor/assets/55081594/e91fce75-6b43-4f8b-88f7-29a2814b38d4)

### What is expected?

As per description the error message is supposed to be shown as a hover on the icon

### What is actually happening?

The text is shown under the NumberInput

**Comment by severinlandolt** [comment]
Thanks!
