### ISSUE TITLE
[Bug]:  Doc: Text Input, "Import TextInput" section no content

### ISSUE THREAD

**Issue by JonZhang3** [tremorlabs/tremor-npm#763]
### Tremor Version

doc

### Link to minimal reproduction

https://www.tremor.so/docs/components/text-input

### Steps to reproduce

<img width="1728" alt="image" src="https://github.com/tremorlabs/tremor/assets/53330083/5788c5c6-5f84-48be-ab0d-9acc29b71192">

### What is expected?

`import { TextInput } from "@tremor/react";`

### What is actually happening?

no content

### What browsers are you seeing the problem on?

Chrome

**Comment by severinlandolt** [comment]
Noted, will be fixed in the next release
