### ISSUE TITLE
[Feature]: TextInput supports 'enableClear'

### ISSUE THREAD

**Issue by JonZhang3** [tremorlabs/tremor-npm#766]
### What problem does this feature solve?

When using `TextInput`, if enter very long text, must either long press the delete button to delete or select all text before deleting.
If there has a clear button, like `Select`, it would improve the user experience.

### What does the proposed API look like?

For `TextInput`, add `enableClear` prop. 
`NumberInput` does not support `enableClear` prop.
The api:
```ts
export type TextInputProps  = Omit<BaseInputProps, "stepper" | "makeInputClassName"> & {
  ...
  enableClear?: boolean;
  ...
}
```

The ui:

Normal: 
<img width="478" alt="image" src="https://github.com/tremorlabs/tremor/assets/53330083/f7eee9f9-4b8f-4060-8741-b719a299d20d">

With Error:
<img width="477" alt="image" src="https://github.com/tremorlabs/tremor/assets/53330083/6297674b-0f75-47b1-bf27-728d4a4173a3">

With Disabled: 
<img width="478" alt="image" src="https://github.com/tremorlabs/tremor/assets/53330083/e5f86fa6-56d4-49d9-8860-979e52fba85f">

**Comment by Harsh-0986** [comment]
Shall I try on this issue?

**Comment by Lateef9** [comment]
can i try this issue?

**Comment by severinlandolt** [comment]
c.f. #769
