### ISSUE TITLE
[Bug]: negative values issue by BarChart

### ISSUE THREAD

**Issue by dimanoid22** [tremorlabs/tremor-npm#779]
### Tremor Version

v3

### Link to minimal reproduction

no-link.com

### Steps to reproduce

const chartdata2 = [
  { "X": "Topic 1", "Income": 890, "Outcome": -338, "Total": 538 }
];

<BarChart
      className="mt-2 h-[7rem] bg-gray-900 text-neutral-200"
      data={chartdata2} index="X"
      categories={["Income", "Outcome", "Total"]}
      colors={["emerald", "rose", "blue"]}
      stack={false} relative={false} allowDecimals={false}
      showLegend={false} showYAxis={false} showAnimation={true}
      layout="vertical"
    /> 

### What is expected?

to display a positive AND negative bar

### What is actually happening?

negative bar is not on screen

### What browsers are you seeing the problem on?

Chrome

### Any additional comments?

---

**Comment by severinlandolt** [comment]
Looking into it!

**Comment by severinlandolt** [comment]
Hey @dimanoid22, could you test your app with this beta version and report back if its working for you?

```
npm i @tremor/react@3.10.1-beta-fixnegativebar.1
```

**Comment by severinlandolt** [comment]
Hello! Can you test the newest beta, this issue should be solved now: 

```bash
npm i @tremor/react@3.10.1-beta-fixnegativebar.2
```
