### ISSUE TITLE
[Feature]: Navigation links

### ISSUE THREAD

**Issue by lucafaggianelli** [tremorlabs/tremor-npm#786]
### What problem does this feature solve?

Create a Link component to navigate the react app or to go to an external location.

Today the Button component doesn't accept an href property, of course we could use a normal HTML Anchor `<a>` or a ReactRouter / NextJS link but we would miss Tremor styling

### What does the proposed API look like?

We could create a new standalone component:

```tsx
<Link component={NextLink} href="/the/page">go to page</Link>
```

```tsx
<Link component="a" href="https://tremor.so">Tremor</Link>
```

or we can use the existing Button component to reuse its style and we simply add the
`component` property as many libs do:

```tsx
<Button component="a" href="https://tremor.so" target="_blank">Tremor</Button>
```

**Comment by rajdip-b** [comment]
Hey @lucafaggianelli, can you tell me what the `component={NextLink}` or the `component="a"` is supposed to do in the `Link` component API that you proposed?

**Comment by lucafaggianelli** [comment]
Hey, @rajdip-b the idea is to do something like this: let's take as an example the tremor Card component, I'd like to make it clickable to navigate to another page, so let's use the native `a` tag as example, but could be another routing system like React Router or NextJS.

I'd like to write this code:

```tsx
<Card component="a" href="http://google.com">
  My Card
</Card>
```

And this should render as a native HTML `<a>` tag instead of a `<div>`:
```html
<a href="http://google.com" class="tremor-card">
  My Card
</a>
```

Once you use the property `component="a"` then the properties of `<a>` will be available also on the `Card` component, like `target` for example.

Today the workaround for this is to add an onClick listener and programmatically navigate to the new page.

Of course we should identify which Tremor components should have this navigation feature.

**Comment by rajdip-b** [comment]
> Hey, @rajdip-b the idea is to do something like this: let's take as an example the tremor Card component, I'd like to make it clickable to navigate to another page, so let's use the native `a` tag as example, but could be another routing system like React Router or NextJS.
> 
> I'd like to write this code:
> 
> ```tsx
> <Card component="a" href="http://google.com">
>   My Card
> </Card>
> ```
> 
> And this should render as a native HTML `<a>` tag instead of a `<div>`:
> 
> ```
> <a href="http://google.com" class="tremor-card">
>   My Card
> </a>
> ```
> 
> Once you use the property `component="a"` then the properties of `<a>` will be available also on the `Card` component, like `target` for example.
> 
> Today the workaround for this is to add an onClick listener and programmatically navigate to the new page.
> 
> Of course we should identify which Tremor components should have this navigation feature.

Okay now it's clear to me. So should I get on with it, or should we first do the research about which components we should modify?

**Comment by christopherkindl** [comment]
Hi @lucafaggianelli and @rajdip-b,

thanks for the discussion. Not sure whether it makes sense to use such a universal approach for href / <a>. In our view, Links should be solved individually.


**Reasoning:**
Keep in mind that while nesting inline-level elements within an <a> element is common and valid, nesting block-level elements inside an <a> element is generally not recommended according to HTML specifications.

**Worst practice:** The example below would not comply with HTML standards(This would be our card case as discussed above):

```
<a href="https://www.example.com">
  <div>
    <h2>Title</h2>
    <p>Description</p>
  </div>
</a>

```

**Best practice:** In this case, I would do the following (notice how span line is used to make the link clickable across the entire card:

```
<Card className="relative">
  <h2>
    <a href={item.href} className="focus:outline-none">
      {/* Extend link to entire panel */}
      <span className="absolute inset-0" aria-hidden="true" />
      Title
    </a>
  </h2>
</div>
```

**Comment by lucafaggianelli** [comment]
> Hi @lucafaggianelli and @rajdip-b,
> 
> 
> 
> thanks for the discussion. Not sure whether it makes sense to use such a universal approach for href / <a>. In our view, Links should be solved individually.
> 
> 
> 
> 
> 
> **Reasoning:**
> 
> Keep in mind that while nesting inline-level elements within an <a> element is common and valid, nesting block-level elements inside an <a> element is generally not recommended according to HTML specifications.
> 
> 
> 
> **Worst practice:** The example below would not comply with HTML standards(This would be our card case as discussed above):
> 
> 
> 
> ```
> 
> <a href="https://www.example.com">
> 
>   <div>
> 
>     <h2>Title</h2>
> 
>     <p>Description</p>
> 
>   </div>
> 
> </a>
> 
> 
> 
> ```
> 
> 
> 
> **Best practice:** In this case, I would do the following (notice how span line is used to make the link clickable across the entire card:
> 
> 
> 
> ```
> 
> <Card className="relative">
> 
>   <h2>
> 
>     <a href={item.href} className="focus:outline-none">
> 
>       {/* Extend link to entire panel */}
> 
>       <span className="absolute inset-0" aria-hidden="true" />
> 
>       Title
> 
>     </a>
> 
>   </h2>
> 
> </div>
> 
> ```

Yes you're right about the nesting of in-line and block elements!

Ok so the card component is out of limits, but would you consider to add a link component to buttons and badges for example? Or do you have some workaround for those components?

Thanks!

**Comment by t3rminus** [comment]
I’m going to chime in and say it’s very much needed, at least on the \<Button> component.

I had to copy+paste the entire button source code into my application, changing the final element to Next’s \<Link>, so I could use the navigation library’s state-management and functionality with tremor-styled buttons.

Obviously this immediately broke when tremor was updated. It’s not a long-term maintainable option.

At the very least, we need to pass a custom element on a \<Button>. There are definitely other places, but this is a major shortcoming.

@christopherkindl Note that all block-level content is valid inside HTML5 standard anchor tags, so \<div> and \<h2> are absolutely valid, in the card example. It has been this way for almost 10 years: http://w3c.github.io/html-reference/a.html#a-changes 

\<a> is not only an inline element!
\<a href=“…”>\<div>\<h2>Text\</h2>\</div>\</a> is valid HTML5

**Comment by severinlandolt** [comment]
Hi all! Thanks @t3rminus, for adding this context–you are right. **Short answer:** We won't be fixing this anytime soon. 

**However**: We just launched Tremor Raw, a copy & paste library for React components. Here we have a [new version of the Button](https://raw.tremor.so/docs/ui/button), where you have full control over this. There are even two options on how you could go about this:

1. [Using the `asChild` prop](https://raw.tremor.so/docs/ui/button#example-create-anchor-with-aschild-pop)
```tsx
import { Button } from '@/components/Button';
  
export const ButtonAsChildExample = () => (
  <div className="flex justify-center">
    <Button asChild>
      <a href="#api-reference-button">API Reference</a>
    </Button>
  </div>
);
```
2. Importing the button styles and pass them to a link component
```tsx
import { buttonVariants } from "./Button"
// ...
<Link className={cx(buttonVariants({ variant: "secondary" }))}>
        Anchor element
</Link>
```

Happy coding! ⌨️
