### ISSUE TITLE
[Bug]: Using tremo and Material Tailwind together may cause some icon colors to become invalid

### ISSUE THREAD

**Issue by pickedbrian** [tremorlabs/tremor-npm#788]
### Tremor Version

Using tremo and Material Tailwind together may cause some icon colors to become invalid

### Link to minimal reproduction

https://github.com/creativetimofficial/material-tailwind?ref=material-tailwind

### Steps to reproduce

1.install termor and matterial tailwind
2.Code and preview
          <TextInput placeholder="password" value={password} onChange={(e) => setPassword(e.target.value)} onBlur={validateForm} error={Boolean(errors.password)} />

### What is expected?

If I remove withMT, the icons can revert to their normal state.
![image](https://github.com/tremorlabs/tremor/assets/100608404/81a6ea06-53b1-4675-97a6-4bf1720f6fb3)

### What is actually happening?

Once using withMT, some icons will lose their colors.
![image](https://github.com/tremorlabs/tremor/assets/100608404/cccc50f6-e7c3-46ce-9290-d9cb7add4018)
![image](https://github.com/tremorlabs/tremor/assets/100608404/6b64ef3f-1c5d-4f34-ae59-bf7e453e5bc4)

### What browsers are you seeing the problem on?

Chrome

### Any additional comments?

Should I ask this question at Material Tailwind or here?

seems that the color attribute has been overridden

material Tailwind config withMT:

1.https://github.com/creativetimofficial/material-tailwind/blob/main/packages/material-tailwind-react/src/utils/withMT.js

2.https://github.com/creativetimofficial/material-tailwind/blob/main/packages/material-tailwind-react/src/theme/base/colors.js

how to fix this plz

**Comment by severinlandolt** [comment]
Duplicate Cf. #535
