### ISSUE TITLE
[Feature]: OnClick handler for TrackerBlock

### ISSUE THREAD

**Issue by yujonglee** [tremorlabs/tremor-npm#799]
### What problem does this feature solve?

I want to add onClick handler for each item in Tracker.

### What does the proposed API look like?

```diff
export interface TrackerBlockProps {
  key?: string | number;
  color?: Color;
  tooltip?: string;
+ onClick?: Callable;
}
```

**Comment by severinlandolt** [comment]
@christopherkindl Makes sense to me, what do you think?

**Comment by christopherkindl** [comment]
lgtm! Will submit the PR with the updated design.

**Comment by severinlandolt** [comment]
+ This includes also a soft update of the styles.

**Comment by severinlandolt** [comment]
Hey @yujonglee, I've done some research on this. Initially, your request appears logical. I reviewed various status trackers like Betterstack and Openstatus and didn't find a single instance that includes an onClick functionality.

Could you elaborate on how you are using the tracker and what you aim to achieve with an onClick prop?

**Comment by severinlandolt** [comment]
Since this is not a common pattern, we decided to not implement that feature.
