### ISSUE TITLE
[Feature Request] : Add value notation for each bar in chart bars

### ISSUE THREAD

**Issue by severinlandolt** [tremorlabs/tremor-npm#805]
### Discussed in https://github.com/tremorlabs/tremor/discussions/804

<div type='discussions-op-text'>

<sup>Originally posted by **MenaiAla** November 10, 2023</sup>
Thank you Tremo team for this amazing project.

In fact, it helps us a lot in the data visualization of our product.

Our users are aged a little bit and I used Tremor to create a page to visualize the data and then allow them to download it as PDF.

However, I would ask if it's possible to annotate the value on the top of each bar.

This is Figma example:

![image](https://github.com/tremorlabs/tremor/assets/20143684/48ac939a-c32f-4c42-9bed-b7ca6eb57cc5)

Anf if it's possible in the current version, please could you provide an example because I'm prototyping based on your UI kit and I don't know if it's possible to do it with code.

Thank you</div>

**Comment by rajdip-b** [comment]
Hey! Might I give it a shot? @severinlandolt

**Comment by severinlandolt** [comment]
Hey all! I don't know where to start. Adding labels adds so much complexity that we currently don't see it feasible. Especially if labels are added, the line chart and scatter chart should get labels too–and those are even more complex. 

There is a reason why almost no SaaS has labels. And they know what data they can expect, we don't.

**Comment by rupeshpadhye** [comment]
Hi @severinlandolt , 
looks like this is not priority. but i believe it will improves chart readability.
