### ISSUE TITLE
[Feature]: Enable showing total in tooltip on AreaChart

### ISSUE THREAD

**Issue by goleary** [tremorlabs/tremor-npm#809]
### What problem does this feature solve?

I use a stacked area chart because the total of the series added together is relevant. I want the user to be able to see the value of the top of the chart (all series added together) when they use a tooltip.

I can create a custom tooltip that shows the total but I want the default style of the tooltip which means I need to recreate this in my own custom component.

### What does the proposed API look like?

prop on `AreaChart` that is something like `tooltipShowTotal`

**Comment by severinlandolt** [comment]
@christopherkindl Makes more sense leave this to custom tooltip & blocks, wdyt?

**Comment by severinlandolt** [comment]
Hi! Thank @goleary  you for submitting this feature request. This prop is very dependent on the data context of the chart. In our last minor update, we added a new customTooltip prop, where you can create a custom tooltip component fitting your needs. Hence, I am going to close this issue.

**Comment by goleary** [comment]
I've implemented using a custumTooltip for now, but I'd argue that area charts are used because the total is relevant, so the fact that it requires a custom implementation feels strange to me.

**Comment by nextjs-tsadei** [comment]
how we make tooltip clickable?

**Comment by severinlandolt** [comment]
> how we make tooltip clickable?

Hi, this is not possible.
