### ISSUE TITLE
[Feature]: Option to use <a> instead of <button> for tab

### ISSUE THREAD

**Issue by christopherkindl** [tremorlabs/tremor-npm#814]
### What problem does this feature solve?

Using a href property instead of a button for the Tab primitive. This would allow for the state to be persisted in the url instead on the client

Reference: https://github.com/tremorlabs/tremor/discussions/685

### What does the proposed API look like?

TBD

<Tab href="#" ../>

**Comment by Souravpakhira** [comment]
Hey guys can I fix this issue?

**Comment by christopherkindl** [comment]
Hi @Souravpakhira – Sure, thanks for helping out! I just assigned you.

**Comment by christopherkindl** [comment]
We are still unsure about the new API. If you have any suggestions, please let us know. Ideally, it's not going to be a breaking change.

**Comment by Souravpakhira** [comment]
I'm thinking of adding a prop to the tab. If the 'href' prop is passed, it would behave like an anchor tag; if not passed, it would just function as a normal button.

**Comment by Souravpakhira** [comment]
I need to update the browser URL if href is passed

**Comment by christopherkindl** [comment]
In this case, it also would not make any sense to use `<TabPanels>` as the link forwards to a new site

**Comment by Souravpakhira** [comment]
Yeah thats correct. I guess we need to discuss more on this what should be the ideal behaviour. Does user wants to redirect to new page or wants to stay in the same page

**Comment by Souravpakhira** [comment]
Just thinking what if we add onClick prop And let user decide onclicking tab what should be the action? because if I have onClick action than I can simply add location.replace("http://stackoverflow.com"); to redirect to another page or use any router library.

**Comment by Souravpakhira** [comment]
Having onClick prop on Tab as a optional

**Comment by christopherkindl** [comment]
You can try to use the `as` prop in `<tab>` and try it with `"a"`: https://headlessui.com/react/tabs#tab (it's our underlying library for some of our utilities)

**Comment by Souravpakhira** [comment]
Yeah sure I can try it but making it "a" anchor tag will reduce the some of use case. Because most of us use some routing library like react-router or so. So i feel like giving onClick prop to tab will make more sense and more use case to user.
