### ISSUE TITLE
[Bug]: Module '"@tremor/react"' has no exported member 'ProgressCircle'.ts(2305) import ProgressCircle

### ISSUE THREAD

**Issue by danger-ahead** [tremorlabs/tremor-npm#815]
### Tremor Version

3.11.1

### Link to minimal reproduction

NA

### Steps to reproduce

As per the docs, the [progress circle](https://www.tremor.so/docs/visualizations/progress-circle) component is available.

But no import is found after installing the package. 
```ts
// error
import { ProgressCircle } from "@tremor/react";
```

```
Attempted import error: 'ProgressCircle' is not exported from '__barrel_optimize__?names=Card,Flex,ProgressCircle!=!@tremor/react' (imported as 'ProgressCircle').
```

### What is expected?

The component can be imported and used.

### What is actually happening?

NA

### What browsers are you seeing the problem on?

Firefox

**Comment by severinlandolt** [comment]
Hi! I am not able to replicate your issue, works for me across several projects.

Can please try to:
1. Delete your node_modules folder
2. Run `npm install`

**Comment by danger-ahead** [comment]
Strangely it worked, I was working with pnpm. I think this can be closed. Thanks!
