### ISSUE TITLE
[Feature]: Add column sorting in table component

### ISSUE THREAD

**Issue by xavigpich** [tremorlabs/tremor-npm#817]
### What problem does this feature solve?

As of writing, the Tremor table component doesn't let you click on Column headers for sorting (nor name or sorting button functionality). This would be very helpful to have when displaying large tables.

To start with, column alphabetically sorting (ascending/descending) would be nice to have!

Thanks

**Comment by severinlandolt** [comment]
Hey @xavigpich, this feature would fundamentally change how Tremor's table is working. Such a feature is something we try to cover with a few new [blocks](https://www.tremor.so/blocks) that are coming soon!
