### ISSUE TITLE
[Feature]: Tooltip for Switch

### ISSUE THREAD

**Issue by severinlandolt** [tremorlabs/tremor-npm#818]
### What problem does this feature solve?

The switch component does not have a built-in Tooltip

### What does the proposed API look like?

tooltip? string;

**Comment by rajdip-b** [comment]
I would like to work on this issue. Can this be assigned to me?

**Comment by severinlandolt** [comment]
Sure!

**Comment by rajdip-b** [comment]
Hey @severinlandolt, linked PR #819. Can you check?
