### ISSUE TITLE
Dropdown menu not responsive on mobile viewport

### ISSUE THREAD

**Issue by asheikho99** [tremorlabs/tremor-npm#82]
I was browsing through documentation and it appears that dropdown component is not responsive on IOS Chrome / Safari when rendered within a container that has a horizontal scrollable view

![image](https://user-images.githubusercontent.com/105573050/194986840-5d0d2507-b789-481e-90bc-9822873d7379.jpeg)

**Comment by valcho** [comment]
Hm, wondering what would be the best way to make this better work on mobile. In general, what would be the best design choice here?

**Comment by mitrotasios** [comment]
hi @asheikho99, thanks for your comment & for spotting this, we will try to fix that asap!

**Comment by christopherkindl** [comment]
Hi @asheikho99, we just fixed it! Thanks for reaching out and if you have any feedback regarding the library, feel free to share! :)

**Comment by asheikho99** [comment]
> Hi @asheikho99, we just fixed it! Thanks for reaching out and if you have any feedback regarding the library, feel free to share! :)

Hello, sounds good. Will be contributing to this project for sure. Thanks
