### ISSUE TITLE
[Feature]: Category Bar with string values

### ISSUE THREAD

**Issue by alamenai** [tremorlabs/tremor-npm#820]
### What problem does this feature solve?

Thank you @tremor team for this project, I really enjoy working with it.

I used the Category Bar for displaying the energy classes, these classes are letters ( string ), I would to add them as values ( prop in Category Bar ) , however this prop supports only numbers.

Thank you

**Comment by severinlandolt** [comment]
Hey there, if I understand correctly, you want to pass a `string` into the `values` prop? Values have to be a `number` because they are used to calculate the width of the bars. What you are looking for is some way to add like a prefix/suffix, right?

**Comment by alamenai** [comment]
Thank you @severinlandolt for your reply. I want to make the labels as letters.

Currently, we use an image for our energy scale, however, I suggested that the team use Category Bar:

![image](https://github.com/tremorlabs/tremor/assets/20143684/3ecb86bf-0bc8-475b-a304-f95223dc4150)

**Comment by severinlandolt** [comment]
I believe it wouldn't be practical to integrate this directly into Tremor.  Given the potential for label overlaps, especially when dealing with numerous categories, especially if involving prefixes and suffixes. To create such a energy scale, I'd create a custom component.

**Comment by alamenai** [comment]
Thank you so much @severinlandolt. I actually made it like you recommended:

![image](https://github.com/tremorlabs/tremor/assets/20143684/3f70ed18-11a6-4f4e-97a6-d34dec710149)
