### ISSUE TITLE
[Bug]: Date Picker is cut off when positioned on the right end of a page

### ISSUE THREAD

**Issue by lucafaggianelli** [tremorlabs/tremor-npm#823]
### Tremor Version

3.11.1

### Link to minimal reproduction

none

### Steps to reproduce

1. Position a DatePicker at the right end of a page
2. make it smaller than it normally is, i.e. :`className="w-58"``
3. click on it so the calendar menu opens
4. notice that the calendar is cut off
5. an horizontal scroll bar appears in the page

### What is expected?

the floating menu containing the calendar should be automatically moved to fit into the page

I would also accept an `anchor` option to force the menu to be anchored on the right of the input field rather than on the left

### What is actually happening?

![localhost_5173_ (2)](https://github.com/tremorlabs/tremor/assets/4471043/2885560d-a697-4dd0-8e41-2f278b2694bf)

### What browsers are you seeing the problem on?

Chrome

**Comment by rajdip-b** [comment]
@severinlandolt hey, I feel I can fix this. Should I submit a PR?

**Comment by severinlandolt** [comment]
That would be great! I just assigned you. I have to go to sleep now🤣

**Comment by rajdip-b** [comment]
> That would be great! I just assigned you. I have to go to sleep now🤣

Would try to submit the PR by the time you wake up!🤣

**Comment by rajdip-b** [comment]
Hey guys, I was experimenting with the component and sort of found it difficult to fix the alignment automatically. This is so because the Calendar is being rendered in an absolute component, which makes it very tricky to use flex boxes. I however, created a flag that will dock the calendar to left/right, thereby fixing the issue.

Here is a demo
![image](https://github.com/tremorlabs/tremor/assets/83924254/58ddfcf4-3a11-4c5d-a0f5-c5fde33c5cce)
![image](https://github.com/tremorlabs/tremor/assets/83924254/5104776d-9239-4cd9-bf07-095bedac6795)

Can anyone suggest any improvements? @severinlandolt @lucafaggianelli

**Comment by severinlandolt** [comment]
I've completed some tests and its basically a feature that our underlying library (headlessui) does not offer natively.
![CleanShot 2023-11-20 at 01 01 12@2x](https://github.com/tremorlabs/tremor/assets/41927988/4ffedc3c-56f5-4f4e-b06c-f733dd851d20)

Thank you @rajdip-b for your initial effort and suggesting a new prop. We will do some thinking around that an come back later!

**Comment by rajdip-b** [comment]
> I've completed some tests and its basically a feature that our underlying library (headlessui) does not offer natively. ![CleanShot 2023-11-20 at 01 01 12@2x](https://user-images.githubusercontent.com/41927988/284099372-4ffedc3c-56f5-4f4e-b06c-f733dd851d20.png)
> 
> Thank you @rajdip-b for your initial effort and suggesting a new prop. We will do some thinking around that an come back later!

Sure!!

**Comment by lucafaggianelli** [comment]
Yep indeed I reached the same conclusion on headlessui. Though I saw you use the lib _floating ui_ as well in tremor, which seems more suited for this task.

About the new property, maybe I would call it "anchor" or something similar to make it more flexible so it could have values like right, left, center for the horizontal alignment and top, bottom, middle for the vertical one, I see many libs using this pattern.

**Comment by rajdip-b** [comment]
> Yep indeed I reached the same conclusion on headlessui. Though I saw you use the lib _floating ui_ as well in tremor, which seems more suited for this task.
> 
> About the new property, maybe I would call it "anchor" or something similar to make it more flexible so it could have values like right, left, center for the horizontal alignment and top, bottom, middle for the vertical one, I see many libs using this pattern.

Yeah even I did notice that. Should I proceed with the implementation, see what all changes I can implement? @lucafaggianelli @severinlandolt

**Comment by severinlandolt** [comment]
Good news: https://x.com/adamwathan/status/1729274129264624056?s=20

**Comment by rajdip-b** [comment]
> Good news: https://x.com/adamwathan/status/1729274129264624056?s=20

I guess this issue can be closed then?

**Comment by severinlandolt** [comment]
I will keep it open until Headless UI has been updated

**Comment by rajdip-b** [comment]
Sure!

**Comment by rlancejohnson** [comment]
Any update on this?

**Comment by severinlandolt** [comment]
Hi @rlancejohnson → still blocked! Waiting for headless ui 4.0.

**Comment by severinlandolt** [comment]
Hi @lucafaggianelli @rajdip-b  @rlancejohnson! Brief update: The overflow problem still persists and it looks like that this won't be fixable soon. I will update this asap once there is a fixing headless ui release. 

If you are in desperate need of a date picker with improved positioning, it's worth taking a look here: https://raw.tremor.so/docs/inputs/date-range-picker

![CleanShot 2024-04-19 at 20 56 56@2x](https://github.com/tremorlabs/tremor/assets/41927988/6ec21274-71a1-4222-a26f-cee5aae7c844)

**Comment by severinlandolt** [comment]
Soon...
<img width="340" alt="image" src="https://github.com/user-attachments/assets/905f8485-f3cd-448a-aa0f-0c62d68dde8a">
