### ISSUE TITLE
Documentation enhancement

### ISSUE THREAD

**Issue by Ichy77** [tremorlabs/tremor-npm#83]
Hi team,

I just went through the example dashboard and I have to say it's really great!!

During the 3rd Step "Add a Chart" you are using an Icon from React Hero Icons.
`import { InformationCircleIcon } from '@heroicons/react/outline';`

As I am noob dev I'm always struggling with all kind of errors and I think it's helpful to implement a short sentence about the import  at the beginning or in the 3rd Step.
`npm install @heroicons/react`

Best,
Richard!

PS: I think it was `npm install @heroicons/react@1` because there was a version issue too. I'd have to test this again :/

**Comment by Ichy77** [comment]
Ah yeah, the link to the Demo Website's GitHub Repo is old/broken as well.
This one is one the website right now: https://www.tremor.so/docs/getting-started/github.com/tremorlabs/demo.tremor.so

**Comment by mitrotasios** [comment]
Hi @Ichy77, we're glad that you like it! Yes, you're right, we missed that import, will fix asap! Thank you very much :)

**Comment by Ichy77** [comment]
Hi @mitrotasios, I just check and it's 
`npm install @heroicons/react@v1` :-)

**Comment by severinlandolt** [comment]
@Ichy77 Thank you for your thorough comments. We just pushed the fixes. Thank you, stay awesome!
