### ISSUE TITLE
[Feature]: <Dialog /> component

### ISSUE THREAD

**Issue by christopherkindl** [tremorlabs/tremor-npm#830]
### What problem does this feature solve?

Introduce `<Dialog/>` component as shown in plain code usign Headless UI in [Tremor Blocks](https://www.tremor.so/blocks/table) (First two examples). 

Component should also use the transition used in those examples

[Link](https://headlessui.com/react/dialog) to Headless UI documentation of `<Dialog>`

### What does the proposed API look like?

**`<Dialog/>` Props:**
   open?: boolean
   onClose?: (false) => void
   static: boolean (default: false)
   unmount: boolean (default: true)

**`<DialogPanel/>` Props:**
   open?: boolean

Way of building:
```
  <Dialog {...args}>
   <DialogPanel {...args}>
     [Content of Dialog]
   </DialogPanel>
  <Dialog>
```

**Comment by christopherkindl** [comment]
Reference: https://github.com/tremorlabs/tremor/issues/811

**Comment by Sanket-Arekar** [comment]
I would like to work on this issue. Can you Please assign me this issue?

**Comment by christopherkindl** [comment]
sorry @Sanket-Arekar, somehow we did not see the comment. Now assigned! :)

**Comment by christopherkindl** [comment]
@Sanket-Arekar Just to conform, do you want to work on that? :)

**Comment by iamtouha** [comment]
@christopherkindl  I would like to work on it.

**Comment by christopherkindl** [comment]
@touha98 assigned! thank you :)
