### ISSUE TITLE
[Bug]: Not able to see the charts

### ISSUE THREAD

**Issue by nithinkodadhavadee** [tremorlabs/tremor-npm#831]
### Tremor Version

3.11.1

### Link to minimal reproduction

https://github.com/nithinkodadhavadee/tremor/blob/main/app/page.tsx

### Steps to reproduce

All I did was create the next project and install this and the icons library. copy and paste the code from the documentation to my editor. 

### What is expected?

I am not able to see the charts. 

### What is actually happening?

I am getting the following warning when I try to insert charts into my first dashboard. 
I have installed the library after creating a new next project. 

```
The width(0) and height(0) of chart should be greater than 0,
       please check the style of container, or the props width(100%) and height(100%),
       or add a minWidth(0) or minHeight(undefined) or use aspect(undefined) to control the
       height and width.
```

and this is how it looks

![image](https://github.com/tremorlabs/tremor/assets/50230678/a815bb1e-4b41-4e20-a56b-3f7dad6e80bc)
into

### What browsers are you seeing the problem on?

Chrome, Firefox, Brave

**Comment by severinlandolt** [comment]
Hey there, I just tested your code and in another project and works for me. However, I cloned your repo and I git the same issue. You can resolve it by removing the `h-72` from the Area chart args object.

**Comment by nithinkodadhavadee** [comment]
I do not understand why that did not work for me, but it did for you. Have I done something wrong with the setup?

**Comment by dardanbujupaj** [comment]
@nithinkodadhavadee I have the same issue.
It seems to be an update to the `recharts` dependency for me.

Can you try adding the `recharts` dependency explicitely to your `package.json` with a pinned version?

```
"recharts": "2.9.3",
```

(and of course run `npm install` and `npm run dev` afterwards)

This helped in my case, I wonder if this works for you as well?

**Comment by dardanbujupaj** [comment]
@nithinkodadhavadee Ok, I had a look at your repository.

It seems you're not experiencing the same problem, but I found an issue in your configuration.

The content path in your `tailwind.config.ts` does not match your project structure. Try this change: 
<img width="386" alt="Screenshot 2023-11-28 at 16 04 48" src="https://github.com/tremorlabs/tremor/assets/16074028/a1692b64-8bda-4eee-b943-88826847ea8d">

**Comment by severinlandolt** [comment]
@nithinkodadhavadee Have you been able to solve you issue?

**Comment by ebayes** [comment]
Hi! I've also been having the same issue not being able to see the charts in the Next.js app directory. I tried the fixes mentioned above (i.e. removing h-72, and updating tailwind.config.js and the recharts dependency) but I'm still having no luck. I think it's to do with conflicts with Shadcn UI (see here: https://github.com/shadcn-ui/ui/issues/1144). Any ideas?

Relevant files: 

page.tsx in app directory: https://github.com/ebayes/supa_final/blob/color_scheme/app/platform/dashboard/page.tsx
component: https://github.com/ebayes/supa_final/blob/color_scheme/components/testchart.tsx
