### ISSUE TITLE
Tracker colours not fully available

### ISSUE THREAD

**Issue by Sun-bun** [tremorlabs/tremor-npm#84]
Using the 'Tracker' component white isn't a valid colour option, it defaults to blue, so does leaving colour blank.
Having white would be useful against the white background so it can visually show a reduction of tracking blocks whilst staying the same size as a comparison tracker, currently when reducing tracking block count it resizes, it would be nice to have some customisability. and not have it auto fill/fit to the width.

**Comment by mitrotasios** [comment]
Having `white` as a color variant definitely makes sense generally, will fix as soon as we can, thanks for the comment!

**Comment by souravmondal93** [comment]
Having a white color block for tracker is looking empty. I tried with a bordered version as well. Could you please share your thoughts on this? @mitrotasios 

<img width="824" alt="Screenshot 2022-11-01 at 12 36 57" src="https://user-images.githubusercontent.com/2352166/199234340-cbaa83fe-72d7-4fb1-a5de-f14c9b8e821f.png">
Figure 1: Without border
<img width="812" alt="Screenshot 2022-11-01 at 12 37 17" src="https://user-images.githubusercontent.com/2352166/199234337-26aebdc8-a4f6-4318-b496-a0082e93d113.png">
Figure 2: With border

**Comment by Sun-bun** [comment]
Looks great, the use case I wanted it for was so that I could have a sectioned bar filling from left to right over time or with + and - buttons either side as an interactive component so Figure 1 without the border is perfect for that!

**Comment by severinlandolt** [comment]
Hello there! We decided to not implement this feature because there we will be allowing more customisability in the future anyways, so no new colors are needed. Thanks for sticking around!
