### ISSUE TITLE
[Feature]: `RadioButton` Component

### ISSUE THREAD

**Issue by severinlandolt** [tremorlabs/tremor-npm#844]
### What problem does this feature solve?

Tremor is missing Radio Group component.

### What does the proposed API look like?

Cf. HeadlessUI

**Comment by severinlandolt** [comment]
Not planned.

**Comment by adamsuskin** [comment]
@severinlandolt would you welcome a contribution?

**Comment by severinlandolt** [comment]
Hey there! We actually had a PR for this, but closed it because we are preferring this: https://raw.tremor.so/docs/inputs/radio-group
