### ISSUE TITLE
[Feature]: Change x axis interval

### ISSUE THREAD

**Issue by slck98** [tremorlabs/tremor-npm#847]
### What problem does this feature solve?

![image](https://github.com/tremorlabs/tremor/assets/135994483/1c2afc6b-2bd7-4d58-b60c-94dd5795944a)

is it possible to change the x axis interval? It does not show all the index of data.

**Comment by severinlandolt** [comment]
Hi @slck98, this is not possible, we use the default from Recharts under the hood and this won't be changing. You can try change `intervalType` to `preserveStartEnd `
