### ISSUE TITLE
[Bug]: Select and MultiSelect have different height properties

### ISSUE THREAD

**Issue by mohamm-ad** [tremorlabs/tremor-npm#852]
### Tremor Version

v3

### Link to minimal reproduction

/sorry-no-link

### Steps to reproduce

Should be straightforward: the Select component and MultiSelect components appear to have different default heights, which is difficult to manage with Tailwind conflicts. The MultiSelect search also doesn't respect the styling of MultiSelect or MultiSelectItem. For example, if you set className='text-xs', items will get styled by the search will not. 

### What is expected?

These components are often used next to each other as filters etc. in dashboards. Ideally, they would have the same default height.

### What is actually happening?

It appears MultiSelect has a slightly larger height (in order to support selections). Search also doesn't respect styling (while the items do). 

### What browsers are you seeing the problem on?

Chrome, Firefox

### Any additional comments?

Simplest solution would be to increase the height of the Select component to match that of MultiSelect which has to take items.

**Comment by christopherkindl** [comment]
Hi @mohamm-ad, thanks for letting us know, we will investigate asap! In the meantime, you can harmonize the heights via `className` customization: Try to insert `[&>button]:h-9` for example.

**Comment by mohamm-ad** [comment]
Amazing @christopherkindl! And good call, that fix worked! Any suggested workarounds for styling the search in MultiSelect?

**Comment by christopherkindl** [comment]
@mohamm-ad you are welcome! :) What do you want to style exactly?

**Comment by mohamm-ad** [comment]
![image](https://github.com/tremorlabs/tremor/assets/140478188/ad9f55c0-945c-4393-bc7c-54d20b5b209c)

When styling MultiSelect + MultiSelectItem, changes with Tailwind are reflected correctly across the component except for in the search area. For example, in the image above I applied text-xs to both, which works fine except for search (where text stays the default size). Apologies if I'm missing something!

**Comment by severinlandolt** [comment]
Hey @mohamm-ad, I my tests, they seem all seem to have the same height. Can you post a screenshot of your example?


![Image](https://github.com/tremorlabs/tremor/assets/41927988/5ed745eb-0a97-4c3e-aff3-554d7df47a93)


![Image](https://github.com/tremorlabs/tremor/assets/41927988/613d6889-c242-477e-bac4-7f1d2368962c)



![Image](https://github.com/tremorlabs/tremor/assets/41927988/9ed870bf-a7e9-4a1d-9c6a-4a1c16a2470d)

**Comment by severinlandolt** [comment]
Ad text: Why don't use use the Theme in the tremor config? You could easily overwrite `tremor-default` to your liking

```js
 fontSize: {
        "tremor-label": ["0.75rem"],
        "tremor-default": ["0.875rem", { lineHeight: "1.25rem" }],
        "tremor-title": ["1.125rem", { lineHeight: "1.75rem" }],
        "tremor-metric": ["1.875rem", { lineHeight: "2.25rem" }],
      },
```


![Image](https://github.com/tremorlabs/tremor/assets/41927988/23251c57-6992-41ef-bc73-9fa7aee8c36b)

**Comment by mohamm-ad** [comment]
Interesting! I'm not quite sure what's going on in mine, I haven't made any changes:

![image](https://github.com/tremorlabs/tremor/assets/140478188/e1fb1a5b-91d3-41d2-9697-31cf64006681)

![image](https://github.com/tremorlabs/tremor/assets/140478188/73d58eae-534c-4ea0-a871-99830183c163)

![image](https://github.com/tremorlabs/tremor/assets/140478188/88ce86fa-16ed-49af-ad4c-5cd99b41d24b)

Yep, when you adjust the default text size, the search text adjusts accordingly as intended. But for this particular use case, I needed to adjust the placeholder and item size to be different from the default -- that worked fine with tailwind, but i wasn't able to change the _search_ placeholder text.

**Comment by severinlandolt** [comment]
Alright, the select on the left is too small. Its the Select or Multiselect? I am having a hard time replicating your issue. Could you share a minimal reproduction? @mohamm-ad

**Comment by severinlandolt** [comment]
@mohamm-ad Can I close this issue from your side?
