### ISSUE TITLE
[Feature]: Allow disabled state in <SelectItems />

### ISSUE THREAD

**Issue by christopherkindl** [tremorlabs/tremor-npm#853]
### What problem does this feature solve?

Currently, it's only possible to disable an entire `<Select/>` component but not its underlying items.

### What does the proposed API look like?

- `<SelectItem disabled>`
- `<MultiSelectItem disabled>`
- `<SearchSelectItem disabled>`

Make sure to stick to our styling (compare disabled modes in other components of Tremor, e.g. <Input /> or <Select />).

**Comment by madangopal16072000** [comment]
I would like contribute could you please this to me.

**Comment by christopherkindl** [comment]
Assigned! Thanks!

**Comment by madangopal16072000** [comment]
hey @christopherkindl since this is my time contributing to this project could you please point to some resource for reference as contributing.md file not have much info for setting up the project.

**Comment by dislocated-su** [comment]
Hi, why was this closed?

**Comment by severinlandolt** [comment]
@dislocated-su → New select component: https://raw.tremor.so/docs/inputs/select

Won't add this to the package.
