### ISSUE TITLE
[Bug]: Children prop Select

### ISSUE THREAD

**Issue by Digitl-Alchemyst** [tremorlabs/tremor-npm#859]
### Tremor Version

3.12.0

### Link to minimal reproduction

https://github.com/Digitl-Alchemyst/google-shopping

### Steps to reproduce

![image](https://github.com/tremorlabs/tremor/assets/129696730/8c3da905-31f6-4c3c-9cfc-fa78734201c9)
Header component

### What is expected?

No error

### What is actually happening?

Error

**Comment by motinados** [comment]
When does this error occur?
I did the following, but I didn't encounter the error.

1. clone repository
```
git clone https://github.com/Digitl-Alchemyst/google-shopping.git
npm i
npm run dev
```
2.  I made a few selections and clicked the form button.

**Comment by severinlandolt** [comment]
@motinados Thank you for jumping in, also having a hard time replicating the issue.
@Digitl-Alchemyst More info would be appreciated!

**Comment by Digitl-Alchemyst** [comment]
Cant tell you what caused it, the error cleared up on its own so I can no longer reproduce my self, thank you all for the replies.
