### ISSUE TITLE
Icon prop on Button component uses incorrect capitalization

### ISSUE THREAD

**Issue by ethndotsh** [tremorlabs/tremor-npm#87]
The Icon property on the Button component uses `PascalCase` rather than `camelCase` for the prop name. Is this intentional or a bug?

```jsx
import { ReloadIcon } from "someiconlibrary"

<div>                   // here
    <Button text="Reload" Icon={ReloadIcon} importance="primary" />
</div>
```

**Comment by mitrotasios** [comment]
hi @cursecodes, thanks for your comment, this is intentional to signal that a React Element / JSX Constructor is required as an input. Would you suggest to change that?

**Comment by ethndotsh** [comment]
Yes, I feel that that would be the correct move. You can see in the links provided that it seems to be the standard to use camelCase for all props.

[Chakra](https://chakra-ui.com/docs/components/icon-button/props)
[Evergreen by Segment](https://evergreen.segment.com/components/buttons#icon_buttons)

If you need, I will gladly open a PR to change this

**Comment by mitrotasios** [comment]
Seems like it, thanks for that! We are super busy at the moment so it may take a bit to fix this. Therefore, feel free to open a PR whenever you like, would be happy to have you as our first outside contributor :)
