### ISSUE TITLE
[Bug]: Unhandled Runtime Error

### ISSUE THREAD

**Issue by maxdeichmann** [tremorlabs/tremor-npm#871]
### Tremor Version

3.12.1

### Link to minimal reproduction

https://github.com/langfuse/langfuse/blob/main/src/pages/project/%5BprojectId%5D/index.tsx

### Steps to reproduce

When using Tremor in our Frontend, and open up our [dashboard](https://github.com/langfuse/langfuse/blob/main/src/pages/project/%5BprojectId%5D/index.tsx), i run into a runtime error in Firefox 120. Chrome seems to be fine.

### What is expected?

No exception.

### What is actually happening?

```
Unhandled Runtime Error

TypeError: e is undefined
Call Stack
$/r<
node_modules/@tremor/react/dist/lib/utils.js (1:665)
$
node_modules/@tremor/react/dist/lib/utils.js (1:665)
f
node_modules/@tremor/react/dist/components/text-elements/Legend/Legend.js (1:1011)
renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js (16305:0)
mountIndeterminateComponent
node_modules/react-dom/cjs/react-dom.development.js (20074:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (21587:0)
callCallback
node_modules/react-dom/cjs/react-dom.development.js (4164:0)
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (4213:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (4277:0)
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js (27451:0)
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js (26557:0)
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js (26466:0)
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js (26434:0)
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (25738:0)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (239:0)
performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (533:0)
```

### What browsers are you seeing the problem on?

Firefox

**Comment by bfowle** [comment]
Also seeing this, using `Legend` in a next.js app:

```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'includes')

Call Stack
eval
node_modules/@tremor/react/dist/lib/utils.js (1:665)
$
node_modules/@tremor/react/dist/lib/utils.js (1:665)
f
node_modules/@tremor/react/dist/components/text-elements/Legend/Legend.js (1:1011)
...
```

From a quick bisect: `v3.11.1` was fine; `v3.12.x` (starting at `v3.12.0-beta.5`) seems to have broken it.

**Comment by severinlandolt** [comment]
Thanks! Will take a look at it today

**Comment by severinlandolt** [comment]
Hey there, wasn't able to reproduce both errors in any browser or framework ☹️

@bfowle Could you paste this simple test legend and tell me if it works? (Are you using any custom colors?)
Test the following:
* Code snippet as is
* Without `colors`
* Without `onClickLegendItem`

Thanks!

```jsx
<Legend
  categories={[
  "Active users",
  "Inactive users",
  ]}
  colors={["green", "slate"]}
  onClickLegendItem={(e) => {
  console.log(e)
  }}
/>
```

**Comment by bfowle** [comment]
@severinlandolt I realized it was in a case where the number of `categories` were greater than specified `colors`:
Example:
```
<Legend categories={['Foo','Bar','Baz']} colors={['blue','purple']} />
```
Prior to `v3.12.x` this gracefully picked a default (`slate` I believe) color for unspecified colors and did not throw any sort of error or warning. Now it throws the error previously posted.
Hope this helps.
Cheers~

**Comment by severinlandolt** [comment]
Alright, thank you!

**Comment by matheuzinoficial** [comment]
Any updates on this? @severinlandolt

**Comment by severinlandolt** [comment]
@matheuzinoficial You can test `npm i @tremor/react@3.13.0-beta.6`, please let me know if the bug still occurs, thanks!
