### ISSUE TITLE
[Bug]:  Can't use icons

### ISSUE THREAD

**Issue by PalmoSweet** [tremorlabs/tremor-npm#879]
### Tremor Version

latest installed 2023-12-19

### Link to minimal reproduction

Used the exact table example https://www.tremor.so/docs/ui/text-input

### Steps to reproduce

Nothing, just run the code in your example docs using next 14

### What is expected?

It's expected to show a icon

### What is actually happening?

Unhandled Runtime Error
Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server".
  {$$typeof: ..., render: function}
                          ^^^^^^^^

Call Stack
<unknown>
/Users/rasmus/Developer/Webdev/autoserve2-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:280406)
Object.toJSON
/Users/rasmus/Developer/Webdev/autoserve2-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:281132)
stringify
<anonymous>
<unknown>
/Users/rasmus/Developer/Webdev/autoserve2-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:267488)
ez
/Users/rasmus/Developer/Webdev/autoserve2-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:267567)
eH
/Users/rasmus/Developer/Webdev/autoserve2-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:267968)
Timeout._onTimeout
/Users/rasmus/Developer/Webdev/autoserve2-nextjs/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js (35:264466)
listOnTimeout
node:internal/timers (573:17)
process.processTimers
node:internal/timers (514:7)

### What browsers are you seeing the problem on?

Chrome

**Comment by severinlandolt** [comment]
Hey @PalmoSweet , just tested it on Next 14.0.4 and the example works for me. Can you try to add the 'use client' directive to the component where this error occurs?

**Comment by PalmoSweet** [comment]
I have the "use client" directive in my component. But still, the Icons does not work. The table is displayed but not the icon. I am running a client component (the table) inside of a server component (page.tsx) if that info helps!

**Comment by severinlandolt** [comment]
@PalmoSweet Could you provide a minimal replication of the bug you are encountering? Could be a codesanbox or a github repo, thanks!

**Comment by severinlandolt** [comment]
Closed until more information is provided, thanks!
