### ISSUE TITLE
[Feature]: Make the x-axis label inclined on mobile devices

### ISSUE THREAD

**Issue by alamenai** [tremorlabs/tremor-npm#881]
### What problem does this feature solve?

I have created a Bar Chart with 5 columns ( bars ), while it looks perfect on the desktop, on mobiles, the labels do not appear on all of them:

#### Large screen ( > 1200px )
![image](https://github.com/tremorlabs/tremor/assets/20143684/8719878e-b999-4720-b40d-57cbf7e97f87)

#### Small screen ( 320-425px)

![image](https://github.com/tremorlabs/tremor/assets/20143684/b165d887-9b68-421d-9956-dd5e4c28b914)

I would suggest making them inclined ( 45 degrees or 90 degrees) to allow all of them to appear on small screens.

**Comment by severinlandolt** [comment]
Hey @MenaiAla , there is a `rotateLabelX` prop to add your custom label rotation. The logic at which breakpoint or card width you rotate the labels and by how much you would have to implement yourself :)

**Comment by alamenai** [comment]
Thank you @severinlandolt , I'll try your suggestions.
