### ISSUE TITLE
[Bug]: `DateRangePicker` range dropdown missing hover styles

### ISSUE THREAD

**Issue by adamhenson** [tremorlabs/tremor-npm#883]
**_Disclaimer_**: This isn't necessarily a bug, but perhaps an opportunity for documentation. See solution at bottom.

### Tremor Version

3.3.2

### Link to minimal reproduction

NA

### Steps to reproduce

1. Import `DateRangePicker` per [docs](https://www.tremor.so/docs/ui/daterangepicker#import-daterangepicker).

### What is expected?

The range dropdown list should have hover styles, mirroring the [Storybook example](https://storybook.tremor.so/?path=/story/ui-input-daterangepicker--uncontrolled-default). Note the existence of styles in the screenshot starting with `ui-active:...`

<img width="1389" alt="Screenshot 2023-12-26 at 12 12 34 PM" src="https://github.com/tremorlabs/tremor/assets/747743/88b7875f-4b6a-48c4-9bb7-09f5c7855a9e">

### What is actually happening?

The range dropdown list does not have hover styles. Styles applied in the above screenshot with `ui-active:...` are not applied in actuality.

### What browsers are you seeing the problem on?

All

### Any additional comments?

# Solution

I had to install a new dependency `@headlessui/tailwindcss` and add the below plugin to Tailwind CSS config.

```javascript
plugins: [require('@headlessui/tailwindcss')],
```

I'm more reporting that this is an opportunity to add documentation to callout this dependency, unless I'm missing something.

**Comment by severinlandolt** [comment]
Thanks @adamhenson! Just at the right time, was about to release a Tremor CLI update. Will fix this soon!

**Comment by adamhenson** [comment]
🙇

**Comment by severinlandolt** [comment]
Updated the docs + cli.
