### ISSUE TITLE
[Feature]: Custom Bars

### ISSUE THREAD

**Issue by charliemday** [tremorlabs/tremor-npm#887]
### What problem does this feature solve?

An ability to render your own bars and having the `Bar` component from the `recharts` library the default. Basically, I want to be able to add some `borderRadius` to the top of my charts which I could do if I were to render it myself instead (similar to the `CustomTooltip`).

### What does the proposed API look like?

```
<BarChart
  data={chartData}
  ...
  customBarComponent={renderCustomBarComponent}
/>
```

Could just be a conditional [here](https://github.com/tremorlabs/tremor/blob/main/src/components/chart-elements/BarChart/BarChart.tsx#L322) (and use the recharts types for `Bar`)?

**Comment by severinlandolt** [comment]
Hi @charliemday, unfortunately, we have decided not to proceed with your feature request. Our approach to charting will maintain its current level of abstraction. If you require control over the bars, the other abstractions in Tremor may not match the level of customizability you desire. Thank you for your request!
