### ISSUE TITLE
[Feature]: click handler for BarList

### ISSUE THREAD

**Issue by goleary** [tremorlabs/tremor-npm#888]
### What problem does this feature solve?

Looks like onClick handlers were added for many of the charts, but not the `BarList`.

### What does the proposed API look like?

Same as the others would be great with an `onValueChange` prop that can be passed in to know when a specific bar is clicked.

**Comment by severinlandolt** [comment]
Refactoring the whole barlist is something planned, thanks for your feedback!

**Comment by severinlandolt** [comment]
cf. #204
