### ISSUE TITLE
Badge Icon and Text Misaligned

### ISSUE THREAD

**Issue by Josue14RO** [tremorlabs/tremor-npm#904]
Hi, I am trying to use the Badge and BadgeDelta components, but when I use them, they appear as follows:

![image](https://github.com/tremorlabs/tremor/assets/147109347/4563860c-6d5b-48e3-85d6-741ef99b6dc4)

The icon and the text are misaligned, how can I fix this, I attach the code used.
`<Badge size="lg" color="teal" icon={CheckCircleIcon}>`
`{item.testStatus}`
`</Badge>`

**Comment by severinlandolt** [comment]
Hi @Josue14RO can you send me a code snippet with the surrounding code? I dont think its the Badge itseldf, but some parent element causing this, thanks!

**Comment by Josue14RO** [comment]
Hi @severinlandolt, this is the code for the whole component.

`import React from "react";
import { useFetch } from "../useFetch";
import {
  Badge,
  Card,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeaderCell,
  TableRow,
  Title,
} from "@tremor/react";
import { CheckCircleIcon, XCircleIcon } from "@heroicons/react/24/solid";

const DataTable = () => {
  const { judge } = useFetch();
  console.log(judge);
  return (
    <Card>
      <Title>Lista de TestResult</Title>
      <Table>
        <TableHead>
          <TableRow>
            <TableHeaderCell>SerialNumber</TableHeaderCell>
            <TableHeaderCell>TestStatus</TableHeaderCell>
            <TableHeaderCell>Cell</TableHeaderCell>
            <TableHeaderCell>PartNumber</TableHeaderCell>
            <TableHeaderCell>EmployeeNumber</TableHeaderCell>
            <TableHeaderCell>ComputerName</TableHeaderCell>
            <TableHeaderCell>FailureReason</TableHeaderCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {judge?.map((item) => (
            <TableRow key={item.judgeId}>
              <TableCell>{item.serialNumber1}</TableCell>
              {item.testStatus === "PASS" ? (
                <TableCell>
                  <Badge size="lg" color="teal" icon={CheckCircleIcon}>
                    {item.testStatus}
                  </Badge>
                </TableCell>
              ) : (
                <TableCell>
                  <Badge color="red" icon={XCircleIcon}>
                    {item.testStatus}
                  </Badge>
                </TableCell>
              )}

              <TableCell>{item.cell}</TableCell>
              <TableCell>{item.partNumber}</TableCell>
              <TableCell>{item.employeeNumber}</TableCell>
              <TableCell>{item.computerName}</TableCell>
              <TableCell>{item.failureReason}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Card>
  );
};

export default DataTable;
`
I don't think it's the father because I also used it on a Card and the result was the same.

**Comment by severinlandolt** [comment]
@Josue14RO I cant see any badge in that code, can you please post a working example, thanks!

**Comment by Josue14RO** [comment]
Sorry, I didn't realise when I pasted the text it hadn't been placed.

`import React from "react";`
`import { useFetch } from "../useFetch";`
`import {  Badge,  Card,  Table,  TableBody,  TableCell,  TableHead,  TableHeaderCell,  TableRow,  Title,} from "@tremor/react";`
`import { CheckCircleIcon, XCircleIcon } from "@heroicons/react/24/solid";`

`const DataTable = () => {`
`  const { judge } = useFetch();`
`  console.log(judge);`
`  return (`
`    <Card>`
`      <Title>Lista de TestResult</Title>`
`      <Table>`
`        <TableHead>`
`          <TableRow>`
`           <TableHeaderCell>SerialNumber</TableHeaderCell>`
`            <TableHeaderCell>TestStatus</TableHeaderCell>`
`            <TableHeaderCell>Cell</TableHeaderCell>`
`            <TableHeaderCell>PartNumber</TableHeaderCell>`
`            <TableHeaderCell>EmployeeNumber</TableHeaderCell>`
`            <TableHeaderCell>ComputerName</TableHeaderCell>`
`            <TableHeaderCell>FailureReason</TableHeaderCell>`
`          </TableRow>`
`        </TableHead>`
`        <TableBody>`
`          {judge?.map((item) => (`
`            <TableRow key={item.judgeId}>`
`              <TableCell>{item.serialNumber1}</TableCell>`
`              {item.testStatus === "PASS" ? (`
`                <TableCell>`
`                  <Badge size="lg" color="teal" icon={CheckCircleIcon}>`
`                    {item.testStatus}`
`                  </Badge>`
`                </TableCell>`
`              ) : (`
`                <TableCell>`
`                  <Badge color="red" icon={XCircleIcon}>`
`                    {item.testStatus}`
`                  </Badge>`
`                </TableCell>`
`              )}`

`             <TableCell>{item.cell}</TableCell>`
`             <TableCell>{item.partNumber}</TableCell>`
`             <TableCell>{item.employeeNumber}</TableCell>`
`             <TableCell>{item.computerName}</TableCell>`
`             <TableCell>{item.failureReason}</TableCell>`
`           </TableRow>`
`         ))}`
`       </TableBody>`
`     </Table>`
`   </Card>`
` );`
`};`

`export default DataTable;`

**Comment by severinlandolt** [comment]
Hi @Josue14RO, its'working for me. What framwork are you using? What version of tailwind css?

Note that i am using
`npm i @heroicons/react@1.0.6`
<img width="614" alt="image" src="https://github.com/tremorlabs/tremor/assets/41927988/e6869887-1bdc-492b-af77-756418105a73">

```tsx
"use client";
import React from "react";
import {
  Badge,
  Card,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeaderCell,
  TableRow,
  Title,
} from "@tremor/react";

import { StatusOnlineIcon, ExclamationIcon } from "@heroicons/react/outline";

const dummyJudgeArray = [
  {
    judgeId: 1,
    serialNumber1: "SN001",
    testStatus: "PASS",
    cell: "Cell A",
    partNumber: "12345",
    employeeNumber: "E001",
    computerName: "Computer 1",
    failureReason: "",
  },
  {
    judgeId: 2,
    serialNumber1: "SN002",
    testStatus: "FAIL",
    cell: "Cell B",
    partNumber: "67890",
    employeeNumber: "E002",
    computerName: "Computer 2",
    failureReason: "Test Failed",
  },
  {
    judgeId: 3,
    serialNumber1: "SN003",
    testStatus: "PASS",
    cell: "Cell C",
    partNumber: "54321",
    employeeNumber: "E003",
    computerName: "Computer 3",
    failureReason: "",
  },
];

const DataTable = () => {
  return (
    <Card>
      <Title>Lista de TestResult</Title>
      <Table>
        <TableHead>
          <TableRow>
            <TableHeaderCell>SerialNumber</TableHeaderCell>
            <TableHeaderCell>TestStatus</TableHeaderCell>
            <TableHeaderCell>Cell</TableHeaderCell>
            <TableHeaderCell>PartNumber</TableHeaderCell>
            <TableHeaderCell>EmployeeNumber</TableHeaderCell>
            <TableHeaderCell>ComputerName</TableHeaderCell>
            <TableHeaderCell>FailureReason</TableHeaderCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {dummyJudgeArray?.map((item) => (
            <TableRow key={item.judgeId}>
              <TableCell>{item.serialNumber1}</TableCell>
              {item.testStatus === "PASS" ? (
                <TableCell>
                  <Badge size="lg" color="teal" icon={StatusOnlineIcon}>
                    {item.testStatus}
                  </Badge>
                </TableCell>
              ) : (
                <TableCell>
                  <Badge color="red" icon={ExclamationIcon}>
                    {item.testStatus}
                  </Badge>
                </TableCell>
              )}

              <TableCell>{item.cell}</TableCell>
              <TableCell>{item.partNumber}</TableCell>
              <TableCell>{item.employeeNumber}</TableCell>
              <TableCell>{item.computerName}</TableCell>
              <TableCell>{item.failureReason}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </Card>
  );
};

export default DataTable;

```

**Comment by Josue14RO** [comment]
Hi @severinlandolt I used the same code as you and got this result.

![image](https://github.com/tremorlabs/tremor/assets/147109347/ac28e48f-82a5-48b4-aab6-3fbd130391ed)

Mi package.Json is:
```
"dependencies": {
    "@heroicons/react": "^1.0.6",
    "@tremor/react": "^3.12.2",
    "react": "^18.2.0"
},
"devDependencies": {
    "tailwindcss": "^3.4.1"
}
```

**Comment by severinlandolt** [comment]
@Josue14RO Do you have any special settings in your tailwind config? Is this repository public?

**Comment by Josue14RO** [comment]
@severinlandolt I don't have it in a repository.
This is the tailwind configuration.

```
/** @type {import('tailwindcss').Config} */

const colors = require("tailwindcss/colors");
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./node_modules/@tremor/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    transparent: "transparent",
    current: "currentColor",
    extend: {
      colors: {
        // light mode
        tremor: {
          brand: {
            faint: colors.blue[50],
            muted: colors.blue[200],
            subtle: colors.blue[400],
            DEFAULT: colors.blue[500],
            emphasis: colors.blue[700],
            inverted: colors.white,
          },
          background: {
            muted: colors.gray[50],
            subtle: colors.gray[100],
            DEFAULT: colors.white,
            emphasis: colors.gray[700],
          },
          border: {
            DEFAULT: colors.gray[200],
          },
          ring: {
            DEFAULT: colors.gray[200],
          },
          content: {
            subtle: colors.gray[400],
            DEFAULT: colors.gray[500],
            emphasis: colors.gray[700],
            strong: colors.gray[900],
            inverted: colors.white,
          },
        },
        // dark mode
        "dark-tremor": {
          brand: {
            faint: "#0B1229",
            muted: colors.blue[950],
            subtle: colors.blue[800],
            DEFAULT: colors.blue[500],
            emphasis: colors.blue[400],
            inverted: colors.blue[950],
          },
          background: {
            muted: "#131A2B",
            subtle: colors.gray[800],
            DEFAULT: colors.gray[900],
            emphasis: colors.gray[300],
          },
          border: {
            DEFAULT: colors.gray[700],
          },
          ring: {
            DEFAULT: colors.gray[800],
          },
          content: {
            subtle: colors.gray[600],
            DEFAULT: colors.gray[500],
            emphasis: colors.gray[200],
            strong: colors.gray[50],
            inverted: colors.gray[950],
          },
        },
      },
      boxShadow: {
        // light
        "tremor-input": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "tremor-card":
          "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
        "tremor-dropdown":
          "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
        // dark
        "dark-tremor-input": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "dark-tremor-card":
          "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
        "dark-tremor-dropdown":
          "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
      },
      borderRadius: {
        "tremor-small": "0.375rem",
        "tremor-default": "0.5rem",
        "tremor-full": "9999px",
      },
      fontSize: {
        "tremor-label": ["0.75rem"],
        "tremor-default": ["0.875rem", { lineHeight: "1.25rem" }],
        "tremor-title": ["1.125rem", { lineHeight: "1.75rem" }],
        "tremor-metric": ["1.875rem", { lineHeight: "2.25rem" }],
      },
    },
  },
  safelist: [
    {
      pattern:
        /^(bg-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
      variants: ["hover", "ui-selected"],
    },
    {
      pattern:
        /^(text-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
      variants: ["hover", "ui-selected"],
    },
    {
      pattern:
        /^(border-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
      variants: ["hover", "ui-selected"],
    },
    {
      pattern:
        /^(ring-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
    },
    {
      pattern:
        /^(stroke-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
    },
    {
      pattern:
        /^(fill-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
    },

    // custom colors charts
    ...["[#32a852]", "[#fcba03]"].flatMap((customColor) => [
      `bg-${customColor}`,
      `border-${customColor}`,
      `hover:bg-${customColor}`,
      `hover:border-${customColor}`,
      `hover:text-${customColor}`,
      `fill-${customColor}`,
      `ring-${customColor}`,
      `stroke-${customColor}`,
      `text-${customColor}`,
      `ui-selected:bg-${customColor}]`,
      `ui-selected:border-${customColor}]`,
      `ui-selected:text-${customColor}`,
    ]),
  ],
  plugins: [require("@headlessui/tailwindcss")],
};
```

**Comment by severinlandolt** [comment]
@Josue14RO, looks good to me. I am out of ideas why this is happening. 

Last thing you could try: add the following utility to your badge:

className="flex-nowrap"

If this does not work, I'd recommend creating your own badge component and use it instead. Here is some starting code:

```
<span className="inline-flex items-center gap-x-1 rounded-tremor-small flex-nowrap px-2 py-1 text-tremor-label font-semibold text-emerald-700 ring-1 ring-tremor-ring dark:text-emerald-500 dark:ring-dark-tremor-ring">
  <RiArrowUpSFill className="-ml-0.5 h-4 w-4" aria-hidden="true" />
  9.3%
</span>
```

**Comment by Josue14RO** [comment]
That gets me started, thank you very much for the help @severinlandolt

**Comment by severinlandolt** [comment]
I will close this issue, but feel free to comment if anything comes up!
