### ISSUE TITLE
[Feature]: MarkerBar `rangeColor` prop

### ISSUE THREAD

**Issue by NicHaley** [tremorlabs/tremor-npm#911]
### What problem does this feature solve?

I would like to use the MarkerBar chart for the following scenario:
- I would like to have the chart function ostensibly like a ProgressBar, but with a Marker on top

My real world use-case for this is to indicate a company's token usage over the course of a month, with the marker indicating the day of the month. This would make it easy to visualize whether they are ahead of behind their monthly usage allotment. 

I can basically handle this use-case already, except for the fact the range color isn't configrable. If there was just an option for that it would be great.

### What does the proposed API look like?

`rangeColor`

**Comment by severinlandolt** [comment]
Hi! In your case, I want you to forward to our copy & paste library: https://tremor.so/docs/visualizations/progress-bar

You can add a marker and range exactly as you need. Here is the marker reference: https://github.com/tremorlabs/tremor/blob/a3e785358317cf0c902c0ac84e0bf8ac7406ac75/src/components/vis-elements/MarkerBar/MarkerBar.tsx
