### ISSUE TITLE
[Bug]: SearchSelect with large padding

### ISSUE THREAD

**Issue by giovannefc** [tremorlabs/tremor-npm#912]
### Tremor Version

3.13.2-beta-button-transition.1

### Link to minimal reproduction

It looked like this after updating, I just don't know exactly when

### Steps to reproduce

```
<SearchSelect
        icon={fetcher.state !== "idle" ? LoadingIcon : ListBulletIcon}
        value={value}
        onValueChange={(value) => {
          setValue(value);
          validate();
        }}
        onInputCapture={(e: ChangeEvent<HTMLInputElement>) =>
          debounceFn(e.target.value)
        }
        id={name}
        placeholder="Nome do produto"
      >
        {produtos &&
          produtos.map((produto) => (
            <SearchSelectItem key={produto.id} value={produto.descricao}>
              {produto.descricao}
            </SearchSelectItem>
          ))}
</SearchSelect>
```

### What is expected?

Normal size of input.

### What is actually happening?

![tremor1](https://github.com/tremorlabs/tremor/assets/10576729/b51d57f4-6bdb-4f32-8c6a-4089539bc441)
![tremor](https://github.com/tremorlabs/tremor/assets/10576729/10ff8cd8-4eaa-46af-953b-972acd5b85e6)

If I change padding directly in chrome dev tools the appearance is normal.

**Comment by severinlandolt** [comment]
Thanks! Will be fixed in the next release!
