### ISSUE TITLE
[Bug]:  Build when you use laravel inertia react stack

### ISSUE THREAD

**Issue by gildastema** [tremorlabs/tremor-npm#913]
### Tremor Version

3.13.1

### Link to minimal reproduction

https://google.com

### Steps to reproduce

Create laravel project 

> composer create-project laravel/laravel tremor-demo 

Next Install Breeze 
> composer require laravel/breeze 
Setup breeze 
> php artisan breeze:install 
Configure tremor like vite project 
Run Package install 
> npm i 
Build 
> npm run build 

### What is expected?

I expect build to run wheel

### What is actually happening?

> build
> tsc && vite build

node_modules/@tremor/react/dist/index.d.ts:4:44 - error TS2307: Cannot find module 'components/chart-elements/common' or its corresponding type declarations.

4 import { EventProps as EventProps$1 } from 'components/chart-elements/common';
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@tremor/react/dist/index.d.ts:5:58 - error TS2307: Cannot find module 'components/chart-elements/common/CustomTooltipProps' or its corresponding type declarations.

5 import { CustomTooltipType as CustomTooltipType$1 } from 'components/chart-elements/common/CustomTooltipProps';
                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@tremor/react/dist/index.d.ts:6:196 - error TS2307: Cannot find module 'lib' or its corresponding type declarations.

6 import { Color as Color$1, Size as Size$2, DeltaType as DeltaType$1, HorizontalPosition as HorizontalPosition$1, VerticalPosition as VerticalPosition$1, ValueFormatter as ValueFormatter$1 } from 'lib';

               ~~~~~

node_modules/@tremor/react/dist/index.d.ts:8:40 - error TS2307: Cannot find module 'components/chart-elements/common/BaseAnimationTimingProps' or its corresponding type declarations.
8 import BaseAnimationTimingProps$1 from 'components/chart-elements/common/BaseAnimationTimingProps';
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 4 errors in the same file, starting at: node_modules/@tremor/react/dist/index.d.ts:
![image](https://github.com/tremorlabs/tremor/assets/19803232/feabfe44-0f47-45e0-ac55-871ec4c30794)

### What browsers are you seeing the problem on?

Chrome

**Comment by severinlandolt** [comment]
Hi, unfortunately, we don't focus on developing/compatability with Laravel. What you may try is to delete your package.lock and node_modules folder and reinstall everything.

**Comment by timboozle** [comment]
For anyone else running into this issue: add `"skipLibCheck": true` to your Laravel tsconfig.json file.
