### ISSUE TITLE
[Bug]: Could not change the height for Multi-Selectect component

### ISSUE THREAD

**Issue by alamenai** [tremorlabs/tremor-npm#918]
### Tremor Version

latest

### Link to minimal reproduction

unvailabale

### Steps to reproduce

1. Install Tremor.
2. Import the Multi-Select component.
3. Change the height with className using TailwindCSS.class name.

### Code

```tsx


export function SelectRoofs({ roofs }: Props) {
  const [selectedRoofs, setSelectedRoofs] = useState(roofs)

  return (
    <div className='w-full'>
      <MultiSelect
        defaultValue={selectedRoofs.map(({ roof_id }) => roof_id.toString())}
        className='mt-2 h-full min-h-16 bg-red-400'
        icon={InspectIcon}
      >
        {roofs.map(({ roof_id, default_additional_panels }) => {
          return (
            <MultiSelectItem className='text-lg font-bold h-full' key={roof_id} value={roof_id.toString()}>
              {roof_id.toString()}
            </MultiSelectItem>
          )
        })}
      </MultiSelect>
    </div>
  )
}
```

### What is expected?

The Multi-Select component should have the same height I set.

![image](https://github.com/tremorlabs/tremor/assets/20143684/55e979d4-0b5e-4a4b-a03d-362d0bdbcc63)

### What is actually happening?

The layout that wrapped the Multi-Select changes its height.

**Comment by alamenai** [comment]
The same thing happened with the Select component.

**Comment by christopherkindl** [comment]
Hi @MenaiAla, try the following to customize the height:

```
  <MultiSelect className="[&>*]:h-20">
```

**Comment by alamenai** [comment]
Thank you @christopherkindl 

Before I close the issue, I tried the same thing with DatePicker component but the text ( placeholder ) is not the middle:

![image](https://github.com/tremorlabs/tremor/assets/20143684/1e95fb67-84a7-45d8-ae2b-6cab4f1ef65e)

## Code

```tsx

 <DatePicker className='w-full mt-2 [&>*]:h-11' locale={de} />
```

**Comment by alamenai** [comment]
Thank you @christopherkindl ,


I solved the issue in this way:

```tsx

 <DatePicker
            className='w-full mt-2 [&>*]:h-11 [&>button]:flex  [&>button]:items-center [&>div]:w-full [&_.rdp>div]:justify-center'
            locale={de}
          />
```
