### ISSUE TITLE
disabling dark mode

### ISSUE THREAD

**Issue by sinamfawork** [tremorlabs/tremor-npm#923]
is there a way to disable dark mode for components?

**Comment by mrichman** [comment]
In your `tailwind.config.{js,ts}` do `darkMode: "class"` as a top level property. I just figured this out yesterday myself.

**Comment by severinlandolt** [comment]
Thank you @mrichman for jumping in.  @sinamfawork If you need more context, checkout our theming section: https://www.tremor.so/docs/getting-started/theming#notes-on-dark-mode
