### ISSUE TITLE
[DOC]: Cannot assign to 'LineChart' because it is an import.

### ISSUE THREAD

**Issue by alamenai** [tremorlabs/tremor-npm#932]
### Tremor Version

latest

### Link to minimal reproduction

https://www.tremor.so/docs/visualizations/line-chart

### Steps to reproduce

![image](https://github.com/tremorlabs/tremor/assets/20143684/0c759468-20a2-44ea-8b2e-9cfe5eb95c6b)

### What is expected?

The name of the component should be different from the import name

### What is actually happening?

Conflicts between the component name and imported component.

**Comment by severinlandolt** [comment]
@MenaiAla Thank you for the hint, it's fixed now!
