### ISSUE TITLE
[HELP]: How to let the dates popover fit the date input? 

### ISSUE THREAD

**Issue by alamenai** [tremorlabs/tremor-npm#933]
### Tremor Version

@latest

### Link to minimal reproduction

unvailable

### Steps to reproduce

I started using the date picker component for the first time and I could not change the CSS or add the right CSS class name that let the dates Popover be the same as the Data input:

## Screenshot

![image](https://github.com/tremorlabs/tremor/assets/20143684/d2caa104-3d97-47b1-9a1d-e6d49c2c7148)

## Code

```tsx
      <DatePicker className='w-full mx-auto mt-2 min-h-11' locale={de} />
  
```

### What is expected?

The popover follow the width of the input.follows

### What is actually happening?

The Popover has a fixed-width

### What browsers are you seeing the problem on?

Chrome, Firefox

**Comment by iamtouha** [comment]
You can make the `Popover` follow the input width by using tailwindcss arbitrary variants.

```tsx
<DatePicker className="[&>div]:w-full" />
```
But the `Calendar` is width is fixed. Though you can center the `Calendar` for better visual-

```tsx
<DatePicker className="[&>div]:w-full [&_.rdp>div]:justify-center" />
```

It's a hacky way, but it works nonetheless!

**Comment by alamenai** [comment]
Thank you @iamtouha .

I guess you suggestions serves the goal.
