### ISSUE TITLE
[Bug]: Tremor Button background, border, and outline is not applied

### ISSUE THREAD

**Issue by galih56** [tremorlabs/tremor-npm#947]
### Tremor Version

^3.13.4

### Link to minimal reproduction

https://github.com/galih56/manpro-v2/tree/dev_tremor_so

### Steps to reproduce

Laravel setup : 
php artisan migrate
php artisan composer update

React Setup : 
npm install
npm run dev

The button can be seen in landing, login, register page

### What is expected?

Button must be expected to be like in the document. But it is not. It can be seen on the image

![image](https://github.com/tremorlabs/tremor/assets/33045630/bb3885a6-8b44-4c79-8722-7901e4197e27)

### What is actually happening?

I checked the css classes, i couldn't find bg-tremor-brand. Seems like something is conflicting with the tremor config. But i don't know what exactly is happening 

### What browsers are you seeing the problem on?

Chrome

**Comment by casualzach** [comment]
same issue here with the datepicker!

**Comment by casualzach** [comment]
had the same issue but is fixed by adding the tremor modules to content in the tailwind config like this:
```
module.exports = {
  content: [ 
     {...}
    './node_modules/@tremor/**/*.{js,ts,jsx,tsx}'
  ],
```

Easy miss when (like me) you skip directly to theming and don't read the installation docs

**Comment by severinlandolt** [comment]
Hi @galih56, I see you have to separate `tailwind.config.{js,ts}` files. This should unified. Please follow the advice posted by @casualzach, then everything should be working as expected.

@casualzach Thank you for jumping in.

**Comment by galih56** [comment]
@casualzach Thank you sir
My bad, At first, I already have headlessui installed in my project. And then i installed tremor with CLI without reading on the document deeply. It generated talwind.config in TS file, meanwhile my existing tailwind.config is written in JS file
