### ISSUE TITLE
[Feature]: Gauge component

### ISSUE THREAD

**Issue by alamenai** [tremorlabs/tremor-npm#965]
### What problem does this feature solve?

For some data such as speed and efficiency and performance, the gauge component explains more the meaning of the output.

Example:

![image](https://github.com/tremorlabs/tremor/assets/20143684/2f32ead5-bff8-4469-a97e-428ae4d350d4)

### What does the proposed API look like?

```tsx
<Gauge
data={data}
categories=[""]
{...props}
/>
```

**Comment by severinlandolt** [comment]
Hi! We have been building dashboards for five years now and no Gauge chart has ever made it into production. Hence, we have to say no to this proposal. 

More info [here](https://robslink.com/SAS/democd26/gauges_info.htm).
