### ISSUE TITLE
[Bug]: tooltip text overflows if text is long

### ISSUE THREAD

**Issue by AbdullahHakeemNP** [tremorlabs/tremor-npm#966]
### Tremor Version

3.14.0

### Link to minimal reproduction

no

### Steps to reproduce

just use the icon component with a tooltip 
and make the tooltip text too long

![image](https://github.com/tremorlabs/tremor/assets/150131946/e2ac4482-08f2-427c-80ab-f7ede70bdeb4)

### What is expected?

tooltip background should cover the whole text

### What is actually happening?

the text overflows the tooltip 

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Safari, Firefox

**Comment by AbdullahHakeemNP** [comment]
Is this going to be fixed anytime soon?

**Comment by jho14** [comment]
+1, the max-w-xs in the tooltip CSS is causing this.

**Comment by jho14** [comment]
Please allow for manual styling of the tooltip

**Comment by severinlandolt** [comment]
Hey there! We decided to adjust the defaults in our next release. But no Tooltip prop.

**Comment by AbdullahHakeemNP** [comment]
> Hey there! We decided to adjust the defaults in our next release. But no Tooltip prop.
![Screenshot 1445-10-15 at 10 10 29 AM](https://github.com/tremorlabs/tremor/assets/150131946/5f296c0a-e30a-439f-8f8f-1ba59d8d4e54)
the issue have not been fixed
i'm on 3.16.1

**Comment by severinlandolt** [comment]
Hi! The tooltip should wrap automatically. Like this:
![CleanShot 2024-04-24 at 11 23 40@2x](https://github.com/tremorlabs/tremor/assets/41927988/ae5defe2-4660-4d07-8a9a-40c6d11f4ea0)


Could you share a code snippet of this?

**Comment by yuhengwang7** [comment]
Hi! Similar issue here:

Code snippet:
`              <Icon
                                                        icon={StarIcon}
                                                        variant="simple"
                                                        tooltip="Patient engages poorly with texts, please prioritize calling"
                                                        />`

<img width="388" alt="Screenshot 2024-10-22 at 10 20 38 AM" src="https://github.com/user-attachments/assets/578ce8c4-125e-4570-82a4-ca11573b0b65">
