### ISSUE TITLE
[Feature]: Add color override for [bar] charts

### ISSUE THREAD

**Issue by imclint21** [tremorlabs/tremor-npm#969]
### What problem does this feature solve?

Would be nice to have the possibility to specify a specific color for an item in the [bar] chart, by example would be nice to have some bar here in red:

![image](https://github.com/tremorlabs/tremor/assets/5221349/c00ba0f4-db43-428c-8f62-e77e98018f71)

### What does the proposed API look like?

```jsx
colorOverride={[{"item1": "red"]}
```

**Comment by parisosuch** [comment]
I second this idea. In what context is the item. Is that a specific value on the x-axis or a specific value range on the y-axis.

I for one would want a feature that can color a bar based on another property in a data point.
For example, you are given a list of data points that contain the execution time, the date, and the pass/fail of that execution. The bar would be colored based on the pass/fail. Would this be different than your proposed idea?

**Comment by imclint21** [comment]
Not really, I just want the ability to change some bars depending of some conditions.

**Comment by parisosuch** [comment]
> Not really, I just want the ability to change some bars depending of some conditions.

I think this is solvable and a great feature. The Override would accept a list of x-axis values what that color should be.

**Comment by severinlandolt** [comment]
Hi! This feature is quite an exception from the norm. Imho, this is something we forward to our copy & paste components: https://tremor.so
