### ISSUE TITLE
Dropdown actions

### ISSUE THREAD

**Issue by ethndotsh** [tremorlabs/tremor-npm#97]
Maybe let dropdowns not have to be for selecting an option, but rather for performing actions e.g. Edit, Archive, Delete, etc.

This could also allow for an IconDropdown component that only shows an Icon (e.g. three vertical dots) instead of text.

**Comment by Meechie21** [comment]
> Maybe let dropdowns not have to be for selecting an option, but rather for performing actions e.g. Edit, Archive, Delete, etc.
> 
> This could also allow for an IconDropdown component that only shows an Icon (e.g. three vertical dots) instead of text.

**Comment by mitrotasios** [comment]
hey @cursecodes, thanks for the proposal and for being so involved in our library (We have not forgotten about the open PRs 😊 )! I think that makes sense, we will just need to discuss this a bit further and think of an appropriate design to implement the feature.

**Comment by mitrotasios** [comment]
hey @cursecodes, I think we will not implement this. You can achieve the same thing through the `onValueChange` prop :)
