### ISSUE TITLE
[Bug]: Link to - Installation First Component Guide is Broken

### ISSUE THREAD

**Issue by unclebay143** [tremorlabs/tremor-npm#971]
### Tremor Version

Documentation

### Link to minimal reproduction

https://www.tremor.so/docs/getting-started/installation/first-component

### Steps to reproduce

Visit: https://www.tremor.so/docs/getting-started/installation

And click the link below in the ss
![image](https://github.com/tremorlabs/tremor/assets/58919619/8417445d-2dd3-46ad-88bb-2575467dd3d3)

### What is expected?

Redirect to the first component guide

### What is actually happening?

returns 404 page
![image](https://github.com/tremorlabs/tremor/assets/58919619/266cd979-4b9a-4335-9f06-415f6c0ad4c7)

**Comment by unclebay143** [comment]
The correct url seems to be https://www.tremor.so/docs/getting-started/first-component and not https://www.tremor.so/docs/getting-started/installation/first-component

**Comment by christopherkindl** [comment]
Thanks so much for pointing this out! Just fixed it :)
