### ISSUE TITLE
Can we add our own cutom colors in the props for bar and line charts?

### ISSUE THREAD

**Issue by LombaxTech** [tremorlabs/tremor-npm#975]
### What problem does this feature solve?

right now we can only add colors predefined by tremor. It would be nice if we could also add any custom color.

**Comment by severinlandolt** [comment]
Hey @LombaxTech, you actually can! Have a look here: https://www.tremor.so/docs/getting-started/theming#custom-charts-colors

**Comment by LombaxTech** [comment]
Oh I see. I was hoping to add custom colors in a way that my users could select custom colors and have that be used in the graph. But in that case, it wouldn't be easy to change the tailwind config file right? So would it be possible to use in line css to change it to some dynamic custom value or is there some other way?
