### ISSUE TITLE
[Bug]: Minor error in documentation of DonutChart

### ISSUE THREAD

**Issue by eehnsio** [tremorlabs/tremor-npm#976]
### Tremor Version

n/a

### Link to minimal reproduction

https://www.tremor.so/docs/visualizations/donut-chart#usage-example

### Steps to reproduce

Wrong component mentioned in the usage example of donut chart

### What is expected?

"The example below s"hows a composition of a _**DonutChart**_ and Legend component."

### What is actually happening?

"The example below s"hows a composition of a **_BarChart_** and Legend component."

### Any additional comments?

Minor issue in documentation

**Comment by severinlandolt** [comment]
Thanks for the hint!
