### ISSUE TITLE
Support data with uneven splits of the x axis

### ISSUE THREAD

**Issue by dmattia** [tremorlabs/tremor-npm#98]
If I update the `LineChart` example data to look like:

```typescript
const chartdata = [
  {
    year: 1951,
    "Population growth rate": 1.74,
  },
  {
    year: 1952,
    "Population growth rate": 1.63,
  },
  {
    year: 1953,
    "Population growth rate": 1.9,
  },
  {
    year: 1954,
    "Population growth rate": 1.98,
  },
  {
    year: 1955,
    "Population growth rate": 2,
  },
  {
    year: 1999,
    "Population growth rate": 1.8,
  },
];
```

where there is a gap between 1955 and 1999. it would be great if there were a way to have the x-axis reflect this gap as opposed to displaying the data as though 1999 is just one step above 1955. 

<img width="1238" alt="Screen Shot 2022-10-11 at 8 07 50 PM" src="https://user-images.githubusercontent.com/8922077/195240708-8ec9f3ce-c695-4d88-91b8-3e224b439864.png">

This is especially useful for sparse data sets where the readings may not occur linearly

**Comment by mitrotasios** [comment]
hey @dmattia, thanks so much for your suggestion, I think that makes sense! We will most likely add this to our roadmap :)

**Comment by mitrotasios** [comment]
Thanks for the suggestion @dmattia! I think we do not have the resources to implement this for now :(
