### ISSUE TITLE
[Bug]: Typescript error

### ISSUE THREAD

**Issue by jptagorda** [tremorlabs/tremor-npm#999]
### Tremor Version

3.14.1

### Link to minimal reproduction

*

### Steps to reproduce

This error occurs right out of the box

![Screenshot 2024-03-26 at 2 10 29 AM](https://github.com/tremorlabs/tremor/assets/32463915/611cc499-591f-44ba-860b-7f28a42850df)

### What is expected?

No typescript errors upon fresh installation 

### What is actually happening?

after fresh install the error occurs when i build or compile with typescript checking

### What browsers are you seeing the problem on?

Other

**Comment by thekidnamedkd** [comment]
Have you checked that you are using the workspace version of Typescript and not your IDE? And/or that your IDE TS version is sufficiently updated?

**Comment by severinlandolt** [comment]
Hi @jptagorda, hard to pinpoint the issue. Have you tried what @thekidnamedkd has suggested?

**Comment by jptagorda** [comment]
@thekidnamedkd 

My current Typescript version was 5.4.3

**Comment by jptagorda** [comment]
@thekidnamedkd 

My current Typescript Version was 5.4.3
